// Command zonelist writes rules/zones.go, the IANA zone names the
// timezone rule accepts, from the zone database the Go toolchain ships
// ($GOROOT/lib/time/zoneinfo.zip).
//
// It is run by hand when the Go toolchain's zone database is updated, not by
// go generate, so a build with a different Go patch release does not see a
// drift it cannot act on:
//
//	go run ./rules/internal/zonelist
package main

import (
	"archive/zip"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
)

// excluded are the entries of the database that are not zones a stored value
// could mean.
var excluded = map[string]bool{"Factory": true, "localtime": true, "posixrules": true}

func main() {
	count, err := run()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %d zones\n", count)
}

// run writes zones.go and returns how many zones it lists.
func run() (int, error) {
	goroot, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return 0, fmt.Errorf("asking the go command for GOROOT: %w", err)
	}
	version, err := exec.Command("go", "env", "GOVERSION").Output()
	if err != nil {
		return 0, fmt.Errorf("asking the go command for its version: %w", err)
	}

	archive, err := zip.OpenReader(filepath.Join(strings.TrimSpace(string(goroot)), "lib", "time", "zoneinfo.zip"))
	if err != nil {
		return 0, err
	}
	defer func() { _ = archive.Close() }()

	var names []string
	for _, file := range archive.File {
		if strings.HasSuffix(file.Name, "/") || excluded[file.Name] {
			continue
		}
		names = append(names, file.Name)
	}
	slices.Sort(names)

	var source bytes.Buffer
	source.WriteString("// Code generated by zonelist from the " + strings.TrimSpace(string(version)) +
		" zone database. DO NOT EDIT.\n\npackage rules\n\n")
	source.WriteString("// timeZoneNames are the IANA time zone names the timezone rule accepts, sorted.\nvar timeZoneNames = [...]string{\n")
	for _, name := range names {
		source.WriteString("\t" + strconv.Quote(name) + ",\n")
	}
	source.WriteString("}\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return 0, err
	}
	return len(names), os.WriteFile(filepath.Join("rules", "zones.go"), formatted, 0o600)
}
