// Code generated by vogue. DO NOT EDIT.

package catalogue

import (
	"errors"
	"fmt"
	"net/mail"
	"net/url"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/MathiasHilgert/vogue/examples/validation"
	"github.com/govalues/decimal"
)

var stockCodePattern = regexp.MustCompile(`^[A-Z]{3}-[0-9]{4}$`)

// TrimmedName is a name with the whitespace around it removed. The `required`
// after it is what proves the normalizer ran: a value that was nothing but
// whitespace is empty by the time the check sees it.
type TrimmedName struct {
	value string
	set   bool
}

// NewTrimmedName validates raw and returns the TrimmedName it describes.
func NewTrimmedName(raw string) (TrimmedName, error) {
	var trimmedName TrimmedName // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.TrimSpace(value)
	if value == "" {
		failures.Add("trimmedName", "required", "is required")

		return trimmedName, failures.Err()
	}

	err := failures.Err()
	if err != nil {
		return trimmedName, err
	}

	return TrimmedName{value: value, set: true}, nil
}

// String returns the validated value.
func (trimmedName TrimmedName) String() string { return trimmedName.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (trimmedName TrimmedName) IsZero() bool { return !trimmedName.set }

// Equal reports whether both hold the same value.
func (trimmedName TrimmedName) Equal(other TrimmedName) bool { return trimmedName == other }

// MarshalText implements encoding.TextMarshaler; the zero TrimmedName has no text form.
func (trimmedName TrimmedName) MarshalText() ([]byte, error) {
	if trimmedName.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero TrimmedName: %w", errors.ErrUnsupported)
	}

	return []byte(trimmedName.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (trimmedName *TrimmedName) UnmarshalText(data []byte) error {
	parsed, err := NewTrimmedName(string(data))
	if err != nil {
		return err
	}

	*trimmedName = parsed

	return nil
}

// SquishedName is a name whose internal whitespace is collapsed.
type SquishedName struct {
	value string
	set   bool
}

// NewSquishedName validates raw and returns the SquishedName it describes.
func NewSquishedName(raw string) (SquishedName, error) {
	var squishedName SquishedName // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.Join(strings.Fields(value), " ")
	if value == "" {
		failures.Add("squishedName", "required", "is required")

		return squishedName, failures.Err()
	}

	err := failures.Err()
	if err != nil {
		return squishedName, err
	}

	return SquishedName{value: value, set: true}, nil
}

// String returns the validated value.
func (squishedName SquishedName) String() string { return squishedName.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (squishedName SquishedName) IsZero() bool { return !squishedName.set }

// Equal reports whether both hold the same value.
func (squishedName SquishedName) Equal(other SquishedName) bool { return squishedName == other }

// MarshalText implements encoding.TextMarshaler; the zero SquishedName has no text form.
func (squishedName SquishedName) MarshalText() ([]byte, error) {
	if squishedName.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero SquishedName: %w", errors.ErrUnsupported)
	}

	return []byte(squishedName.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (squishedName *SquishedName) UnmarshalText(data []byte) error {
	parsed, err := NewSquishedName(string(data))
	if err != nil {
		return err
	}

	*squishedName = parsed

	return nil
}

// LoweredName is a name folded to lower case.
type LoweredName struct {
	value string
	set   bool
}

// NewLoweredName validates raw and returns the LoweredName it describes.
func NewLoweredName(raw string) (LoweredName, error) {
	var loweredName LoweredName // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.ToLower(value)
	if value == "" {
		failures.Add("loweredName", "required", "is required")

		return loweredName, failures.Err()
	}

	err := failures.Err()
	if err != nil {
		return loweredName, err
	}

	return LoweredName{value: value, set: true}, nil
}

// String returns the validated value.
func (loweredName LoweredName) String() string { return loweredName.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (loweredName LoweredName) IsZero() bool { return !loweredName.set }

// Equal reports whether both hold the same value.
func (loweredName LoweredName) Equal(other LoweredName) bool { return loweredName == other }

// MarshalText implements encoding.TextMarshaler; the zero LoweredName has no text form.
func (loweredName LoweredName) MarshalText() ([]byte, error) {
	if loweredName.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero LoweredName: %w", errors.ErrUnsupported)
	}

	return []byte(loweredName.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (loweredName *LoweredName) UnmarshalText(data []byte) error {
	parsed, err := NewLoweredName(string(data))
	if err != nil {
		return err
	}

	*loweredName = parsed

	return nil
}

// UpperedName is a name folded to upper case.
type UpperedName struct {
	value string
	set   bool
}

// NewUpperedName validates raw and returns the UpperedName it describes.
func NewUpperedName(raw string) (UpperedName, error) {
	var upperedName UpperedName // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.ToUpper(value)
	if value == "" {
		failures.Add("upperedName", "required", "is required")

		return upperedName, failures.Err()
	}

	err := failures.Err()
	if err != nil {
		return upperedName, err
	}

	return UpperedName{value: value, set: true}, nil
}

// String returns the validated value.
func (upperedName UpperedName) String() string { return upperedName.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (upperedName UpperedName) IsZero() bool { return !upperedName.set }

// Equal reports whether both hold the same value.
func (upperedName UpperedName) Equal(other UpperedName) bool { return upperedName == other }

// MarshalText implements encoding.TextMarshaler; the zero UpperedName has no text form.
func (upperedName UpperedName) MarshalText() ([]byte, error) {
	if upperedName.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero UpperedName: %w", errors.ErrUnsupported)
	}

	return []byte(upperedName.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (upperedName *UpperedName) UnmarshalText(data []byte) error {
	parsed, err := NewUpperedName(string(data))
	if err != nil {
		return err
	}

	*upperedName = parsed

	return nil
}

// TrimmedOnly proves what `trim` rewrites.
type TrimmedOnly struct {
	value string
	set   bool
}

// NewTrimmedOnly validates raw and returns the TrimmedOnly it describes.
func NewTrimmedOnly(raw string) (TrimmedOnly, error) {
	var trimmedOnly TrimmedOnly // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.TrimSpace(value)

	err := failures.Err()
	if err != nil {
		return trimmedOnly, err
	}

	return TrimmedOnly{value: value, set: true}, nil
}

// String returns the validated value.
func (trimmedOnly TrimmedOnly) String() string { return trimmedOnly.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (trimmedOnly TrimmedOnly) IsZero() bool { return !trimmedOnly.set }

// Equal reports whether both hold the same value.
func (trimmedOnly TrimmedOnly) Equal(other TrimmedOnly) bool { return trimmedOnly == other }

// MarshalText implements encoding.TextMarshaler; the zero TrimmedOnly has no text form.
func (trimmedOnly TrimmedOnly) MarshalText() ([]byte, error) {
	if trimmedOnly.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero TrimmedOnly: %w", errors.ErrUnsupported)
	}

	return []byte(trimmedOnly.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (trimmedOnly *TrimmedOnly) UnmarshalText(data []byte) error {
	parsed, err := NewTrimmedOnly(string(data))
	if err != nil {
		return err
	}

	*trimmedOnly = parsed

	return nil
}

// SquishedOnly proves what `squish` rewrites.
type SquishedOnly struct {
	value string
	set   bool
}

// NewSquishedOnly validates raw and returns the SquishedOnly it describes.
func NewSquishedOnly(raw string) (SquishedOnly, error) {
	var squishedOnly SquishedOnly // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.Join(strings.Fields(value), " ")

	err := failures.Err()
	if err != nil {
		return squishedOnly, err
	}

	return SquishedOnly{value: value, set: true}, nil
}

// String returns the validated value.
func (squishedOnly SquishedOnly) String() string { return squishedOnly.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (squishedOnly SquishedOnly) IsZero() bool { return !squishedOnly.set }

// Equal reports whether both hold the same value.
func (squishedOnly SquishedOnly) Equal(other SquishedOnly) bool { return squishedOnly == other }

// MarshalText implements encoding.TextMarshaler; the zero SquishedOnly has no text form.
func (squishedOnly SquishedOnly) MarshalText() ([]byte, error) {
	if squishedOnly.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero SquishedOnly: %w", errors.ErrUnsupported)
	}

	return []byte(squishedOnly.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (squishedOnly *SquishedOnly) UnmarshalText(data []byte) error {
	parsed, err := NewSquishedOnly(string(data))
	if err != nil {
		return err
	}

	*squishedOnly = parsed

	return nil
}

// LoweredOnly proves what `lower` rewrites.
type LoweredOnly struct {
	value string
	set   bool
}

// NewLoweredOnly validates raw and returns the LoweredOnly it describes.
func NewLoweredOnly(raw string) (LoweredOnly, error) {
	var loweredOnly LoweredOnly // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.ToLower(value)

	err := failures.Err()
	if err != nil {
		return loweredOnly, err
	}

	return LoweredOnly{value: value, set: true}, nil
}

// String returns the validated value.
func (loweredOnly LoweredOnly) String() string { return loweredOnly.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (loweredOnly LoweredOnly) IsZero() bool { return !loweredOnly.set }

// Equal reports whether both hold the same value.
func (loweredOnly LoweredOnly) Equal(other LoweredOnly) bool { return loweredOnly == other }

// MarshalText implements encoding.TextMarshaler; the zero LoweredOnly has no text form.
func (loweredOnly LoweredOnly) MarshalText() ([]byte, error) {
	if loweredOnly.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero LoweredOnly: %w", errors.ErrUnsupported)
	}

	return []byte(loweredOnly.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (loweredOnly *LoweredOnly) UnmarshalText(data []byte) error {
	parsed, err := NewLoweredOnly(string(data))
	if err != nil {
		return err
	}

	*loweredOnly = parsed

	return nil
}

// UpperedOnly proves what `upper` rewrites.
type UpperedOnly struct {
	value string
	set   bool
}

// NewUpperedOnly validates raw and returns the UpperedOnly it describes.
func NewUpperedOnly(raw string) (UpperedOnly, error) {
	var upperedOnly UpperedOnly // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.ToUpper(value)

	err := failures.Err()
	if err != nil {
		return upperedOnly, err
	}

	return UpperedOnly{value: value, set: true}, nil
}

// String returns the validated value.
func (upperedOnly UpperedOnly) String() string { return upperedOnly.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (upperedOnly UpperedOnly) IsZero() bool { return !upperedOnly.set }

// Equal reports whether both hold the same value.
func (upperedOnly UpperedOnly) Equal(other UpperedOnly) bool { return upperedOnly == other }

// MarshalText implements encoding.TextMarshaler; the zero UpperedOnly has no text form.
func (upperedOnly UpperedOnly) MarshalText() ([]byte, error) {
	if upperedOnly.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero UpperedOnly: %w", errors.ErrUnsupported)
	}

	return []byte(upperedOnly.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (upperedOnly *UpperedOnly) UnmarshalText(data []byte) error {
	parsed, err := NewUpperedOnly(string(data))
	if err != nil {
		return err
	}

	*upperedOnly = parsed

	return nil
}

// RequiredName is a name that must be given.
type RequiredName struct {
	value string
	set   bool
}

// NewRequiredName validates raw and returns the RequiredName it describes.
func NewRequiredName(raw string) (RequiredName, error) {
	var requiredName RequiredName // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if value == "" {
		failures.Add("requiredName", "required", "is required")

		return requiredName, failures.Err()
	}

	err := failures.Err()
	if err != nil {
		return requiredName, err
	}

	return RequiredName{value: value, set: true}, nil
}

// String returns the validated value.
func (requiredName RequiredName) String() string { return requiredName.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (requiredName RequiredName) IsZero() bool { return !requiredName.set }

// Equal reports whether both hold the same value.
func (requiredName RequiredName) Equal(other RequiredName) bool { return requiredName == other }

// MarshalText implements encoding.TextMarshaler; the zero RequiredName has no text form.
func (requiredName RequiredName) MarshalText() ([]byte, error) {
	if requiredName.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero RequiredName: %w", errors.ErrUnsupported)
	}

	return []byte(requiredName.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (requiredName *RequiredName) UnmarshalText(data []byte) error {
	parsed, err := NewRequiredName(string(data))
	if err != nil {
		return err
	}

	*requiredName = parsed

	return nil
}

// ShortName is a name of at least one character.
type ShortName struct {
	value string
	set   bool
}

// NewShortName validates raw and returns the ShortName it describes.
func NewShortName(raw string) (ShortName, error) {
	var shortName ShortName // stays zero unless every rule passes
	var failures validation.Validation

	const minimumParameter = 1

	value := raw
	if utf8.RuneCountInString(value) < minimumParameter {
		failures.Add("shortName", "min", "length must be at least 1")
	}

	err := failures.Err()
	if err != nil {
		return shortName, err
	}

	return ShortName{value: value, set: true}, nil
}

// String returns the validated value.
func (shortName ShortName) String() string { return shortName.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (shortName ShortName) IsZero() bool { return !shortName.set }

// Equal reports whether both hold the same value.
func (shortName ShortName) Equal(other ShortName) bool { return shortName == other }

// MarshalText implements encoding.TextMarshaler; the zero ShortName has no text form.
func (shortName ShortName) MarshalText() ([]byte, error) {
	if shortName.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero ShortName: %w", errors.ErrUnsupported)
	}

	return []byte(shortName.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (shortName *ShortName) UnmarshalText(data []byte) error {
	parsed, err := NewShortName(string(data))
	if err != nil {
		return err
	}

	*shortName = parsed

	return nil
}

// LongerName is a name of at least three characters.
type LongerName struct {
	value string
	set   bool
}

// NewLongerName validates raw and returns the LongerName it describes.
func NewLongerName(raw string) (LongerName, error) {
	var longerName LongerName // stays zero unless every rule passes
	var failures validation.Validation

	const minimumParameter = 3

	value := raw
	if utf8.RuneCountInString(value) < minimumParameter {
		failures.Add("longerName", "min", "length must be at least 3")
	}

	err := failures.Err()
	if err != nil {
		return longerName, err
	}

	return LongerName{value: value, set: true}, nil
}

// String returns the validated value.
func (longerName LongerName) String() string { return longerName.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (longerName LongerName) IsZero() bool { return !longerName.set }

// Equal reports whether both hold the same value.
func (longerName LongerName) Equal(other LongerName) bool { return longerName == other }

// MarshalText implements encoding.TextMarshaler; the zero LongerName has no text form.
func (longerName LongerName) MarshalText() ([]byte, error) {
	if longerName.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero LongerName: %w", errors.ErrUnsupported)
	}

	return []byte(longerName.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (longerName *LongerName) UnmarshalText(data []byte) error {
	parsed, err := NewLongerName(string(data))
	if err != nil {
		return err
	}

	*longerName = parsed

	return nil
}

// BoundedName is a name of at most four characters.
type BoundedName struct {
	value string
	set   bool
}

// NewBoundedName validates raw and returns the BoundedName it describes.
func NewBoundedName(raw string) (BoundedName, error) {
	var boundedName BoundedName // stays zero unless every rule passes
	var failures validation.Validation

	const maximumParameter = 4

	value := raw
	if utf8.RuneCountInString(value) > maximumParameter {
		failures.Add("boundedName", "max", "length must be at most 4")
	}

	err := failures.Err()
	if err != nil {
		return boundedName, err
	}

	return BoundedName{value: value, set: true}, nil
}

// String returns the validated value.
func (boundedName BoundedName) String() string { return boundedName.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (boundedName BoundedName) IsZero() bool { return !boundedName.set }

// Equal reports whether both hold the same value.
func (boundedName BoundedName) Equal(other BoundedName) bool { return boundedName == other }

// MarshalText implements encoding.TextMarshaler; the zero BoundedName has no text form.
func (boundedName BoundedName) MarshalText() ([]byte, error) {
	if boundedName.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero BoundedName: %w", errors.ErrUnsupported)
	}

	return []byte(boundedName.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (boundedName *BoundedName) UnmarshalText(data []byte) error {
	parsed, err := NewBoundedName(string(data))
	if err != nil {
		return err
	}

	*boundedName = parsed

	return nil
}

// CurrencyCode is a currency code of exactly three characters.
type CurrencyCode struct {
	value string
	set   bool
}

// NewCurrencyCode validates raw and returns the CurrencyCode it describes.
func NewCurrencyCode(raw string) (CurrencyCode, error) {
	var currencyCode CurrencyCode // stays zero unless every rule passes
	var failures validation.Validation

	const lengthParameter = 3

	value := raw
	if utf8.RuneCountInString(value) != lengthParameter {
		failures.Add("currencyCode", "len", "must be exactly 3 characters long")
	}

	err := failures.Err()
	if err != nil {
		return currencyCode, err
	}

	return CurrencyCode{value: value, set: true}, nil
}

// String returns the validated value.
func (currencyCode CurrencyCode) String() string { return currencyCode.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (currencyCode CurrencyCode) IsZero() bool { return !currencyCode.set }

// Equal reports whether both hold the same value.
func (currencyCode CurrencyCode) Equal(other CurrencyCode) bool { return currencyCode == other }

// MarshalText implements encoding.TextMarshaler; the zero CurrencyCode has no text form.
func (currencyCode CurrencyCode) MarshalText() ([]byte, error) {
	if currencyCode.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero CurrencyCode: %w", errors.ErrUnsupported)
	}

	return []byte(currencyCode.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (currencyCode *CurrencyCode) UnmarshalText(data []byte) error {
	parsed, err := NewCurrencyCode(string(data))
	if err != nil {
		return err
	}

	*currencyCode = parsed

	return nil
}

// EmailAddress is a mailbox a guest can be written to at.
type EmailAddress struct {
	value string
	set   bool
}

// NewEmailAddress validates raw and returns the EmailAddress it describes.
func NewEmailAddress(raw string) (EmailAddress, error) {
	var emailAddress EmailAddress // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if !emailAddress.isEmail(value) {
		failures.Add("emailAddress", "email", "must be a valid email address")
	}

	err := failures.Err()
	if err != nil {
		return emailAddress, err
	}

	return EmailAddress{value: value, set: true}, nil
}

// String returns the validated value.
func (emailAddress EmailAddress) String() string { return emailAddress.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (emailAddress EmailAddress) IsZero() bool { return !emailAddress.set }

// Equal reports whether both hold the same value.
func (emailAddress EmailAddress) Equal(other EmailAddress) bool { return emailAddress == other }

// MarshalText implements encoding.TextMarshaler; the zero EmailAddress has no text form.
func (emailAddress EmailAddress) MarshalText() ([]byte, error) {
	if emailAddress.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero EmailAddress: %w", errors.ErrUnsupported)
	}

	return []byte(emailAddress.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (emailAddress *EmailAddress) UnmarshalText(data []byte) error {
	parsed, err := NewEmailAddress(string(data))
	if err != nil {
		return err
	}

	*emailAddress = parsed

	return nil
}

// isEmail implements the email rule of NewEmailAddress.
func (EmailAddress) isEmail(value string) bool {
	address, err := mail.ParseAddress(value)

	return err == nil && address.Name == "" && address.Address == value
}

// MenuLink is the address of a published menu.
type MenuLink struct {
	value string
	set   bool
}

// NewMenuLink validates raw and returns the MenuLink it describes.
func NewMenuLink(raw string) (MenuLink, error) {
	var menuLink MenuLink // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if !menuLink.isURL(value) {
		failures.Add("menuLink", "url", "must be a valid http or https URL")
	}

	err := failures.Err()
	if err != nil {
		return menuLink, err
	}

	return MenuLink{value: value, set: true}, nil
}

// String returns the validated value.
func (menuLink MenuLink) String() string { return menuLink.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (menuLink MenuLink) IsZero() bool { return !menuLink.set }

// Equal reports whether both hold the same value.
func (menuLink MenuLink) Equal(other MenuLink) bool { return menuLink == other }

// MarshalText implements encoding.TextMarshaler; the zero MenuLink has no text form.
func (menuLink MenuLink) MarshalText() ([]byte, error) {
	if menuLink.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero MenuLink: %w", errors.ErrUnsupported)
	}

	return []byte(menuLink.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (menuLink *MenuLink) UnmarshalText(data []byte) error {
	parsed, err := NewMenuLink(string(data))
	if err != nil {
		return err
	}

	*menuLink = parsed

	return nil
}

// isURL implements the url rule of NewMenuLink.
func (MenuLink) isURL(value string) bool {
	parsed, err := url.ParseRequestURI(value)
	if err != nil || parsed.Host == "" {
		return false
	}

	return parsed.Scheme == "http" || parsed.Scheme == "https"
}

// ExternalRef is an identifier another system assigned, written as a UUID.
type ExternalRef struct {
	value string
	set   bool
}

// NewExternalRef validates raw and returns the ExternalRef it describes.
func NewExternalRef(raw string) (ExternalRef, error) {
	var externalRef ExternalRef // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if !externalRef.isUUID(value) {
		failures.Add("externalRef", "uuid", "must be a valid UUID")
	}

	err := failures.Err()
	if err != nil {
		return externalRef, err
	}

	return ExternalRef{value: value, set: true}, nil
}

// String returns the validated value.
func (externalRef ExternalRef) String() string { return externalRef.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (externalRef ExternalRef) IsZero() bool { return !externalRef.set }

// Equal reports whether both hold the same value.
func (externalRef ExternalRef) Equal(other ExternalRef) bool { return externalRef == other }

// MarshalText implements encoding.TextMarshaler; the zero ExternalRef has no text form.
func (externalRef ExternalRef) MarshalText() ([]byte, error) {
	if externalRef.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero ExternalRef: %w", errors.ErrUnsupported)
	}

	return []byte(externalRef.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (externalRef *ExternalRef) UnmarshalText(data []byte) error {
	parsed, err := NewExternalRef(string(data))
	if err != nil {
		return err
	}

	*externalRef = parsed

	return nil
}

// isUUID implements the uuid rule of NewExternalRef.
func (ExternalRef) isUUID(value string) bool {
	const (
		layout    = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
		hexDigits = "0123456789abcdefABCDEF"
	)

	if len(value) != len(layout) {
		return false
	}

	for index := range len(layout) {
		allowed := hexDigits
		if layout[index] == '-' {
			allowed = "-"
		}

		if strings.IndexByte(allowed, value[index]) < 0 {
			return false
		}
	}

	return true
}

// ZoneName is the IANA time zone a venue keeps its hours in.
type ZoneName struct {
	value string
	set   bool
}

// NewZoneName validates raw and returns the ZoneName it describes.
func NewZoneName(raw string) (ZoneName, error) {
	var zoneName ZoneName // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if !zoneName.isTimeZone(value) {
		failures.Add("zoneName", "timezone", "must be an IANA time zone")
	}

	err := failures.Err()
	if err != nil {
		return zoneName, err
	}

	return ZoneName{value: value, set: true}, nil
}

// String returns the validated value.
func (zoneName ZoneName) String() string { return zoneName.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (zoneName ZoneName) IsZero() bool { return !zoneName.set }

// Equal reports whether both hold the same value.
func (zoneName ZoneName) Equal(other ZoneName) bool { return zoneName == other }

// MarshalText implements encoding.TextMarshaler; the zero ZoneName has no text form.
func (zoneName ZoneName) MarshalText() ([]byte, error) {
	if zoneName.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero ZoneName: %w", errors.ErrUnsupported)
	}

	return []byte(zoneName.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (zoneName *ZoneName) UnmarshalText(data []byte) error {
	parsed, err := NewZoneName(string(data))
	if err != nil {
		return err
	}

	*zoneName = parsed

	return nil
}

// isTimeZone implements the timezone rule of NewZoneName.
//
//nolint:funlen // the body lists data, every name the rule accepts, not logic.
func (ZoneName) isTimeZone(value string) bool {
	switch value {
	case "Africa/Abidjan", "Africa/Accra", "Africa/Addis_Ababa", "Africa/Algiers", "Africa/Asmara",
		"Africa/Asmera", "Africa/Bamako", "Africa/Bangui", "Africa/Banjul", "Africa/Bissau",
		"Africa/Blantyre", "Africa/Brazzaville", "Africa/Bujumbura", "Africa/Cairo", "Africa/Casablanca",
		"Africa/Ceuta", "Africa/Conakry", "Africa/Dakar", "Africa/Dar_es_Salaam", "Africa/Djibouti",
		"Africa/Douala", "Africa/El_Aaiun", "Africa/Freetown", "Africa/Gaborone", "Africa/Harare",
		"Africa/Johannesburg", "Africa/Juba", "Africa/Kampala", "Africa/Khartoum", "Africa/Kigali",
		"Africa/Kinshasa", "Africa/Lagos", "Africa/Libreville", "Africa/Lome", "Africa/Luanda",
		"Africa/Lubumbashi", "Africa/Lusaka", "Africa/Malabo", "Africa/Maputo", "Africa/Maseru",
		"Africa/Mbabane", "Africa/Mogadishu", "Africa/Monrovia", "Africa/Nairobi", "Africa/Ndjamena",
		"Africa/Niamey", "Africa/Nouakchott", "Africa/Ouagadougou", "Africa/Porto-Novo",
		"Africa/Sao_Tome", "Africa/Timbuktu", "Africa/Tripoli", "Africa/Tunis", "Africa/Windhoek",
		"America/Adak", "America/Anchorage", "America/Anguilla", "America/Antigua", "America/Araguaina",
		"America/Argentina/Buenos_Aires", "America/Argentina/Catamarca",
		"America/Argentina/ComodRivadavia", "America/Argentina/Cordoba", "America/Argentina/Jujuy",
		"America/Argentina/La_Rioja", "America/Argentina/Mendoza", "America/Argentina/Rio_Gallegos",
		"America/Argentina/Salta", "America/Argentina/San_Juan", "America/Argentina/San_Luis",
		"America/Argentina/Tucuman", "America/Argentina/Ushuaia", "America/Aruba", "America/Asuncion",
		"America/Atikokan", "America/Atka", "America/Bahia", "America/Bahia_Banderas",
		"America/Barbados", "America/Belem", "America/Belize", "America/Blanc-Sablon",
		"America/Boa_Vista", "America/Bogota", "America/Boise", "America/Buenos_Aires",
		"America/Cambridge_Bay", "America/Campo_Grande", "America/Cancun", "America/Caracas",
		"America/Catamarca", "America/Cayenne", "America/Cayman", "America/Chicago", "America/Chihuahua",
		"America/Ciudad_Juarez", "America/Coral_Harbour", "America/Cordoba", "America/Costa_Rica",
		"America/Coyhaique", "America/Creston", "America/Cuiaba", "America/Curacao",
		"America/Danmarkshavn", "America/Dawson", "America/Dawson_Creek", "America/Denver",
		"America/Detroit", "America/Dominica", "America/Edmonton", "America/Eirunepe",
		"America/El_Salvador", "America/Ensenada", "America/Fort_Nelson", "America/Fort_Wayne",
		"America/Fortaleza", "America/Glace_Bay", "America/Godthab", "America/Goose_Bay",
		"America/Grand_Turk", "America/Grenada", "America/Guadeloupe", "America/Guatemala",
		"America/Guayaquil", "America/Guyana", "America/Halifax", "America/Havana", "America/Hermosillo",
		"America/Indiana/Indianapolis", "America/Indiana/Knox", "America/Indiana/Marengo",
		"America/Indiana/Petersburg", "America/Indiana/Tell_City", "America/Indiana/Vevay",
		"America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Indianapolis", "America/Inuvik",
		"America/Iqaluit", "America/Jamaica", "America/Jujuy", "America/Juneau",
		"America/Kentucky/Louisville", "America/Kentucky/Monticello", "America/Knox_IN",
		"America/Kralendijk", "America/La_Paz", "America/Lima", "America/Los_Angeles",
		"America/Louisville", "America/Lower_Princes", "America/Maceio", "America/Managua",
		"America/Manaus", "America/Marigot", "America/Martinique", "America/Matamoros",
		"America/Mazatlan", "America/Mendoza", "America/Menominee", "America/Merida",
		"America/Metlakatla", "America/Mexico_City", "America/Miquelon", "America/Moncton",
		"America/Monterrey", "America/Montevideo", "America/Montreal", "America/Montserrat",
		"America/Nassau", "America/New_York", "America/Nipigon", "America/Nome", "America/Noronha",
		"America/North_Dakota/Beulah", "America/North_Dakota/Center", "America/North_Dakota/New_Salem",
		"America/Nuuk", "America/Ojinaga", "America/Panama", "America/Pangnirtung", "America/Paramaribo",
		"America/Phoenix", "America/Port-au-Prince", "America/Port_of_Spain", "America/Porto_Acre",
		"America/Porto_Velho", "America/Puerto_Rico", "America/Punta_Arenas", "America/Rainy_River",
		"America/Rankin_Inlet", "America/Recife", "America/Regina", "America/Resolute",
		"America/Rio_Branco", "America/Rosario", "America/Santa_Isabel", "America/Santarem",
		"America/Santiago", "America/Santo_Domingo", "America/Sao_Paulo", "America/Scoresbysund",
		"America/Shiprock", "America/Sitka", "America/St_Barthelemy", "America/St_Johns",
		"America/St_Kitts", "America/St_Lucia", "America/St_Thomas", "America/St_Vincent",
		"America/Swift_Current", "America/Tegucigalpa", "America/Thule", "America/Thunder_Bay",
		"America/Tijuana", "America/Toronto", "America/Tortola", "America/Vancouver", "America/Virgin",
		"America/Whitehorse", "America/Winnipeg", "America/Yakutat", "America/Yellowknife",
		"Antarctica/Casey", "Antarctica/Davis", "Antarctica/DumontDUrville", "Antarctica/Macquarie",
		"Antarctica/Mawson", "Antarctica/McMurdo", "Antarctica/Palmer", "Antarctica/Rothera",
		"Antarctica/South_Pole", "Antarctica/Syowa", "Antarctica/Troll", "Antarctica/Vostok",
		"Arctic/Longyearbyen", "Asia/Aden", "Asia/Almaty", "Asia/Amman", "Asia/Anadyr", "Asia/Aqtau",
		"Asia/Aqtobe", "Asia/Ashgabat", "Asia/Ashkhabad", "Asia/Atyrau", "Asia/Baghdad", "Asia/Bahrain",
		"Asia/Baku", "Asia/Bangkok", "Asia/Barnaul", "Asia/Beirut", "Asia/Bishkek", "Asia/Brunei",
		"Asia/Calcutta", "Asia/Chita", "Asia/Choibalsan", "Asia/Chongqing", "Asia/Chungking",
		"Asia/Colombo", "Asia/Dacca", "Asia/Damascus", "Asia/Dhaka", "Asia/Dili", "Asia/Dubai",
		"Asia/Dushanbe", "Asia/Famagusta", "Asia/Gaza", "Asia/Harbin", "Asia/Hebron", "Asia/Ho_Chi_Minh",
		"Asia/Hong_Kong", "Asia/Hovd", "Asia/Irkutsk", "Asia/Istanbul", "Asia/Jakarta", "Asia/Jayapura",
		"Asia/Jerusalem", "Asia/Kabul", "Asia/Kamchatka", "Asia/Karachi", "Asia/Kashgar",
		"Asia/Kathmandu", "Asia/Katmandu", "Asia/Khandyga", "Asia/Kolkata", "Asia/Krasnoyarsk",
		"Asia/Kuala_Lumpur", "Asia/Kuching", "Asia/Kuwait", "Asia/Macao", "Asia/Macau", "Asia/Magadan",
		"Asia/Makassar", "Asia/Manila", "Asia/Muscat", "Asia/Nicosia", "Asia/Novokuznetsk",
		"Asia/Novosibirsk", "Asia/Omsk", "Asia/Oral", "Asia/Phnom_Penh", "Asia/Pontianak",
		"Asia/Pyongyang", "Asia/Qatar", "Asia/Qostanay", "Asia/Qyzylorda", "Asia/Rangoon", "Asia/Riyadh",
		"Asia/Saigon", "Asia/Sakhalin", "Asia/Samarkand", "Asia/Seoul", "Asia/Shanghai",
		"Asia/Singapore", "Asia/Srednekolymsk", "Asia/Taipei", "Asia/Tashkent", "Asia/Tbilisi",
		"Asia/Tehran", "Asia/Tel_Aviv", "Asia/Thimbu", "Asia/Thimphu", "Asia/Tokyo", "Asia/Tomsk",
		"Asia/Ujung_Pandang", "Asia/Ulaanbaatar", "Asia/Ulan_Bator", "Asia/Urumqi", "Asia/Ust-Nera",
		"Asia/Vientiane", "Asia/Vladivostok", "Asia/Yakutsk", "Asia/Yangon", "Asia/Yekaterinburg",
		"Asia/Yerevan", "Atlantic/Azores", "Atlantic/Bermuda", "Atlantic/Canary", "Atlantic/Cape_Verde",
		"Atlantic/Faeroe", "Atlantic/Faroe", "Atlantic/Jan_Mayen", "Atlantic/Madeira",
		"Atlantic/Reykjavik", "Atlantic/South_Georgia", "Atlantic/St_Helena", "Atlantic/Stanley",
		"Australia/ACT", "Australia/Adelaide", "Australia/Brisbane", "Australia/Broken_Hill",
		"Australia/Canberra", "Australia/Currie", "Australia/Darwin", "Australia/Eucla",
		"Australia/Hobart", "Australia/LHI", "Australia/Lindeman", "Australia/Lord_Howe",
		"Australia/Melbourne", "Australia/NSW", "Australia/North", "Australia/Perth",
		"Australia/Queensland", "Australia/South", "Australia/Sydney", "Australia/Tasmania",
		"Australia/Victoria", "Australia/West", "Australia/Yancowinna", "Brazil/Acre",
		"Brazil/DeNoronha", "Brazil/East", "Brazil/West", "CET", "CST6CDT", "Canada/Atlantic",
		"Canada/Central", "Canada/Eastern", "Canada/Mountain", "Canada/Newfoundland", "Canada/Pacific",
		"Canada/Saskatchewan", "Canada/Yukon", "Chile/Continental", "Chile/EasterIsland", "Cuba", "EET",
		"EST", "EST5EDT", "Egypt", "Eire", "Etc/GMT", "Etc/GMT+0", "Etc/GMT+1", "Etc/GMT+10",
		"Etc/GMT+11", "Etc/GMT+12", "Etc/GMT+2", "Etc/GMT+3", "Etc/GMT+4", "Etc/GMT+5", "Etc/GMT+6",
		"Etc/GMT+7", "Etc/GMT+8", "Etc/GMT+9", "Etc/GMT-0", "Etc/GMT-1", "Etc/GMT-10", "Etc/GMT-11",
		"Etc/GMT-12", "Etc/GMT-13", "Etc/GMT-14", "Etc/GMT-2", "Etc/GMT-3", "Etc/GMT-4", "Etc/GMT-5",
		"Etc/GMT-6", "Etc/GMT-7", "Etc/GMT-8", "Etc/GMT-9", "Etc/GMT0", "Etc/Greenwich", "Etc/UCT",
		"Etc/UTC", "Etc/Universal", "Etc/Zulu", "Europe/Amsterdam", "Europe/Andorra", "Europe/Astrakhan",
		"Europe/Athens", "Europe/Belfast", "Europe/Belgrade", "Europe/Berlin", "Europe/Bratislava",
		"Europe/Brussels", "Europe/Bucharest", "Europe/Budapest", "Europe/Busingen", "Europe/Chisinau",
		"Europe/Copenhagen", "Europe/Dublin", "Europe/Gibraltar", "Europe/Guernsey", "Europe/Helsinki",
		"Europe/Isle_of_Man", "Europe/Istanbul", "Europe/Jersey", "Europe/Kaliningrad", "Europe/Kiev",
		"Europe/Kirov", "Europe/Kyiv", "Europe/Lisbon", "Europe/Ljubljana", "Europe/London",
		"Europe/Luxembourg", "Europe/Madrid", "Europe/Malta", "Europe/Mariehamn", "Europe/Minsk",
		"Europe/Monaco", "Europe/Moscow", "Europe/Nicosia", "Europe/Oslo", "Europe/Paris",
		"Europe/Podgorica", "Europe/Prague", "Europe/Riga", "Europe/Rome", "Europe/Samara",
		"Europe/San_Marino", "Europe/Sarajevo", "Europe/Saratov", "Europe/Simferopol", "Europe/Skopje",
		"Europe/Sofia", "Europe/Stockholm", "Europe/Tallinn", "Europe/Tirane", "Europe/Tiraspol",
		"Europe/Ulyanovsk", "Europe/Uzhgorod", "Europe/Vaduz", "Europe/Vatican", "Europe/Vienna",
		"Europe/Vilnius", "Europe/Volgograd", "Europe/Warsaw", "Europe/Zagreb", "Europe/Zaporozhye",
		"Europe/Zurich", "GB", "GB-Eire", "GMT", "GMT+0", "GMT-0", "GMT0", "Greenwich", "HST",
		"Hongkong", "Iceland", "Indian/Antananarivo", "Indian/Chagos", "Indian/Christmas",
		"Indian/Cocos", "Indian/Comoro", "Indian/Kerguelen", "Indian/Mahe", "Indian/Maldives",
		"Indian/Mauritius", "Indian/Mayotte", "Indian/Reunion", "Iran", "Israel", "Jamaica", "Japan",
		"Kwajalein", "Libya", "MET", "MST", "MST7MDT", "Mexico/BajaNorte", "Mexico/BajaSur",
		"Mexico/General", "NZ", "NZ-CHAT", "Navajo", "PRC", "PST8PDT", "Pacific/Apia",
		"Pacific/Auckland", "Pacific/Bougainville", "Pacific/Chatham", "Pacific/Chuuk", "Pacific/Easter",
		"Pacific/Efate", "Pacific/Enderbury", "Pacific/Fakaofo", "Pacific/Fiji", "Pacific/Funafuti",
		"Pacific/Galapagos", "Pacific/Gambier", "Pacific/Guadalcanal", "Pacific/Guam",
		"Pacific/Honolulu", "Pacific/Johnston", "Pacific/Kanton", "Pacific/Kiritimati", "Pacific/Kosrae",
		"Pacific/Kwajalein", "Pacific/Majuro", "Pacific/Marquesas", "Pacific/Midway", "Pacific/Nauru",
		"Pacific/Niue", "Pacific/Norfolk", "Pacific/Noumea", "Pacific/Pago_Pago", "Pacific/Palau",
		"Pacific/Pitcairn", "Pacific/Pohnpei", "Pacific/Ponape", "Pacific/Port_Moresby",
		"Pacific/Rarotonga", "Pacific/Saipan", "Pacific/Samoa", "Pacific/Tahiti", "Pacific/Tarawa",
		"Pacific/Tongatapu", "Pacific/Truk", "Pacific/Wake", "Pacific/Wallis", "Pacific/Yap", "Poland",
		"Portugal", "ROC", "ROK", "Singapore", "Turkey", "UCT", "US/Alaska", "US/Aleutian", "US/Arizona",
		"US/Central", "US/East-Indiana", "US/Eastern", "US/Hawaii", "US/Indiana-Starke", "US/Michigan",
		"US/Mountain", "US/Pacific", "US/Samoa", "UTC", "Universal", "W-SU", "WET", "Zulu":
		return true
	}

	return false
}

// StockCode is a stock code in the documented SKU shape.
type StockCode struct {
	value string
	set   bool
}

// NewStockCode validates raw and returns the StockCode it describes.
func NewStockCode(raw string) (StockCode, error) {
	var stockCode StockCode // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if !stockCodePattern.MatchString(value) {
		failures.Add("stockCode", "regex", "must match the pattern ^[A-Z]{3}-[0-9]{4}$")
	}

	err := failures.Err()
	if err != nil {
		return stockCode, err
	}

	return StockCode{value: value, set: true}, nil
}

// String returns the validated value.
func (stockCode StockCode) String() string { return stockCode.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (stockCode StockCode) IsZero() bool { return !stockCode.set }

// Equal reports whether both hold the same value.
func (stockCode StockCode) Equal(other StockCode) bool { return stockCode == other }

// MarshalText implements encoding.TextMarshaler; the zero StockCode has no text form.
func (stockCode StockCode) MarshalText() ([]byte, error) {
	if stockCode.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero StockCode: %w", errors.ErrUnsupported)
	}

	return []byte(stockCode.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (stockCode *StockCode) UnmarshalText(data []byte) error {
	parsed, err := NewStockCode(string(data))
	if err != nil {
		return err
	}

	*stockCode = parsed

	return nil
}

// Currency is one of the currencies the restaurant takes.
type Currency struct {
	value string
	set   bool
}

// NewCurrency validates raw and returns the Currency it describes.
func NewCurrency(raw string) (Currency, error) {
	var currency Currency // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if value != "eur" && value != "usd" && value != "gbp" {
		failures.Add("currency", "oneof", "must be one of: eur,usd,gbp")
	}

	err := failures.Err()
	if err != nil {
		return currency, err
	}

	return Currency{value: value, set: true}, nil
}

// String returns the validated value.
func (currency Currency) String() string { return currency.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (currency Currency) IsZero() bool { return !currency.set }

// Equal reports whether both hold the same value.
func (currency Currency) Equal(other Currency) bool { return currency == other }

// MarshalText implements encoding.TextMarshaler; the zero Currency has no text form.
func (currency Currency) MarshalText() ([]byte, error) {
	if currency.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero Currency: %w", errors.ErrUnsupported)
	}

	return []byte(currency.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (currency *Currency) UnmarshalText(data []byte) error {
	parsed, err := NewCurrency(string(data))
	if err != nil {
		return err
	}

	*currency = parsed

	return nil
}

// LetterName is a name written in letters only.
type LetterName struct {
	value string
	set   bool
}

// NewLetterName validates raw and returns the LetterName it describes.
func NewLetterName(raw string) (LetterName, error) {
	var letterName LetterName // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if strings.IndexFunc(value, func(character rune) bool {
		return !unicode.IsLetter(character)
	}) >= 0 {
		failures.Add("letterName", "alpha", "must contain letters only")
	}

	err := failures.Err()
	if err != nil {
		return letterName, err
	}

	return LetterName{value: value, set: true}, nil
}

// String returns the validated value.
func (letterName LetterName) String() string { return letterName.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (letterName LetterName) IsZero() bool { return !letterName.set }

// Equal reports whether both hold the same value.
func (letterName LetterName) Equal(other LetterName) bool { return letterName == other }

// MarshalText implements encoding.TextMarshaler; the zero LetterName has no text form.
func (letterName LetterName) MarshalText() ([]byte, error) {
	if letterName.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero LetterName: %w", errors.ErrUnsupported)
	}

	return []byte(letterName.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (letterName *LetterName) UnmarshalText(data []byte) error {
	parsed, err := NewLetterName(string(data))
	if err != nil {
		return err
	}

	*letterName = parsed

	return nil
}

// Handle is a short code of letters and digits.
type Handle struct {
	value string
	set   bool
}

// NewHandle validates raw and returns the Handle it describes.
func NewHandle(raw string) (Handle, error) {
	var handle Handle // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if strings.IndexFunc(value, func(character rune) bool {
		return !unicode.IsLetter(character) && !unicode.IsDigit(character)
	}) >= 0 {
		failures.Add("handle", "alphanum", "must contain letters and digits only")
	}

	err := failures.Err()
	if err != nil {
		return handle, err
	}

	return Handle{value: value, set: true}, nil
}

// String returns the validated value.
func (handle Handle) String() string { return handle.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (handle Handle) IsZero() bool { return !handle.set }

// Equal reports whether both hold the same value.
func (handle Handle) Equal(other Handle) bool { return handle == other }

// MarshalText implements encoding.TextMarshaler; the zero Handle has no text form.
func (handle Handle) MarshalText() ([]byte, error) {
	if handle.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero Handle: %w", errors.ErrUnsupported)
	}

	return []byte(handle.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (handle *Handle) UnmarshalText(data []byte) error {
	parsed, err := NewHandle(string(data))
	if err != nil {
		return err
	}

	*handle = parsed

	return nil
}

// PhoneDigits is a phone number written as digits only.
type PhoneDigits struct {
	value string
	set   bool
}

// NewPhoneDigits validates raw and returns the PhoneDigits it describes.
func NewPhoneDigits(raw string) (PhoneDigits, error) {
	var phoneDigits PhoneDigits // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if strings.IndexFunc(value, func(character rune) bool {
		return character < '0' || character > '9'
	}) >= 0 {
		failures.Add("phoneDigits", "numeric", "must contain digits only")
	}

	err := failures.Err()
	if err != nil {
		return phoneDigits, err
	}

	return PhoneDigits{value: value, set: true}, nil
}

// String returns the validated value.
func (phoneDigits PhoneDigits) String() string { return phoneDigits.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (phoneDigits PhoneDigits) IsZero() bool { return !phoneDigits.set }

// Equal reports whether both hold the same value.
func (phoneDigits PhoneDigits) Equal(other PhoneDigits) bool { return phoneDigits == other }

// MarshalText implements encoding.TextMarshaler; the zero PhoneDigits has no text form.
func (phoneDigits PhoneDigits) MarshalText() ([]byte, error) {
	if phoneDigits.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero PhoneDigits: %w", errors.ErrUnsupported)
	}

	return []byte(phoneDigits.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (phoneDigits *PhoneDigits) UnmarshalText(data []byte) error {
	parsed, err := NewPhoneDigits(string(data))
	if err != nil {
		return err
	}

	*phoneDigits = parsed

	return nil
}

// LegacyCode is a code an ASCII-only system has to read.
type LegacyCode struct {
	value string
	set   bool
}

// NewLegacyCode validates raw and returns the LegacyCode it describes.
func NewLegacyCode(raw string) (LegacyCode, error) {
	var legacyCode LegacyCode // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if strings.IndexFunc(value, func(character rune) bool {
		return character >= utf8.RuneSelf
	}) >= 0 {
		failures.Add("legacyCode", "ascii", "must contain ASCII characters only")
	}

	err := failures.Err()
	if err != nil {
		return legacyCode, err
	}

	return LegacyCode{value: value, set: true}, nil
}

// String returns the validated value.
func (legacyCode LegacyCode) String() string { return legacyCode.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (legacyCode LegacyCode) IsZero() bool { return !legacyCode.set }

// Equal reports whether both hold the same value.
func (legacyCode LegacyCode) Equal(other LegacyCode) bool { return legacyCode == other }

// MarshalText implements encoding.TextMarshaler; the zero LegacyCode has no text form.
func (legacyCode LegacyCode) MarshalText() ([]byte, error) {
	if legacyCode.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero LegacyCode: %w", errors.ErrUnsupported)
	}

	return []byte(legacyCode.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (legacyCode *LegacyCode) UnmarshalText(data []byte) error {
	parsed, err := NewLegacyCode(string(data))
	if err != nil {
		return err
	}

	*legacyCode = parsed

	return nil
}

// SingleLine is a line of text carrying no control characters.
type SingleLine struct {
	value string
	set   bool
}

// NewSingleLine validates raw and returns the SingleLine it describes.
func NewSingleLine(raw string) (SingleLine, error) {
	var singleLine SingleLine // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if strings.IndexFunc(value, func(character rune) bool {
		return !unicode.IsPrint(character)
	}) >= 0 {
		failures.Add("singleLine", "printable", "must not contain control characters")
	}

	err := failures.Err()
	if err != nil {
		return singleLine, err
	}

	return SingleLine{value: value, set: true}, nil
}

// String returns the validated value.
func (singleLine SingleLine) String() string { return singleLine.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (singleLine SingleLine) IsZero() bool { return !singleLine.set }

// Equal reports whether both hold the same value.
func (singleLine SingleLine) Equal(other SingleLine) bool { return singleLine == other }

// MarshalText implements encoding.TextMarshaler; the zero SingleLine has no text form.
func (singleLine SingleLine) MarshalText() ([]byte, error) {
	if singleLine.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero SingleLine: %w", errors.ErrUnsupported)
	}

	return []byte(singleLine.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (singleLine *SingleLine) UnmarshalText(data []byte) error {
	parsed, err := NewSingleLine(string(data))
	if err != nil {
		return err
	}

	*singleLine = parsed

	return nil
}

// Slug is a URL-safe token carrying no whitespace.
type Slug struct {
	value string
	set   bool
}

// NewSlug validates raw and returns the Slug it describes.
func NewSlug(raw string) (Slug, error) {
	var slug Slug // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if strings.IndexFunc(value, unicode.IsSpace) >= 0 {
		failures.Add("slug", "nospace", "must not contain spaces")
	}

	err := failures.Err()
	if err != nil {
		return slug, err
	}

	return Slug{value: value, set: true}, nil
}

// String returns the validated value.
func (slug Slug) String() string { return slug.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (slug Slug) IsZero() bool { return !slug.set }

// Equal reports whether both hold the same value.
func (slug Slug) Equal(other Slug) bool { return slug == other }

// MarshalText implements encoding.TextMarshaler; the zero Slug has no text form.
func (slug Slug) MarshalText() ([]byte, error) {
	if slug.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero Slug: %w", errors.ErrUnsupported)
	}

	return []byte(slug.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (slug *Slug) UnmarshalText(data []byte) error {
	parsed, err := NewSlug(string(data))
	if err != nil {
		return err
	}

	*slug = parsed

	return nil
}

// ProductCode is a code inside the SKU namespace.
type ProductCode struct {
	value string
	set   bool
}

// NewProductCode validates raw and returns the ProductCode it describes.
func NewProductCode(raw string) (ProductCode, error) {
	var productCode ProductCode // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if !strings.HasPrefix(value, "SKU-") {
		failures.Add("productCode", "prefix", "must start with \"SKU-\"")
	}

	err := failures.Err()
	if err != nil {
		return productCode, err
	}

	return ProductCode{value: value, set: true}, nil
}

// String returns the validated value.
func (productCode ProductCode) String() string { return productCode.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (productCode ProductCode) IsZero() bool { return !productCode.set }

// Equal reports whether both hold the same value.
func (productCode ProductCode) Equal(other ProductCode) bool { return productCode == other }

// MarshalText implements encoding.TextMarshaler; the zero ProductCode has no text form.
func (productCode ProductCode) MarshalText() ([]byte, error) {
	if productCode.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero ProductCode: %w", errors.ErrUnsupported)
	}

	return []byte(productCode.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (productCode *ProductCode) UnmarshalText(data []byte) error {
	parsed, err := NewProductCode(string(data))
	if err != nil {
		return err
	}

	*productCode = parsed

	return nil
}

// DocumentFile is the name of a PDF document.
type DocumentFile struct {
	value string
	set   bool
}

// NewDocumentFile validates raw and returns the DocumentFile it describes.
func NewDocumentFile(raw string) (DocumentFile, error) {
	var documentFile DocumentFile // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if !strings.HasSuffix(value, ".pdf") {
		failures.Add("documentFile", "suffix", "must end with \".pdf\"")
	}

	err := failures.Err()
	if err != nil {
		return documentFile, err
	}

	return DocumentFile{value: value, set: true}, nil
}

// String returns the validated value.
func (documentFile DocumentFile) String() string { return documentFile.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (documentFile DocumentFile) IsZero() bool { return !documentFile.set }

// Equal reports whether both hold the same value.
func (documentFile DocumentFile) Equal(other DocumentFile) bool { return documentFile == other }

// MarshalText implements encoding.TextMarshaler; the zero DocumentFile has no text form.
func (documentFile DocumentFile) MarshalText() ([]byte, error) {
	if documentFile.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero DocumentFile: %w", errors.ErrUnsupported)
	}

	return []byte(documentFile.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (documentFile *DocumentFile) UnmarshalText(data []byte) error {
	parsed, err := NewDocumentFile(string(data))
	if err != nil {
		return err
	}

	*documentFile = parsed

	return nil
}

// ResourcePath is a path carrying a separator.
type ResourcePath struct {
	value string
	set   bool
}

// NewResourcePath validates raw and returns the ResourcePath it describes.
func NewResourcePath(raw string) (ResourcePath, error) {
	var resourcePath ResourcePath // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if !strings.Contains(value, "/") {
		failures.Add("resourcePath", "contains", "must contain \"/\"")
	}

	err := failures.Err()
	if err != nil {
		return resourcePath, err
	}

	return ResourcePath{value: value, set: true}, nil
}

// String returns the validated value.
func (resourcePath ResourcePath) String() string { return resourcePath.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (resourcePath ResourcePath) IsZero() bool { return !resourcePath.set }

// Equal reports whether both hold the same value.
func (resourcePath ResourcePath) Equal(other ResourcePath) bool { return resourcePath == other }

// MarshalText implements encoding.TextMarshaler; the zero ResourcePath has no text form.
func (resourcePath ResourcePath) MarshalText() ([]byte, error) {
	if resourcePath.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero ResourcePath: %w", errors.ErrUnsupported)
	}

	return []byte(resourcePath.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (resourcePath *ResourcePath) UnmarshalText(data []byte) error {
	parsed, err := NewResourcePath(string(data))
	if err != nil {
		return err
	}

	*resourcePath = parsed

	return nil
}

// FlatName is a name carrying no separator.
type FlatName struct {
	value string
	set   bool
}

// NewFlatName validates raw and returns the FlatName it describes.
func NewFlatName(raw string) (FlatName, error) {
	var flatName FlatName // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if strings.Contains(value, "/") {
		failures.Add("flatName", "excludes", "must not contain \"/\"")
	}

	err := failures.Err()
	if err != nil {
		return flatName, err
	}

	return FlatName{value: value, set: true}, nil
}

// String returns the validated value.
func (flatName FlatName) String() string { return flatName.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (flatName FlatName) IsZero() bool { return !flatName.set }

// Equal reports whether both hold the same value.
func (flatName FlatName) Equal(other FlatName) bool { return flatName == other }

// MarshalText implements encoding.TextMarshaler; the zero FlatName has no text form.
func (flatName FlatName) MarshalText() ([]byte, error) {
	if flatName.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero FlatName: %w", errors.ErrUnsupported)
	}

	return []byte(flatName.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (flatName *FlatName) UnmarshalText(data []byte) error {
	parsed, err := NewFlatName(string(data))
	if err != nil {
		return err
	}

	*flatName = parsed

	return nil
}

// Covers is the number of guests seated at a tab, at least one.
type Covers struct {
	value int64
	set   bool
}

// NewCovers validates raw and returns the Covers it describes.
func NewCovers(raw int64) (Covers, error) {
	var covers Covers // stays zero unless every rule passes
	var failures validation.Validation

	const minimumParameter = 1

	value := raw
	if value < minimumParameter {
		failures.Add("covers", "min", "must be at least 1")
	}

	err := failures.Err()
	if err != nil {
		return covers, err
	}

	return Covers{value: value, set: true}, nil
}

// NewCoversFromString reads a base-10 whole number and validates it.
func NewCoversFromString(raw string) (Covers, error) {
	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var failures validation.Validation
		failures.Add("covers", "int", "must be a whole number")

		return Covers{}, failures.Err()
	}

	return NewCovers(value)
}

// Int64 returns the validated value.
func (covers Covers) Int64() int64 { return covers.value }

// String returns the base-10 representation.
func (covers Covers) String() string { return strconv.FormatInt(covers.value, 10) }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (covers Covers) IsZero() bool { return !covers.set }

// Equal reports whether both hold the same value.
func (covers Covers) Equal(other Covers) bool { return covers == other }

// MarshalText implements encoding.TextMarshaler; the zero Covers has no text form.
func (covers Covers) MarshalText() ([]byte, error) {
	if covers.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero Covers: %w", errors.ErrUnsupported)
	}

	return []byte(covers.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (covers *Covers) UnmarshalText(data []byte) error {
	parsed, err := NewCoversFromString(string(data))
	if err != nil {
		return err
	}

	*covers = parsed

	return nil
}

// Seats is the number of seats in the room, at most two hundred.
type Seats struct {
	value int64
	set   bool
}

// NewSeats validates raw and returns the Seats it describes.
func NewSeats(raw int64) (Seats, error) {
	var seats Seats // stays zero unless every rule passes
	var failures validation.Validation

	const maximumParameter = 200

	value := raw
	if value > maximumParameter {
		failures.Add("seats", "max", "must be at most 200")
	}

	err := failures.Err()
	if err != nil {
		return seats, err
	}

	return Seats{value: value, set: true}, nil
}

// NewSeatsFromString reads a base-10 whole number and validates it.
func NewSeatsFromString(raw string) (Seats, error) {
	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var failures validation.Validation
		failures.Add("seats", "int", "must be a whole number")

		return Seats{}, failures.Err()
	}

	return NewSeats(value)
}

// Int64 returns the validated value.
func (seats Seats) Int64() int64 { return seats.value }

// String returns the base-10 representation.
func (seats Seats) String() string { return strconv.FormatInt(seats.value, 10) }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (seats Seats) IsZero() bool { return !seats.set }

// Equal reports whether both hold the same value.
func (seats Seats) Equal(other Seats) bool { return seats == other }

// MarshalText implements encoding.TextMarshaler; the zero Seats has no text form.
func (seats Seats) MarshalText() ([]byte, error) {
	if seats.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero Seats: %w", errors.ErrUnsupported)
	}

	return []byte(seats.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (seats *Seats) UnmarshalText(data []byte) error {
	parsed, err := NewSeatsFromString(string(data))
	if err != nil {
		return err
	}

	*seats = parsed

	return nil
}

// CourseCount is one of the menu sizes the kitchen serves.
type CourseCount struct {
	value int64
	set   bool
}

// NewCourseCount validates raw and returns the CourseCount it describes.
func NewCourseCount(raw int64) (CourseCount, error) {
	var courseCount CourseCount // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if !slices.Contains([]int64{1, 2, 4}, value) {
		failures.Add("courseCount", "oneof", "must be one of: 1,2,4")
	}

	err := failures.Err()
	if err != nil {
		return courseCount, err
	}

	return CourseCount{value: value, set: true}, nil
}

// NewCourseCountFromString reads a base-10 whole number and validates it.
func NewCourseCountFromString(raw string) (CourseCount, error) {
	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var failures validation.Validation
		failures.Add("courseCount", "int", "must be a whole number")

		return CourseCount{}, failures.Err()
	}

	return NewCourseCount(value)
}

// Int64 returns the validated value.
func (courseCount CourseCount) Int64() int64 { return courseCount.value }

// String returns the base-10 representation.
func (courseCount CourseCount) String() string { return strconv.FormatInt(courseCount.value, 10) }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (courseCount CourseCount) IsZero() bool { return !courseCount.set }

// Equal reports whether both hold the same value.
func (courseCount CourseCount) Equal(other CourseCount) bool { return courseCount == other }

// MarshalText implements encoding.TextMarshaler; the zero CourseCount has no text form.
func (courseCount CourseCount) MarshalText() ([]byte, error) {
	if courseCount.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero CourseCount: %w", errors.ErrUnsupported)
	}

	return []byte(courseCount.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (courseCount *CourseCount) UnmarshalText(data []byte) error {
	parsed, err := NewCourseCountFromString(string(data))
	if err != nil {
		return err
	}

	*courseCount = parsed

	return nil
}

// Portions is a count of portions, which is always at least one.
type Portions struct {
	value int64
	set   bool
}

// NewPortions validates raw and returns the Portions it describes.
func NewPortions(raw int64) (Portions, error) {
	var portions Portions // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if value <= 0 {
		failures.Add("portions", "positive", "must be greater than zero")
	}

	err := failures.Err()
	if err != nil {
		return portions, err
	}

	return Portions{value: value, set: true}, nil
}

// NewPortionsFromString reads a base-10 whole number and validates it.
func NewPortionsFromString(raw string) (Portions, error) {
	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var failures validation.Validation
		failures.Add("portions", "int", "must be a whole number")

		return Portions{}, failures.Err()
	}

	return NewPortions(value)
}

// Int64 returns the validated value.
func (portions Portions) Int64() int64 { return portions.value }

// String returns the base-10 representation.
func (portions Portions) String() string { return strconv.FormatInt(portions.value, 10) }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (portions Portions) IsZero() bool { return !portions.set }

// Equal reports whether both hold the same value.
func (portions Portions) Equal(other Portions) bool { return portions == other }

// MarshalText implements encoding.TextMarshaler; the zero Portions has no text form.
func (portions Portions) MarshalText() ([]byte, error) {
	if portions.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero Portions: %w", errors.ErrUnsupported)
	}

	return []byte(portions.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (portions *Portions) UnmarshalText(data []byte) error {
	parsed, err := NewPortionsFromString(string(data))
	if err != nil {
		return err
	}

	*portions = parsed

	return nil
}

// StockLevel is a stock level, which may be nothing but never less.
type StockLevel struct {
	value int64
	set   bool
}

// NewStockLevel validates raw and returns the StockLevel it describes.
func NewStockLevel(raw int64) (StockLevel, error) {
	var stockLevel StockLevel // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if value < 0 {
		failures.Add("stockLevel", "nonneg", "must not be negative")
	}

	err := failures.Err()
	if err != nil {
		return stockLevel, err
	}

	return StockLevel{value: value, set: true}, nil
}

// NewStockLevelFromString reads a base-10 whole number and validates it.
func NewStockLevelFromString(raw string) (StockLevel, error) {
	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var failures validation.Validation
		failures.Add("stockLevel", "int", "must be a whole number")

		return StockLevel{}, failures.Err()
	}

	return NewStockLevel(value)
}

// Int64 returns the validated value.
func (stockLevel StockLevel) Int64() int64 { return stockLevel.value }

// String returns the base-10 representation.
func (stockLevel StockLevel) String() string { return strconv.FormatInt(stockLevel.value, 10) }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (stockLevel StockLevel) IsZero() bool { return !stockLevel.set }

// Equal reports whether both hold the same value.
func (stockLevel StockLevel) Equal(other StockLevel) bool { return stockLevel == other }

// MarshalText implements encoding.TextMarshaler; the zero StockLevel has no text form.
func (stockLevel StockLevel) MarshalText() ([]byte, error) {
	if stockLevel.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero StockLevel: %w", errors.ErrUnsupported)
	}

	return []byte(stockLevel.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (stockLevel *StockLevel) UnmarshalText(data []byte) error {
	parsed, err := NewStockLevelFromString(string(data))
	if err != nil {
		return err
	}

	*stockLevel = parsed

	return nil
}

// SlotMinutes is a booking length measured in whole quarter hours.
type SlotMinutes struct {
	value int64
	set   bool
}

// NewSlotMinutes validates raw and returns the SlotMinutes it describes.
func NewSlotMinutes(raw int64) (SlotMinutes, error) {
	var slotMinutes SlotMinutes // stays zero unless every rule passes
	var failures validation.Validation

	const multipleofParameter = 15

	value := raw
	if value%multipleofParameter != 0 {
		failures.Add("slotMinutes", "multipleof", "must be a multiple of 15")
	}

	err := failures.Err()
	if err != nil {
		return slotMinutes, err
	}

	return SlotMinutes{value: value, set: true}, nil
}

// NewSlotMinutesFromString reads a base-10 whole number and validates it.
func NewSlotMinutesFromString(raw string) (SlotMinutes, error) {
	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var failures validation.Validation
		failures.Add("slotMinutes", "int", "must be a whole number")

		return SlotMinutes{}, failures.Err()
	}

	return NewSlotMinutes(value)
}

// Int64 returns the validated value.
func (slotMinutes SlotMinutes) Int64() int64 { return slotMinutes.value }

// String returns the base-10 representation.
func (slotMinutes SlotMinutes) String() string { return strconv.FormatInt(slotMinutes.value, 10) }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (slotMinutes SlotMinutes) IsZero() bool { return !slotMinutes.set }

// Equal reports whether both hold the same value.
func (slotMinutes SlotMinutes) Equal(other SlotMinutes) bool { return slotMinutes == other }

// MarshalText implements encoding.TextMarshaler; the zero SlotMinutes has no text form.
func (slotMinutes SlotMinutes) MarshalText() ([]byte, error) {
	if slotMinutes.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero SlotMinutes: %w", errors.ErrUnsupported)
	}

	return []byte(slotMinutes.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (slotMinutes *SlotMinutes) UnmarshalText(data []byte) error {
	parsed, err := NewSlotMinutesFromString(string(data))
	if err != nil {
		return err
	}

	*slotMinutes = parsed

	return nil
}

// MinRate is a rate that may not fall below nothing.
type MinRate struct {
	value decimal.Decimal
	set   bool
}

// NewMinRate validates raw and returns the MinRate it describes.
func NewMinRate(raw decimal.Decimal) (MinRate, error) {
	var minRate MinRate // stays zero unless every rule passes
	var failures validation.Validation

	const minimumParameter = 0

	value := raw
	if value.Cmp(decimal.MustNew(minimumParameter, 0)) < 0 {
		failures.Add("minRate", "min", "must be at least 0")
	}

	err := failures.Err()
	if err != nil {
		return minRate, err
	}

	return MinRate{value: value, set: true}, nil
}

// NewMinRateFromString reads an exact decimal number and validates it.
func NewMinRateFromString(raw string) (MinRate, error) {
	value, err := decimal.Parse(raw)
	if err != nil {
		var failures validation.Validation
		failures.Add("minRate", "decimal", "must be an exact decimal number")

		return MinRate{}, failures.Err()
	}

	return NewMinRate(value)
}

// Decimal returns the validated value.
func (minRate MinRate) Decimal() decimal.Decimal { return minRate.value }

// String returns the canonical text, which keeps the scale: 1.50 stays "1.50".
func (minRate MinRate) String() string { return minRate.value.String() }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (minRate MinRate) IsZero() bool { return !minRate.set }

// Equal reports whether both hold the same number, so 1.5 equals 1.50.
func (minRate MinRate) Equal(other MinRate) bool {
	return minRate.set == other.set && minRate.value.Cmp(other.value) == 0
}

// MarshalText implements encoding.TextMarshaler; the zero MinRate has no text form.
func (minRate MinRate) MarshalText() ([]byte, error) {
	if minRate.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero MinRate: %w", errors.ErrUnsupported)
	}

	return []byte(minRate.value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (minRate *MinRate) UnmarshalText(data []byte) error {
	parsed, err := NewMinRateFromString(string(data))
	if err != nil {
		return err
	}

	*minRate = parsed

	return nil
}

// MaxRate is a share of a bill, which cannot exceed the whole.
type MaxRate struct {
	value decimal.Decimal
	set   bool
}

// NewMaxRate validates raw and returns the MaxRate it describes.
func NewMaxRate(raw decimal.Decimal) (MaxRate, error) {
	var maxRate MaxRate // stays zero unless every rule passes
	var failures validation.Validation

	const maximumParameter = 1

	value := raw
	if value.Cmp(decimal.MustNew(maximumParameter, 0)) > 0 {
		failures.Add("maxRate", "max", "must be at most 1")
	}

	err := failures.Err()
	if err != nil {
		return maxRate, err
	}

	return MaxRate{value: value, set: true}, nil
}

// NewMaxRateFromString reads an exact decimal number and validates it.
func NewMaxRateFromString(raw string) (MaxRate, error) {
	value, err := decimal.Parse(raw)
	if err != nil {
		var failures validation.Validation
		failures.Add("maxRate", "decimal", "must be an exact decimal number")

		return MaxRate{}, failures.Err()
	}

	return NewMaxRate(value)
}

// Decimal returns the validated value.
func (maxRate MaxRate) Decimal() decimal.Decimal { return maxRate.value }

// String returns the canonical text, which keeps the scale: 1.50 stays "1.50".
func (maxRate MaxRate) String() string { return maxRate.value.String() }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (maxRate MaxRate) IsZero() bool { return !maxRate.set }

// Equal reports whether both hold the same number, so 1.5 equals 1.50.
func (maxRate MaxRate) Equal(other MaxRate) bool {
	return maxRate.set == other.set && maxRate.value.Cmp(other.value) == 0
}

// MarshalText implements encoding.TextMarshaler; the zero MaxRate has no text form.
func (maxRate MaxRate) MarshalText() ([]byte, error) {
	if maxRate.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero MaxRate: %w", errors.ErrUnsupported)
	}

	return []byte(maxRate.value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (maxRate *MaxRate) UnmarshalText(data []byte) error {
	parsed, err := NewMaxRateFromString(string(data))
	if err != nil {
		return err
	}

	*maxRate = parsed

	return nil
}

// UnitWeight is a weight on a scale, which only means something above zero.
type UnitWeight struct {
	value decimal.Decimal
	set   bool
}

// NewUnitWeight validates raw and returns the UnitWeight it describes.
func NewUnitWeight(raw decimal.Decimal) (UnitWeight, error) {
	var unitWeight UnitWeight // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if value.Sign() <= 0 {
		failures.Add("unitWeight", "positive", "must be greater than zero")
	}

	err := failures.Err()
	if err != nil {
		return unitWeight, err
	}

	return UnitWeight{value: value, set: true}, nil
}

// NewUnitWeightFromString reads an exact decimal number and validates it.
func NewUnitWeightFromString(raw string) (UnitWeight, error) {
	value, err := decimal.Parse(raw)
	if err != nil {
		var failures validation.Validation
		failures.Add("unitWeight", "decimal", "must be an exact decimal number")

		return UnitWeight{}, failures.Err()
	}

	return NewUnitWeight(value)
}

// Decimal returns the validated value.
func (unitWeight UnitWeight) Decimal() decimal.Decimal { return unitWeight.value }

// String returns the canonical text, which keeps the scale: 1.50 stays "1.50".
func (unitWeight UnitWeight) String() string { return unitWeight.value.String() }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (unitWeight UnitWeight) IsZero() bool { return !unitWeight.set }

// Equal reports whether both hold the same number, so 1.5 equals 1.50.
func (unitWeight UnitWeight) Equal(other UnitWeight) bool {
	return unitWeight.set == other.set && unitWeight.value.Cmp(other.value) == 0
}

// MarshalText implements encoding.TextMarshaler; the zero UnitWeight has no text form.
func (unitWeight UnitWeight) MarshalText() ([]byte, error) {
	if unitWeight.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero UnitWeight: %w", errors.ErrUnsupported)
	}

	return []byte(unitWeight.value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (unitWeight *UnitWeight) UnmarshalText(data []byte) error {
	parsed, err := NewUnitWeightFromString(string(data))
	if err != nil {
		return err
	}

	*unitWeight = parsed

	return nil
}

// ShelfWeight is a stock weight, which may be nothing but never less.
type ShelfWeight struct {
	value decimal.Decimal
	set   bool
}

// NewShelfWeight validates raw and returns the ShelfWeight it describes.
func NewShelfWeight(raw decimal.Decimal) (ShelfWeight, error) {
	var shelfWeight ShelfWeight // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if value.Sign() < 0 {
		failures.Add("shelfWeight", "nonneg", "must not be negative")
	}

	err := failures.Err()
	if err != nil {
		return shelfWeight, err
	}

	return ShelfWeight{value: value, set: true}, nil
}

// NewShelfWeightFromString reads an exact decimal number and validates it.
func NewShelfWeightFromString(raw string) (ShelfWeight, error) {
	value, err := decimal.Parse(raw)
	if err != nil {
		var failures validation.Validation
		failures.Add("shelfWeight", "decimal", "must be an exact decimal number")

		return ShelfWeight{}, failures.Err()
	}

	return NewShelfWeight(value)
}

// Decimal returns the validated value.
func (shelfWeight ShelfWeight) Decimal() decimal.Decimal { return shelfWeight.value }

// String returns the canonical text, which keeps the scale: 1.50 stays "1.50".
func (shelfWeight ShelfWeight) String() string { return shelfWeight.value.String() }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (shelfWeight ShelfWeight) IsZero() bool { return !shelfWeight.set }

// Equal reports whether both hold the same number, so 1.5 equals 1.50.
func (shelfWeight ShelfWeight) Equal(other ShelfWeight) bool {
	return shelfWeight.set == other.set && shelfWeight.value.Cmp(other.value) == 0
}

// MarshalText implements encoding.TextMarshaler; the zero ShelfWeight has no text form.
func (shelfWeight ShelfWeight) MarshalText() ([]byte, error) {
	if shelfWeight.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero ShelfWeight: %w", errors.ErrUnsupported)
	}

	return []byte(shelfWeight.value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (shelfWeight *ShelfWeight) UnmarshalText(data []byte) error {
	parsed, err := NewShelfWeightFromString(string(data))
	if err != nil {
		return err
	}

	*shelfWeight = parsed

	return nil
}

// TaxRate is a rate stored in a numeric column of scale four.
type TaxRate struct {
	value decimal.Decimal
	set   bool
}

// NewTaxRate validates raw and returns the TaxRate it describes.
func NewTaxRate(raw decimal.Decimal) (TaxRate, error) {
	var taxRate TaxRate // stays zero unless every rule passes
	var failures validation.Validation

	const scaleParameter = 4

	value := raw
	if value.Scale() > scaleParameter {
		failures.Add("taxRate", "scale", "must have at most 4 decimal places")
	}

	err := failures.Err()
	if err != nil {
		return taxRate, err
	}

	return TaxRate{value: value, set: true}, nil
}

// NewTaxRateFromString reads an exact decimal number and validates it.
func NewTaxRateFromString(raw string) (TaxRate, error) {
	value, err := decimal.Parse(raw)
	if err != nil {
		var failures validation.Validation
		failures.Add("taxRate", "decimal", "must be an exact decimal number")

		return TaxRate{}, failures.Err()
	}

	return NewTaxRate(value)
}

// Decimal returns the validated value.
func (taxRate TaxRate) Decimal() decimal.Decimal { return taxRate.value }

// String returns the canonical text, which keeps the scale: 1.50 stays "1.50".
func (taxRate TaxRate) String() string { return taxRate.value.String() }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (taxRate TaxRate) IsZero() bool { return !taxRate.set }

// Equal reports whether both hold the same number, so 1.5 equals 1.50.
func (taxRate TaxRate) Equal(other TaxRate) bool {
	return taxRate.set == other.set && taxRate.value.Cmp(other.value) == 0
}

// MarshalText implements encoding.TextMarshaler; the zero TaxRate has no text form.
func (taxRate TaxRate) MarshalText() ([]byte, error) {
	if taxRate.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero TaxRate: %w", errors.ErrUnsupported)
	}

	return []byte(taxRate.value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (taxRate *TaxRate) UnmarshalText(data []byte) error {
	parsed, err := NewTaxRateFromString(string(data))
	if err != nil {
		return err
	}

	*taxRate = parsed

	return nil
}

// PreciseWeight is a weight measured to the gram and no finer.
type PreciseWeight struct {
	value decimal.Decimal
	set   bool
}

// NewPreciseWeight validates raw and returns the PreciseWeight it describes.
func NewPreciseWeight(raw decimal.Decimal) (PreciseWeight, error) {
	var preciseWeight PreciseWeight // stays zero unless every rule passes
	var failures validation.Validation

	const scaleParameter = 3

	value := raw
	if value.Scale() > scaleParameter {
		failures.Add("preciseWeight", "scale", "must have at most 3 decimal places")
	}

	err := failures.Err()
	if err != nil {
		return preciseWeight, err
	}

	return PreciseWeight{value: value, set: true}, nil
}

// NewPreciseWeightFromString reads an exact decimal number and validates it.
func NewPreciseWeightFromString(raw string) (PreciseWeight, error) {
	value, err := decimal.Parse(raw)
	if err != nil {
		var failures validation.Validation
		failures.Add("preciseWeight", "decimal", "must be an exact decimal number")

		return PreciseWeight{}, failures.Err()
	}

	return NewPreciseWeight(value)
}

// Decimal returns the validated value.
func (preciseWeight PreciseWeight) Decimal() decimal.Decimal { return preciseWeight.value }

// String returns the canonical text, which keeps the scale: 1.50 stays "1.50".
func (preciseWeight PreciseWeight) String() string { return preciseWeight.value.String() }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (preciseWeight PreciseWeight) IsZero() bool { return !preciseWeight.set }

// Equal reports whether both hold the same number, so 1.5 equals 1.50.
func (preciseWeight PreciseWeight) Equal(other PreciseWeight) bool {
	return preciseWeight.set == other.set && preciseWeight.value.Cmp(other.value) == 0
}

// MarshalText implements encoding.TextMarshaler; the zero PreciseWeight has no text form.
func (preciseWeight PreciseWeight) MarshalText() ([]byte, error) {
	if preciseWeight.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero PreciseWeight: %w", errors.ErrUnsupported)
	}

	return []byte(preciseWeight.value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (preciseWeight *PreciseWeight) UnmarshalText(data []byte) error {
	parsed, err := NewPreciseWeightFromString(string(data))
	if err != nil {
		return err
	}

	*preciseWeight = parsed

	return nil
}

// Adjustment is a correction to a bill, which is pointless when it is zero.
type Adjustment struct {
	value decimal.Decimal
	set   bool
}

// NewAdjustment validates raw and returns the Adjustment it describes.
func NewAdjustment(raw decimal.Decimal) (Adjustment, error) {
	var adjustment Adjustment // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	if value.IsZero() {
		failures.Add("adjustment", "nonzero", "must not be zero")
	}

	err := failures.Err()
	if err != nil {
		return adjustment, err
	}

	return Adjustment{value: value, set: true}, nil
}

// NewAdjustmentFromString reads an exact decimal number and validates it.
func NewAdjustmentFromString(raw string) (Adjustment, error) {
	value, err := decimal.Parse(raw)
	if err != nil {
		var failures validation.Validation
		failures.Add("adjustment", "decimal", "must be an exact decimal number")

		return Adjustment{}, failures.Err()
	}

	return NewAdjustment(value)
}

// Decimal returns the validated value.
func (adjustment Adjustment) Decimal() decimal.Decimal { return adjustment.value }

// String returns the canonical text, which keeps the scale: 1.50 stays "1.50".
func (adjustment Adjustment) String() string { return adjustment.value.String() }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (adjustment Adjustment) IsZero() bool { return !adjustment.set }

// Equal reports whether both hold the same number, so 1.5 equals 1.50.
func (adjustment Adjustment) Equal(other Adjustment) bool {
	return adjustment.set == other.set && adjustment.value.Cmp(other.value) == 0
}

// MarshalText implements encoding.TextMarshaler; the zero Adjustment has no text form.
func (adjustment Adjustment) MarshalText() ([]byte, error) {
	if adjustment.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero Adjustment: %w", errors.ErrUnsupported)
	}

	return []byte(adjustment.value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (adjustment *Adjustment) UnmarshalText(data []byte) error {
	parsed, err := NewAdjustmentFromString(string(data))
	if err != nil {
		return err
	}

	*adjustment = parsed

	return nil
}

// LoweredCurrency is a currency code typed in any case.
type LoweredCurrency struct {
	value string
	set   bool
}

// NewLoweredCurrency validates raw and returns the LoweredCurrency it describes.
func NewLoweredCurrency(raw string) (LoweredCurrency, error) {
	var loweredCurrency LoweredCurrency // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.ToLower(value)
	if value != "eur" && value != "usd" && value != "gbp" {
		failures.Add("loweredCurrency", "oneof", "must be one of: eur,usd,gbp")
	}

	err := failures.Err()
	if err != nil {
		return loweredCurrency, err
	}

	return LoweredCurrency{value: value, set: true}, nil
}

// String returns the validated value.
func (loweredCurrency LoweredCurrency) String() string { return loweredCurrency.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (loweredCurrency LoweredCurrency) IsZero() bool { return !loweredCurrency.set }

// Equal reports whether both hold the same value.
func (loweredCurrency LoweredCurrency) Equal(other LoweredCurrency) bool {
	return loweredCurrency == other
}

// MarshalText implements encoding.TextMarshaler; the zero LoweredCurrency has no text form.
func (loweredCurrency LoweredCurrency) MarshalText() ([]byte, error) {
	if loweredCurrency.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero LoweredCurrency: %w", errors.ErrUnsupported)
	}

	return []byte(loweredCurrency.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (loweredCurrency *LoweredCurrency) UnmarshalText(data []byte) error {
	parsed, err := NewLoweredCurrency(string(data))
	if err != nil {
		return err
	}

	*loweredCurrency = parsed

	return nil
}

// ShoutedSku is a stock code typed in any case.
type ShoutedSku struct {
	value string
	set   bool
}

// NewShoutedSku validates raw and returns the ShoutedSku it describes.
func NewShoutedSku(raw string) (ShoutedSku, error) {
	var shoutedSku ShoutedSku // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.ToUpper(value)
	if !strings.HasPrefix(value, "SKU-") {
		failures.Add("shoutedSku", "prefix", "must start with \"SKU-\"")
	}

	err := failures.Err()
	if err != nil {
		return shoutedSku, err
	}

	return ShoutedSku{value: value, set: true}, nil
}

// String returns the validated value.
func (shoutedSku ShoutedSku) String() string { return shoutedSku.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (shoutedSku ShoutedSku) IsZero() bool { return !shoutedSku.set }

// Equal reports whether both hold the same value.
func (shoutedSku ShoutedSku) Equal(other ShoutedSku) bool { return shoutedSku == other }

// MarshalText implements encoding.TextMarshaler; the zero ShoutedSku has no text form.
func (shoutedSku ShoutedSku) MarshalText() ([]byte, error) {
	if shoutedSku.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero ShoutedSku: %w", errors.ErrUnsupported)
	}

	return []byte(shoutedSku.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (shoutedSku *ShoutedSku) UnmarshalText(data []byte) error {
	parsed, err := NewShoutedSku(string(data))
	if err != nil {
		return err
	}

	*shoutedSku = parsed

	return nil
}

// TrimmedSlug is a slug pasted with blanks around it.
type TrimmedSlug struct {
	value string
	set   bool
}

// NewTrimmedSlug validates raw and returns the TrimmedSlug it describes.
func NewTrimmedSlug(raw string) (TrimmedSlug, error) {
	var trimmedSlug TrimmedSlug // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.TrimSpace(value)
	if strings.IndexFunc(value, unicode.IsSpace) >= 0 {
		failures.Add("trimmedSlug", "nospace", "must not contain spaces")
	}

	err := failures.Err()
	if err != nil {
		return trimmedSlug, err
	}

	return TrimmedSlug{value: value, set: true}, nil
}

// String returns the validated value.
func (trimmedSlug TrimmedSlug) String() string { return trimmedSlug.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (trimmedSlug TrimmedSlug) IsZero() bool { return !trimmedSlug.set }

// Equal reports whether both hold the same value.
func (trimmedSlug TrimmedSlug) Equal(other TrimmedSlug) bool { return trimmedSlug == other }

// MarshalText implements encoding.TextMarshaler; the zero TrimmedSlug has no text form.
func (trimmedSlug TrimmedSlug) MarshalText() ([]byte, error) {
	if trimmedSlug.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero TrimmedSlug: %w", errors.ErrUnsupported)
	}

	return []byte(trimmedSlug.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (trimmedSlug *TrimmedSlug) UnmarshalText(data []byte) error {
	parsed, err := NewTrimmedSlug(string(data))
	if err != nil {
		return err
	}

	*trimmedSlug = parsed

	return nil
}

// SquishedLine is one line of text pasted with extra blanks.
type SquishedLine struct {
	value string
	set   bool
}

// NewSquishedLine validates raw and returns the SquishedLine it describes.
func NewSquishedLine(raw string) (SquishedLine, error) {
	var squishedLine SquishedLine // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.Join(strings.Fields(value), " ")
	if strings.IndexFunc(value, func(character rune) bool {
		return !unicode.IsPrint(character)
	}) >= 0 {
		failures.Add("squishedLine", "printable", "must not contain control characters")
	}

	err := failures.Err()
	if err != nil {
		return squishedLine, err
	}

	return SquishedLine{value: value, set: true}, nil
}

// String returns the validated value.
func (squishedLine SquishedLine) String() string { return squishedLine.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (squishedLine SquishedLine) IsZero() bool { return !squishedLine.set }

// Equal reports whether both hold the same value.
func (squishedLine SquishedLine) Equal(other SquishedLine) bool { return squishedLine == other }

// MarshalText implements encoding.TextMarshaler; the zero SquishedLine has no text form.
func (squishedLine SquishedLine) MarshalText() ([]byte, error) {
	if squishedLine.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero SquishedLine: %w", errors.ErrUnsupported)
	}

	return []byte(squishedLine.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (squishedLine *SquishedLine) UnmarshalText(data []byte) error {
	parsed, err := NewSquishedLine(string(data))
	if err != nil {
		return err
	}

	*squishedLine = parsed

	return nil
}

// LoweredFile is a file name typed in any case.
type LoweredFile struct {
	value string
	set   bool
}

// NewLoweredFile validates raw and returns the LoweredFile it describes.
func NewLoweredFile(raw string) (LoweredFile, error) {
	var loweredFile LoweredFile // stays zero unless every rule passes
	var failures validation.Validation

	value := raw
	value = strings.ToLower(value)
	if !strings.HasSuffix(value, ".pdf") {
		failures.Add("loweredFile", "suffix", "must end with \".pdf\"")
	}

	err := failures.Err()
	if err != nil {
		return loweredFile, err
	}

	return LoweredFile{value: value, set: true}, nil
}

// String returns the validated value.
func (loweredFile LoweredFile) String() string { return loweredFile.value }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (loweredFile LoweredFile) IsZero() bool { return !loweredFile.set }

// Equal reports whether both hold the same value.
func (loweredFile LoweredFile) Equal(other LoweredFile) bool { return loweredFile == other }

// MarshalText implements encoding.TextMarshaler; the zero LoweredFile has no text form.
func (loweredFile LoweredFile) MarshalText() ([]byte, error) {
	if loweredFile.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero LoweredFile: %w", errors.ErrUnsupported)
	}

	return []byte(loweredFile.value), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (loweredFile *LoweredFile) UnmarshalText(data []byte) error {
	parsed, err := NewLoweredFile(string(data))
	if err != nil {
		return err
	}

	*loweredFile = parsed

	return nil
}
