// Code generated by vogue. DO NOT EDIT.

package catalogue

import (
	"testing"

	"github.com/MathiasHilgert/vogue/voguetest"
)

// The strings below are shared by several rows of the tables in this file.
const (
	exampleTortilla              = "Tortilla"
	exampleRejectsTheEmptyString = "rejects the empty string"
	exampleRequired              = "required"
	exampleTortillaDePatatas     = "Tortilla de patatas"
	exampleWaiterExampleCom      = "waiter@example.com"
	exampleAlready               = "already"
	exampleEur                   = "eur"
	exampleEUR                   = "EUR"
	exampleMin                   = "min"
	exampleMax                   = "max"
	exampleLen                   = "len"
	exampleEmail                 = "email"
	exampleUrl                   = "url"
	exampleUuid                  = "uuid"
	exampleSku0042               = "sku-0042"
	exampleRegex                 = "regex"
	exampleOneof                 = "oneof"
	exampleNumeric               = "numeric"
	examplePrefix                = "prefix"
	exampleInt                   = "int"
	examplePositive              = "positive"
	exampleNonneg                = "nonneg"
	exampleDecimal               = "decimal"
	example15                    = "1.5"
)

// TestTrimmedName runs the value-object suite against the examples the directive
// and its rules declare.
func TestTrimmedName(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[TrimmedName, *TrimmedName, string]{
		Field:      "trimmedName",
		New:        NewTrimmedName,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, " "},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  exampleRejectsTheEmptyString,
				In:    "",
				Rules: []string{exampleRequired},
			},
		},
		Normalized: []voguetest.Normalization[string]{
			{
				Name: "the blanks around a pasted value are dropped",
				In:   "  Tortilla  ",
				Out:  exampleTortilla,
			},
			{
				Name: "tabs and newlines count as whitespace too",
				In:   "\tTortilla\n",
				Out:  exampleTortilla,
			},
			{
				Name: "an already clean value is left alone",
				In:   exampleTortilla,
				Out:  exampleTortilla,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestSquishedName runs the value-object suite against the examples the directive
// and its rules declare.
func TestSquishedName(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[SquishedName, *SquishedName, string]{
		Field:      "squishedName",
		New:        NewSquishedName,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, " "},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  exampleRejectsTheEmptyString,
				In:    "",
				Rules: []string{exampleRequired},
			},
		},
		Normalized: []voguetest.Normalization[string]{
			{
				Name: "a run of spaces becomes one",
				In:   "Tortilla   de  patatas",
				Out:  exampleTortillaDePatatas,
			},
			{
				Name: "the ends are trimmed as well",
				In:   "  Tortilla de patatas  ",
				Out:  exampleTortillaDePatatas,
			},
			{
				Name: "a tab and a newline become plain spaces",
				In:   "Tortilla\tde\npatatas",
				Out:  exampleTortillaDePatatas,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestLoweredName runs the value-object suite against the examples the directive
// and its rules declare.
func TestLoweredName(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[LoweredName, *LoweredName, string]{
		Field:      "loweredName",
		New:        NewLoweredName,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, " "},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  exampleRejectsTheEmptyString,
				In:    "",
				Rules: []string{exampleRequired},
			},
		},
		Normalized: []voguetest.Normalization[string]{
			{
				Name: "an address is folded to one canonical spelling",
				In:   "Waiter@Example.Com",
				Out:  exampleWaiterExampleCom,
			},
			{
				Name: "an accented capital folds like any other letter",
				In:   "ÁRBOL",
				Out:  "árbol",
			},
			{
				Name: "a value already in lower case is left alone",
				In:   exampleAlready,
				Out:  exampleAlready,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestUpperedName runs the value-object suite against the examples the directive
// and its rules declare.
func TestUpperedName(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[UpperedName, *UpperedName, string]{
		Field:      "upperedName",
		New:        NewUpperedName,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, " "},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  exampleRejectsTheEmptyString,
				In:    "",
				Rules: []string{exampleRequired},
			},
		},
		Normalized: []voguetest.Normalization[string]{
			{
				Name: "a currency code is shouted the way the standard writes it",
				In:   exampleEur,
				Out:  exampleEUR,
			},
			{
				Name: "digits and punctuation are left untouched",
				In:   "sku-12",
				Out:  "SKU-12",
			},
			{
				Name: "a value already in upper case is left alone",
				In:   exampleEUR,
				Out:  exampleEUR,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestTrimmedOnly runs the value-object suite against the examples the directive
// and its rules declare.
func TestTrimmedOnly(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[TrimmedOnly, *TrimmedOnly, string]{
		Field:      "trimmedOnly",
		New:        NewTrimmedOnly,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: nil,
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name: "the blanks around a pasted value are dropped",
				In:   "  Tortilla  ",
				Out:  exampleTortilla,
			},
			{
				Name: "tabs and newlines count as whitespace too",
				In:   "\tTortilla\n",
				Out:  exampleTortilla,
			},
			{
				Name: "an already clean value is left alone",
				In:   exampleTortilla,
				Out:  exampleTortilla,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestSquishedOnly runs the value-object suite against the examples the directive
// and its rules declare.
func TestSquishedOnly(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[SquishedOnly, *SquishedOnly, string]{
		Field:      "squishedOnly",
		New:        NewSquishedOnly,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: nil,
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name: "a run of spaces becomes one",
				In:   "Tortilla   de  patatas",
				Out:  exampleTortillaDePatatas,
			},
			{
				Name: "the ends are trimmed as well",
				In:   "  Tortilla de patatas  ",
				Out:  exampleTortillaDePatatas,
			},
			{
				Name: "a tab and a newline become plain spaces",
				In:   "Tortilla\tde\npatatas",
				Out:  exampleTortillaDePatatas,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestLoweredOnly runs the value-object suite against the examples the directive
// and its rules declare.
func TestLoweredOnly(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[LoweredOnly, *LoweredOnly, string]{
		Field:      "loweredOnly",
		New:        NewLoweredOnly,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: nil,
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name: "an address is folded to one canonical spelling",
				In:   "Waiter@Example.Com",
				Out:  exampleWaiterExampleCom,
			},
			{
				Name: "an accented capital folds like any other letter",
				In:   "ÁRBOL",
				Out:  "árbol",
			},
			{
				Name: "a value already in lower case is left alone",
				In:   exampleAlready,
				Out:  exampleAlready,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestUpperedOnly runs the value-object suite against the examples the directive
// and its rules declare.
func TestUpperedOnly(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[UpperedOnly, *UpperedOnly, string]{
		Field:      "upperedOnly",
		New:        NewUpperedOnly,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: nil,
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name: "a currency code is shouted the way the standard writes it",
				In:   exampleEur,
				Out:  exampleEUR,
			},
			{
				Name: "digits and punctuation are left untouched",
				In:   "sku-12",
				Out:  "SKU-12",
			},
			{
				Name: "a value already in upper case is left alone",
				In:   exampleEUR,
				Out:  exampleEUR,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestRequiredName runs the value-object suite against the examples the directive
// and its rules declare.
func TestRequiredName(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[RequiredName, *RequiredName, string]{
		Field:      "requiredName",
		New:        NewRequiredName,
		Get:        RequiredName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, " "},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  exampleRejectsTheEmptyString,
				In:    "",
				Rules: []string{exampleRequired},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestShortName runs the value-object suite against the examples the directive
// and its rules declare.
func TestShortName(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[ShortName, *ShortName, string]{
		Field:      "shortName",
		New:        NewShortName,
		Get:        ShortName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"a"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the empty string is shorter than one rune",
				In:    "",
				Rules: []string{exampleMin},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestLongerName runs the value-object suite against the examples the directive
// and its rules declare.
func TestLongerName(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[LongerName, *LongerName, string]{
		Field:      "longerName",
		New:        NewLongerName,
		Get:        LongerName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"añó"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects two runes fall short of three",
				In:    "ab",
				Rules: []string{exampleMin},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestBoundedName runs the value-object suite against the examples the directive
// and its rules declare.
func TestBoundedName(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[BoundedName, *BoundedName, string]{
		Field:      "boundedName",
		New:        NewBoundedName,
		Get:        BoundedName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"abcd", ""},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects one rune more than the bound holds",
				In:    "abcde",
				Rules: []string{exampleMax},
			},
			{
				Name:  "rejects five accented runes are five, not ten",
				In:    "añóra",
				Rules: []string{exampleMax},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestCurrencyCode runs the value-object suite against the examples the directive
// and its rules declare.
func TestCurrencyCode(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[CurrencyCode, *CurrencyCode, string]{
		Field:      "currencyCode",
		New:        NewCurrencyCode,
		Get:        CurrencyCode.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleEUR, "añó"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a code one character short",
				In:    "EU",
				Rules: []string{exampleLen},
			},
			{
				Name:  "rejects a code one character long",
				In:    "EURO",
				Rules: []string{exampleLen},
			},
			{
				Name:  "rejects the empty string, which has no characters at all",
				In:    "",
				Rules: []string{exampleLen},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestEmailAddress runs the value-object suite against the examples the directive
// and its rules declare.
func TestEmailAddress(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[EmailAddress, *EmailAddress, string]{
		Field:      "emailAddress",
		New:        NewEmailAddress,
		Get:        EmailAddress.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleWaiterExampleCom, "orders+tab7@example.com"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a local part with no domain",
				In:    "waiter",
				Rules: []string{exampleEmail},
			},
			{
				Name:  "rejects a display name, which a stored address must not carry",
				In:    "Waiter <a@b.test>",
				Rules: []string{exampleEmail},
			},
			{
				Name:  exampleRejectsTheEmptyString,
				In:    "",
				Rules: []string{exampleEmail},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestMenuLink runs the value-object suite against the examples the directive
// and its rules declare.
func TestMenuLink(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[MenuLink, *MenuLink, string]{
		Field:      "menuLink",
		New:        NewMenuLink,
		Get:        MenuLink.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"https://example.com/menu", "http://example.com:8080/menu?tab=7"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a bare host with no scheme",
				In:    "example.com",
				Rules: []string{exampleUrl},
			},
			{
				Name:  "rejects a scheme that is not http or https",
				In:    "ftp://example.com",
				Rules: []string{exampleUrl},
			},
			{
				Name:  exampleRejectsTheEmptyString,
				In:    "",
				Rules: []string{exampleUrl},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestExternalRef runs the value-object suite against the examples the directive
// and its rules declare.
func TestExternalRef(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[ExternalRef, *ExternalRef, string]{
		Field:      "externalRef",
		New:        NewExternalRef,
		Get:        ExternalRef.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"9b2b4f52-1c2d-4e5a-9f3b-6d7c8e9f0a1b", "018f3a2b-7c4d-7e8f-9a0b-1c2d3e4f5a6b"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the undashed form, which stored ids never use",
				In:    "9b2b4f521c2d4e5a9f3b6d7c8e9f0a1b",
				Rules: []string{exampleUuid},
			},
			{
				Name:  "rejects a value that is not hexadecimal at all",
				In:    "not-a-uuid",
				Rules: []string{exampleUuid},
			},
			{
				Name:  exampleRejectsTheEmptyString,
				In:    "",
				Rules: []string{exampleUuid},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestStockCode runs the value-object suite against the examples the directive
// and its rules declare.
func TestStockCode(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[StockCode, *StockCode, string]{
		Field:      "stockCode",
		New:        NewStockCode,
		Get:        StockCode.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"SKU-0042", "EUR-1000"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the prefix is not upper case",
				In:    exampleSku0042,
				Rules: []string{exampleRegex},
			},
			{
				Name:  "rejects the number is too short",
				In:    "SKU-42",
				Rules: []string{exampleRegex},
			},
			{
				Name:  "rejects the empty string, which an anchored pattern rejects",
				In:    "",
				Rules: []string{exampleRegex},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestCurrency runs the value-object suite against the examples the directive
// and its rules declare.
func TestCurrency(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[Currency, *Currency, string]{
		Field:      "currency",
		New:        NewCurrency,
		Get:        Currency.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleEur, "gbp"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a currency nobody listed",
				In:    "chf",
				Rules: []string{exampleOneof},
			},
			{
				Name:  "rejects the right item in the wrong case",
				In:    exampleEUR,
				Rules: []string{exampleOneof},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestLetterName runs the value-object suite against the examples the directive
// and its rules declare.
func TestLetterName(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[LetterName, *LetterName, string]{
		Field:      "letterName",
		New:        NewLetterName,
		Get:        LetterName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, "Muñoz"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a digit among the letters",
				In:    "Tab7",
				Rules: []string{"alpha"},
			},
			{
				Name:  "rejects a space, which is not a letter",
				In:    "de patatas",
				Rules: []string{"alpha"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestHandle runs the value-object suite against the examples the directive
// and its rules declare.
func TestHandle(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[Handle, *Handle, string]{
		Field:      "handle",
		New:        NewHandle,
		Get:        Handle.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"Tab7", "sku0042"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a hyphen, which is neither a letter nor a digit",
				In:    exampleSku0042,
				Rules: []string{"alphanum"},
			},
			{
				Name:  "rejects a space",
				In:    "tab 7",
				Rules: []string{"alphanum"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestPhoneDigits runs the value-object suite against the examples the directive
// and its rules declare.
func TestPhoneDigits(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[PhoneDigits, *PhoneDigits, string]{
		Field:      "phoneDigits",
		New:        NewPhoneDigits,
		Get:        PhoneDigits.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"0042", "600123456"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a sign, which a digit string does not carry",
				In:    "-42",
				Rules: []string{exampleNumeric},
			},
			{
				Name:  "rejects a decimal point",
				In:    "4.2",
				Rules: []string{exampleNumeric},
			},
			{
				Name:  "rejects Arabic-Indic digits, which no parser here would read",
				In:    "٤٢",
				Rules: []string{exampleNumeric},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestLegacyCode runs the value-object suite against the examples the directive
// and its rules declare.
func TestLegacyCode(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[LegacyCode, *LegacyCode, string]{
		Field:      "legacyCode",
		New:        NewLegacyCode,
		Get:        LegacyCode.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"tortilla", "SKU-0042!"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects an accented letter above U+007F",
				In:    "Muñoz",
				Rules: []string{"ascii"},
			},
			{
				Name:  "rejects a combining accent, which is not ASCII either",
				In:    "café",
				Rules: []string{"ascii"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestSingleLine runs the value-object suite against the examples the directive
// and its rules declare.
func TestSingleLine(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[SingleLine, *SingleLine, string]{
		Field:      "singleLine",
		New:        NewSingleLine,
		Get:        SingleLine.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortillaDePatatas, "Muñoz — 42 €"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a newline smuggled into a single-line value",
				In:    "Tortilla\nde patatas",
				Rules: []string{"printable"},
			},
			{
				Name:  "rejects a tab, which is a control character too",
				In:    "Tab\t7",
				Rules: []string{"printable"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestSlug runs the value-object suite against the examples the directive
// and its rules declare.
func TestSlug(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[Slug, *Slug, string]{
		Field:      "slug",
		New:        NewSlug,
		Get:        Slug.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"tortilla-de-patatas", "SKU0042"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a space in the middle",
				In:    "tortilla de patatas",
				Rules: []string{"nospace"},
			},
			{
				Name:  "rejects a trailing space a paste left behind",
				In:    "sku0042 ",
				Rules: []string{"nospace"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestProductCode runs the value-object suite against the examples the directive
// and its rules declare.
func TestProductCode(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[ProductCode, *ProductCode, string]{
		Field:      "productCode",
		New:        NewProductCode,
		Get:        ProductCode.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"SKU-0042", "SKU-"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the right prefix in the wrong case",
				In:    exampleSku0042,
				Rules: []string{examplePrefix},
			},
			{
				Name:  "rejects no namespace at all",
				In:    "0042",
				Rules: []string{examplePrefix},
			},
			{
				Name:  "rejects the empty string, which starts with nothing",
				In:    "",
				Rules: []string{examplePrefix},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestDocumentFile runs the value-object suite against the examples the directive
// and its rules declare.
func TestDocumentFile(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[DocumentFile, *DocumentFile, string]{
		Field:      "documentFile",
		New:        NewDocumentFile,
		Get:        DocumentFile.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"invoice.pdf", ".pdf"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the right extension in the wrong case",
				In:    "invoice.PDF",
				Rules: []string{"suffix"},
			},
			{
				Name:  "rejects a different extension",
				In:    "invoice.png",
				Rules: []string{"suffix"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestResourcePath runs the value-object suite against the examples the directive
// and its rules declare.
func TestResourcePath(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[ResourcePath, *ResourcePath, string]{
		Field:      "resourcePath",
		New:        NewResourcePath,
		Get:        ResourcePath.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"tabs/7", "/"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a different separator",
				In:    "tabs-7",
				Rules: []string{"contains"},
			},
			{
				Name:  "rejects the empty string, which contains nothing",
				In:    "",
				Rules: []string{"contains"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestFlatName runs the value-object suite against the examples the directive
// and its rules declare.
func TestFlatName(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[FlatName, *FlatName, string]{
		Field:      "flatName",
		New:        NewFlatName,
		Get:        FlatName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"tabs-7", ""},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the forbidden separator in the middle",
				In:    "tabs/7",
				Rules: []string{"excludes"},
			},
			{
				Name:  "rejects the forbidden separator at the front",
				In:    "/tabs",
				Rules: []string{"excludes"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestCovers runs the value-object suite against the examples the directive
// and its rules declare.
func TestCovers(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[Covers, *Covers, int64]{
		Field:      "covers",
		New:        NewCovers,
		Get:        Covers.Int64,
		FromString: NewCoversFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{1, 42},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects a table with nobody at it",
				In:    0,
				Rules: []string{exampleMin},
			},
			{
				Name:  "rejects a negative count is below any positive bound",
				In:    -5,
				Rules: []string{exampleMin},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestSeats runs the value-object suite against the examples the directive
// and its rules declare.
func TestSeats(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[Seats, *Seats, int64]{
		Field:      "seats",
		New:        NewSeats,
		Get:        Seats.Int64,
		FromString: NewSeatsFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{200, -1},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects one guest more than the room holds",
				In:    201,
				Rules: []string{exampleMax},
			},
			{
				Name:  "rejects a value far above the bound",
				In:    1000,
				Rules: []string{exampleMax},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestCourseCount runs the value-object suite against the examples the directive
// and its rules declare.
func TestCourseCount(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[CourseCount, *CourseCount, int64]{
		Field:      "courseCount",
		New:        NewCourseCount,
		Get:        CourseCount.Int64,
		FromString: NewCourseCountFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{1, 4},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects a number between two allowed ones",
				In:    3,
				Rules: []string{exampleOneof},
			},
			{
				Name:  "rejects a number below the whole list",
				In:    0,
				Rules: []string{exampleOneof},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestPortions runs the value-object suite against the examples the directive
// and its rules declare.
func TestPortions(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[Portions, *Portions, int64]{
		Field:      "portions",
		New:        NewPortions,
		Get:        Portions.Int64,
		FromString: NewPortionsFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{1, 42},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects zero, which is not positive",
				In:    0,
				Rules: []string{examplePositive},
			},
			{
				Name:  "rejects a negative count",
				In:    -1,
				Rules: []string{examplePositive},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestStockLevel runs the value-object suite against the examples the directive
// and its rules declare.
func TestStockLevel(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[StockLevel, *StockLevel, int64]{
		Field:      "stockLevel",
		New:        NewStockLevel,
		Get:        StockLevel.Int64,
		FromString: NewStockLevelFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{0, 7},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects one below the floor",
				In:    -1,
				Rules: []string{exampleNonneg},
			},
			{
				Name:  "rejects a quantity nobody can have",
				In:    -100,
				Rules: []string{exampleNonneg},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestSlotMinutes runs the value-object suite against the examples the directive
// and its rules declare.
func TestSlotMinutes(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[SlotMinutes, *SlotMinutes, int64]{
		Field:      "slotMinutes",
		New:        NewSlotMinutes,
		Get:        SlotMinutes.Int64,
		FromString: NewSlotMinutesFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{30, 0, -15},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects a duration that does not fill whole slots",
				In:    20,
				Rules: []string{"multipleof"},
			},
			{
				Name:  "rejects less than one slot",
				In:    1,
				Rules: []string{"multipleof"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestMinRate runs the value-object suite against the examples the directive
// and its rules declare.
func TestMinRate(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[MinRate, *MinRate, string]{
		Field:      "minRate",
		New:        NewMinRateFromString,
		Get:        nil,
		FromString: NewMinRateFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{"0.5", "0"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a quarter below a floor of nothing",
				In:    "-0.25",
				Rules: []string{exampleMin},
			},
			{
				Name:  "rejects a whole unit below the floor",
				In:    "-1",
				Rules: []string{exampleMin},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestMaxRate runs the value-object suite against the examples the directive
// and its rules declare.
func TestMaxRate(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[MaxRate, *MaxRate, string]{
		Field:      "maxRate",
		New:        NewMaxRateFromString,
		Get:        nil,
		FromString: NewMaxRateFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{"1", "0.25"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects half again more than the whole",
				In:    example15,
				Rules: []string{exampleMax},
			},
			{
				Name:  "rejects twice the whole bill",
				In:    "2",
				Rules: []string{exampleMax},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestUnitWeight runs the value-object suite against the examples the directive
// and its rules declare.
func TestUnitWeight(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[UnitWeight, *UnitWeight, string]{
		Field:      "unitWeight",
		New:        NewUnitWeightFromString,
		Get:        nil,
		FromString: NewUnitWeightFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{example15, "0.001"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects zero written at three decimal places is still zero",
				In:    "0.000",
				Rules: []string{examplePositive},
			},
			{
				Name:  "rejects half a unit less than nothing",
				In:    "-0.5",
				Rules: []string{examplePositive},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestShelfWeight runs the value-object suite against the examples the directive
// and its rules declare.
func TestShelfWeight(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[ShelfWeight, *ShelfWeight, string]{
		Field:      "shelfWeight",
		New:        NewShelfWeightFromString,
		Get:        nil,
		FromString: NewShelfWeightFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{"0", "12.750"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a hundredth below the floor",
				In:    "-0.01",
				Rules: []string{exampleNonneg},
			},
			{
				Name:  "rejects a quantity nobody can have",
				In:    "-100",
				Rules: []string{exampleNonneg},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestTaxRate runs the value-object suite against the examples the directive
// and its rules declare.
func TestTaxRate(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[TaxRate, *TaxRate, string]{
		Field:      "taxRate",
		New:        NewTaxRateFromString,
		Get:        nil,
		FromString: NewTaxRateFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{"0.1234", "0.5"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects one decimal place more than the column holds",
				In:    "0.12345",
				Rules: []string{"scale"},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestPreciseWeight runs the value-object suite against the examples the directive
// and its rules declare.
func TestPreciseWeight(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[PreciseWeight, *PreciseWeight, string]{
		Field:      "preciseWeight",
		New:        NewPreciseWeightFromString,
		Get:        nil,
		FromString: NewPreciseWeightFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{example15, "12.750"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a weight measured finer than the scale reads",
				In:    "0.1234",
				Rules: []string{"scale"},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestAdjustment runs the value-object suite against the examples the directive
// and its rules declare.
func TestAdjustment(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[Adjustment, *Adjustment, string]{
		Field:      "adjustment",
		New:        NewAdjustmentFromString,
		Get:        nil,
		FromString: NewAdjustmentFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{"1", "-0.5"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects nothing to adjust",
				In:    "0",
				Rules: []string{"nonzero"},
			},
			{
				Name:  "rejects nothing, written to the cent",
				In:    "0.00",
				Rules: []string{"nonzero"},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}
