// Code generated by vogue. DO NOT EDIT.

package catalogue

import (
	"database/sql/driver"
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/MathiasHilgert/vogue"
	"github.com/MathiasHilgert/vogue/rules/fn"
)

// _vogueRegexpa441fc35 is the pattern the `regex` rule matches against,
// compiled once at start-up rather than on every call.
var _vogueRegexpa441fc35 = regexp.MustCompile("^[A-Z]{3}-[0-9]{4}$")

// TrimmedName is a name with the whitespace around it removed. The `required`
// after it is what proves the normalizer ran: a value that was nothing but
// whitespace is empty by the time the check sees it.
type TrimmedName struct{ v string }

// NewTrimmedName validates raw and returns the TrimmedName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewTrimmedName(raw string) (TrimmedName, error) {
	var n vogue.Notification
	v := raw
	v = strings.TrimSpace(v)
	if !(v != "") {
		n.Add(vogue.FieldError{Field: "trimmedName", Rule: "required", Value: v, Message: "trimmedName is required"})
	}

	if err := n.ErrOrNil(); err != nil {
		return TrimmedName{}, err
	}
	return TrimmedName{v: v}, nil
}

// String returns the validated value.
func (t TrimmedName) String() string { return t.v }

// IsZero reports whether the receiver is the zero TrimmedName, which is the only
// TrimmedName that never passed validation.
func (t TrimmedName) IsZero() bool { return t.v == "" }

// Equal reports whether both value objects hold the same value.
func (t TrimmedName) Equal(other TrimmedName) bool { return t.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so TrimmedName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (t TrimmedName) MarshalText() ([]byte, error) { return []byte(t.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a TrimmedName the constructor would have rejected.
func (t *TrimmedName) UnmarshalText(data []byte) error {
	parsed, err := NewTrimmedName(string(data))
	if err != nil {
		return err
	}
	*t = parsed
	return nil
}

// Value implements driver.Valuer.
func (t TrimmedName) Value() (driver.Value, error) { return t.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (t *TrimmedName) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*t = TrimmedName{}
		return nil
	case string:
		return t.UnmarshalText([]byte(value))
	case []byte:
		return t.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into TrimmedName", src)
	}
}

// SquishedName is a name whose internal whitespace is collapsed.
type SquishedName struct{ v string }

// NewSquishedName validates raw and returns the SquishedName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewSquishedName(raw string) (SquishedName, error) {
	var n vogue.Notification
	v := raw
	v = strings.Join(strings.Fields(v), " ")
	if !(v != "") {
		n.Add(vogue.FieldError{Field: "squishedName", Rule: "required", Value: v, Message: "squishedName is required"})
	}

	if err := n.ErrOrNil(); err != nil {
		return SquishedName{}, err
	}
	return SquishedName{v: v}, nil
}

// String returns the validated value.
func (s SquishedName) String() string { return s.v }

// IsZero reports whether the receiver is the zero SquishedName, which is the only
// SquishedName that never passed validation.
func (s SquishedName) IsZero() bool { return s.v == "" }

// Equal reports whether both value objects hold the same value.
func (s SquishedName) Equal(other SquishedName) bool { return s.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so SquishedName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (s SquishedName) MarshalText() ([]byte, error) { return []byte(s.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a SquishedName the constructor would have rejected.
func (s *SquishedName) UnmarshalText(data []byte) error {
	parsed, err := NewSquishedName(string(data))
	if err != nil {
		return err
	}
	*s = parsed
	return nil
}

// Value implements driver.Valuer.
func (s SquishedName) Value() (driver.Value, error) { return s.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (s *SquishedName) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*s = SquishedName{}
		return nil
	case string:
		return s.UnmarshalText([]byte(value))
	case []byte:
		return s.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into SquishedName", src)
	}
}

// LoweredName is a name folded to lower case.
type LoweredName struct{ v string }

// NewLoweredName validates raw and returns the LoweredName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewLoweredName(raw string) (LoweredName, error) {
	var n vogue.Notification
	v := raw
	v = strings.ToLower(v)
	if !(v != "") {
		n.Add(vogue.FieldError{Field: "loweredName", Rule: "required", Value: v, Message: "loweredName is required"})
	}

	if err := n.ErrOrNil(); err != nil {
		return LoweredName{}, err
	}
	return LoweredName{v: v}, nil
}

// String returns the validated value.
func (l LoweredName) String() string { return l.v }

// IsZero reports whether the receiver is the zero LoweredName, which is the only
// LoweredName that never passed validation.
func (l LoweredName) IsZero() bool { return l.v == "" }

// Equal reports whether both value objects hold the same value.
func (l LoweredName) Equal(other LoweredName) bool { return l.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so LoweredName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (l LoweredName) MarshalText() ([]byte, error) { return []byte(l.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a LoweredName the constructor would have rejected.
func (l *LoweredName) UnmarshalText(data []byte) error {
	parsed, err := NewLoweredName(string(data))
	if err != nil {
		return err
	}
	*l = parsed
	return nil
}

// Value implements driver.Valuer.
func (l LoweredName) Value() (driver.Value, error) { return l.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (l *LoweredName) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*l = LoweredName{}
		return nil
	case string:
		return l.UnmarshalText([]byte(value))
	case []byte:
		return l.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into LoweredName", src)
	}
}

// UpperedName is a name folded to upper case.
type UpperedName struct{ v string }

// NewUpperedName validates raw and returns the UpperedName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewUpperedName(raw string) (UpperedName, error) {
	var n vogue.Notification
	v := raw
	v = strings.ToUpper(v)
	if !(v != "") {
		n.Add(vogue.FieldError{Field: "upperedName", Rule: "required", Value: v, Message: "upperedName is required"})
	}

	if err := n.ErrOrNil(); err != nil {
		return UpperedName{}, err
	}
	return UpperedName{v: v}, nil
}

// String returns the validated value.
func (u UpperedName) String() string { return u.v }

// IsZero reports whether the receiver is the zero UpperedName, which is the only
// UpperedName that never passed validation.
func (u UpperedName) IsZero() bool { return u.v == "" }

// Equal reports whether both value objects hold the same value.
func (u UpperedName) Equal(other UpperedName) bool { return u.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so UpperedName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (u UpperedName) MarshalText() ([]byte, error) { return []byte(u.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a UpperedName the constructor would have rejected.
func (u *UpperedName) UnmarshalText(data []byte) error {
	parsed, err := NewUpperedName(string(data))
	if err != nil {
		return err
	}
	*u = parsed
	return nil
}

// Value implements driver.Valuer.
func (u UpperedName) Value() (driver.Value, error) { return u.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (u *UpperedName) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*u = UpperedName{}
		return nil
	case string:
		return u.UnmarshalText([]byte(value))
	case []byte:
		return u.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into UpperedName", src)
	}
}

// RequiredName is a name that must be given.
type RequiredName struct{ v string }

// NewRequiredName validates raw and returns the RequiredName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewRequiredName(raw string) (RequiredName, error) {
	var n vogue.Notification
	v := raw
	if !(v != "") {
		n.Add(vogue.FieldError{Field: "requiredName", Rule: "required", Value: v, Message: "requiredName is required"})
	}

	if err := n.ErrOrNil(); err != nil {
		return RequiredName{}, err
	}
	return RequiredName{v: v}, nil
}

// String returns the validated value.
func (r RequiredName) String() string { return r.v }

// IsZero reports whether the receiver is the zero RequiredName, which is the only
// RequiredName that never passed validation.
func (r RequiredName) IsZero() bool { return r.v == "" }

// Equal reports whether both value objects hold the same value.
func (r RequiredName) Equal(other RequiredName) bool { return r.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so RequiredName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (r RequiredName) MarshalText() ([]byte, error) { return []byte(r.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a RequiredName the constructor would have rejected.
func (r *RequiredName) UnmarshalText(data []byte) error {
	parsed, err := NewRequiredName(string(data))
	if err != nil {
		return err
	}
	*r = parsed
	return nil
}

// Value implements driver.Valuer.
func (r RequiredName) Value() (driver.Value, error) { return r.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (r *RequiredName) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*r = RequiredName{}
		return nil
	case string:
		return r.UnmarshalText([]byte(value))
	case []byte:
		return r.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into RequiredName", src)
	}
}

// ShortName is a name of at least one character.
type ShortName struct{ v string }

// NewShortName validates raw and returns the ShortName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewShortName(raw string) (ShortName, error) {
	var n vogue.Notification
	v := raw
	if !(utf8.RuneCountInString(v) >= 1) {
		n.Add(vogue.FieldError{Field: "shortName", Rule: "min", Param: "1", Value: v, Message: "shortName must be at least 1"})
	}

	if err := n.ErrOrNil(); err != nil {
		return ShortName{}, err
	}
	return ShortName{v: v}, nil
}

// String returns the validated value.
func (s ShortName) String() string { return s.v }

// IsZero reports whether the receiver is the zero ShortName, which is the only
// ShortName that never passed validation.
func (s ShortName) IsZero() bool { return s.v == "" }

// Equal reports whether both value objects hold the same value.
func (s ShortName) Equal(other ShortName) bool { return s.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so ShortName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (s ShortName) MarshalText() ([]byte, error) { return []byte(s.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a ShortName the constructor would have rejected.
func (s *ShortName) UnmarshalText(data []byte) error {
	parsed, err := NewShortName(string(data))
	if err != nil {
		return err
	}
	*s = parsed
	return nil
}

// Value implements driver.Valuer.
func (s ShortName) Value() (driver.Value, error) { return s.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (s *ShortName) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*s = ShortName{}
		return nil
	case string:
		return s.UnmarshalText([]byte(value))
	case []byte:
		return s.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into ShortName", src)
	}
}

// LongerName is a name of at least three characters.
type LongerName struct{ v string }

// NewLongerName validates raw and returns the LongerName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewLongerName(raw string) (LongerName, error) {
	var n vogue.Notification
	v := raw
	if !(utf8.RuneCountInString(v) >= 3) {
		n.Add(vogue.FieldError{Field: "longerName", Rule: "min", Param: "3", Value: v, Message: "longerName must be at least 3"})
	}

	if err := n.ErrOrNil(); err != nil {
		return LongerName{}, err
	}
	return LongerName{v: v}, nil
}

// String returns the validated value.
func (l LongerName) String() string { return l.v }

// IsZero reports whether the receiver is the zero LongerName, which is the only
// LongerName that never passed validation.
func (l LongerName) IsZero() bool { return l.v == "" }

// Equal reports whether both value objects hold the same value.
func (l LongerName) Equal(other LongerName) bool { return l.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so LongerName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (l LongerName) MarshalText() ([]byte, error) { return []byte(l.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a LongerName the constructor would have rejected.
func (l *LongerName) UnmarshalText(data []byte) error {
	parsed, err := NewLongerName(string(data))
	if err != nil {
		return err
	}
	*l = parsed
	return nil
}

// Value implements driver.Valuer.
func (l LongerName) Value() (driver.Value, error) { return l.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (l *LongerName) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*l = LongerName{}
		return nil
	case string:
		return l.UnmarshalText([]byte(value))
	case []byte:
		return l.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into LongerName", src)
	}
}

// BoundedName is a name of at most four characters.
type BoundedName struct{ v string }

// NewBoundedName validates raw and returns the BoundedName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewBoundedName(raw string) (BoundedName, error) {
	var n vogue.Notification
	v := raw
	if !(utf8.RuneCountInString(v) <= 4) {
		n.Add(vogue.FieldError{Field: "boundedName", Rule: "max", Param: "4", Value: v, Message: "boundedName must be at most 4"})
	}

	if err := n.ErrOrNil(); err != nil {
		return BoundedName{}, err
	}
	return BoundedName{v: v}, nil
}

// String returns the validated value.
func (b BoundedName) String() string { return b.v }

// IsZero reports whether the receiver is the zero BoundedName, which is the only
// BoundedName that never passed validation.
func (b BoundedName) IsZero() bool { return b.v == "" }

// Equal reports whether both value objects hold the same value.
func (b BoundedName) Equal(other BoundedName) bool { return b.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so BoundedName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (b BoundedName) MarshalText() ([]byte, error) { return []byte(b.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a BoundedName the constructor would have rejected.
func (b *BoundedName) UnmarshalText(data []byte) error {
	parsed, err := NewBoundedName(string(data))
	if err != nil {
		return err
	}
	*b = parsed
	return nil
}

// Value implements driver.Valuer.
func (b BoundedName) Value() (driver.Value, error) { return b.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (b *BoundedName) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*b = BoundedName{}
		return nil
	case string:
		return b.UnmarshalText([]byte(value))
	case []byte:
		return b.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into BoundedName", src)
	}
}

// CurrencyCode is a currency code of exactly three characters.
type CurrencyCode struct{ v string }

// NewCurrencyCode validates raw and returns the CurrencyCode it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewCurrencyCode(raw string) (CurrencyCode, error) {
	var n vogue.Notification
	v := raw
	if !(utf8.RuneCountInString(v) == 3) {
		n.Add(vogue.FieldError{Field: "currencyCode", Rule: "len", Param: "3", Value: v, Message: "currencyCode must be exactly 3 characters long"})
	}

	if err := n.ErrOrNil(); err != nil {
		return CurrencyCode{}, err
	}
	return CurrencyCode{v: v}, nil
}

// String returns the validated value.
func (c CurrencyCode) String() string { return c.v }

// IsZero reports whether the receiver is the zero CurrencyCode, which is the only
// CurrencyCode that never passed validation.
func (c CurrencyCode) IsZero() bool { return c.v == "" }

// Equal reports whether both value objects hold the same value.
func (c CurrencyCode) Equal(other CurrencyCode) bool { return c.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so CurrencyCode marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (c CurrencyCode) MarshalText() ([]byte, error) { return []byte(c.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a CurrencyCode the constructor would have rejected.
func (c *CurrencyCode) UnmarshalText(data []byte) error {
	parsed, err := NewCurrencyCode(string(data))
	if err != nil {
		return err
	}
	*c = parsed
	return nil
}

// Value implements driver.Valuer.
func (c CurrencyCode) Value() (driver.Value, error) { return c.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (c *CurrencyCode) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*c = CurrencyCode{}
		return nil
	case string:
		return c.UnmarshalText([]byte(value))
	case []byte:
		return c.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into CurrencyCode", src)
	}
}

// EmailAddress is a mailbox a guest can be written to at.
type EmailAddress struct{ v string }

// NewEmailAddress validates raw and returns the EmailAddress it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewEmailAddress(raw string) (EmailAddress, error) {
	var n vogue.Notification
	v := raw
	if !(fn.Email(v)) {
		n.Add(vogue.FieldError{Field: "emailAddress", Rule: "email", Value: v, Message: "emailAddress must be a valid email address"})
	}

	if err := n.ErrOrNil(); err != nil {
		return EmailAddress{}, err
	}
	return EmailAddress{v: v}, nil
}

// String returns the validated value.
func (e EmailAddress) String() string { return e.v }

// IsZero reports whether the receiver is the zero EmailAddress, which is the only
// EmailAddress that never passed validation.
func (e EmailAddress) IsZero() bool { return e.v == "" }

// Equal reports whether both value objects hold the same value.
func (e EmailAddress) Equal(other EmailAddress) bool { return e.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so EmailAddress marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (e EmailAddress) MarshalText() ([]byte, error) { return []byte(e.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a EmailAddress the constructor would have rejected.
func (e *EmailAddress) UnmarshalText(data []byte) error {
	parsed, err := NewEmailAddress(string(data))
	if err != nil {
		return err
	}
	*e = parsed
	return nil
}

// Value implements driver.Valuer.
func (e EmailAddress) Value() (driver.Value, error) { return e.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (e *EmailAddress) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*e = EmailAddress{}
		return nil
	case string:
		return e.UnmarshalText([]byte(value))
	case []byte:
		return e.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into EmailAddress", src)
	}
}

// MenuLink is the address of a published menu.
type MenuLink struct{ v string }

// NewMenuLink validates raw and returns the MenuLink it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewMenuLink(raw string) (MenuLink, error) {
	var n vogue.Notification
	v := raw
	if !(fn.URL(v)) {
		n.Add(vogue.FieldError{Field: "menuLink", Rule: "url", Value: v, Message: "menuLink must be a valid http or https URL"})
	}

	if err := n.ErrOrNil(); err != nil {
		return MenuLink{}, err
	}
	return MenuLink{v: v}, nil
}

// String returns the validated value.
func (m MenuLink) String() string { return m.v }

// IsZero reports whether the receiver is the zero MenuLink, which is the only
// MenuLink that never passed validation.
func (m MenuLink) IsZero() bool { return m.v == "" }

// Equal reports whether both value objects hold the same value.
func (m MenuLink) Equal(other MenuLink) bool { return m.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so MenuLink marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (m MenuLink) MarshalText() ([]byte, error) { return []byte(m.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a MenuLink the constructor would have rejected.
func (m *MenuLink) UnmarshalText(data []byte) error {
	parsed, err := NewMenuLink(string(data))
	if err != nil {
		return err
	}
	*m = parsed
	return nil
}

// Value implements driver.Valuer.
func (m MenuLink) Value() (driver.Value, error) { return m.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (m *MenuLink) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*m = MenuLink{}
		return nil
	case string:
		return m.UnmarshalText([]byte(value))
	case []byte:
		return m.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into MenuLink", src)
	}
}

// ExternalRef is an identifier another system assigned, written as a UUID.
type ExternalRef struct{ v string }

// NewExternalRef validates raw and returns the ExternalRef it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewExternalRef(raw string) (ExternalRef, error) {
	var n vogue.Notification
	v := raw
	if !(fn.UUID(v)) {
		n.Add(vogue.FieldError{Field: "externalRef", Rule: "uuid", Value: v, Message: "externalRef must be a valid UUID"})
	}

	if err := n.ErrOrNil(); err != nil {
		return ExternalRef{}, err
	}
	return ExternalRef{v: v}, nil
}

// String returns the validated value.
func (e ExternalRef) String() string { return e.v }

// IsZero reports whether the receiver is the zero ExternalRef, which is the only
// ExternalRef that never passed validation.
func (e ExternalRef) IsZero() bool { return e.v == "" }

// Equal reports whether both value objects hold the same value.
func (e ExternalRef) Equal(other ExternalRef) bool { return e.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so ExternalRef marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (e ExternalRef) MarshalText() ([]byte, error) { return []byte(e.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a ExternalRef the constructor would have rejected.
func (e *ExternalRef) UnmarshalText(data []byte) error {
	parsed, err := NewExternalRef(string(data))
	if err != nil {
		return err
	}
	*e = parsed
	return nil
}

// Value implements driver.Valuer.
func (e ExternalRef) Value() (driver.Value, error) { return e.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (e *ExternalRef) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*e = ExternalRef{}
		return nil
	case string:
		return e.UnmarshalText([]byte(value))
	case []byte:
		return e.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into ExternalRef", src)
	}
}

// StockCode is a stock code in the documented SKU shape.
type StockCode struct{ v string }

// NewStockCode validates raw and returns the StockCode it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewStockCode(raw string) (StockCode, error) {
	var n vogue.Notification
	v := raw
	if !(_vogueRegexpa441fc35.MatchString(v)) {
		n.Add(vogue.FieldError{Field: "stockCode", Rule: "regex", Param: "^[A-Z]{3}-[0-9]{4}$", Value: v, Message: "stockCode must match the pattern ^[A-Z]{3}-[0-9]{4}$"})
	}

	if err := n.ErrOrNil(); err != nil {
		return StockCode{}, err
	}
	return StockCode{v: v}, nil
}

// String returns the validated value.
func (s StockCode) String() string { return s.v }

// IsZero reports whether the receiver is the zero StockCode, which is the only
// StockCode that never passed validation.
func (s StockCode) IsZero() bool { return s.v == "" }

// Equal reports whether both value objects hold the same value.
func (s StockCode) Equal(other StockCode) bool { return s.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so StockCode marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (s StockCode) MarshalText() ([]byte, error) { return []byte(s.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a StockCode the constructor would have rejected.
func (s *StockCode) UnmarshalText(data []byte) error {
	parsed, err := NewStockCode(string(data))
	if err != nil {
		return err
	}
	*s = parsed
	return nil
}

// Value implements driver.Valuer.
func (s StockCode) Value() (driver.Value, error) { return s.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (s *StockCode) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*s = StockCode{}
		return nil
	case string:
		return s.UnmarshalText([]byte(value))
	case []byte:
		return s.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into StockCode", src)
	}
}

// Currency is one of the currencies the restaurant takes.
type Currency struct{ v string }

// NewCurrency validates raw and returns the Currency it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewCurrency(raw string) (Currency, error) {
	var n vogue.Notification
	v := raw
	if !(v == "eur" || v == "usd" || v == "gbp") {
		n.Add(vogue.FieldError{Field: "currency", Rule: "oneof", Param: "eur,usd,gbp", Value: v, Message: "currency must be one of: eur,usd,gbp"})
	}

	if err := n.ErrOrNil(); err != nil {
		return Currency{}, err
	}
	return Currency{v: v}, nil
}

// String returns the validated value.
func (c Currency) String() string { return c.v }

// IsZero reports whether the receiver is the zero Currency, which is the only
// Currency that never passed validation.
func (c Currency) IsZero() bool { return c.v == "" }

// Equal reports whether both value objects hold the same value.
func (c Currency) Equal(other Currency) bool { return c.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so Currency marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (c Currency) MarshalText() ([]byte, error) { return []byte(c.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a Currency the constructor would have rejected.
func (c *Currency) UnmarshalText(data []byte) error {
	parsed, err := NewCurrency(string(data))
	if err != nil {
		return err
	}
	*c = parsed
	return nil
}

// Value implements driver.Valuer.
func (c Currency) Value() (driver.Value, error) { return c.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (c *Currency) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*c = Currency{}
		return nil
	case string:
		return c.UnmarshalText([]byte(value))
	case []byte:
		return c.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into Currency", src)
	}
}

// LetterName is a name written in letters only.
type LetterName struct{ v string }

// NewLetterName validates raw and returns the LetterName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewLetterName(raw string) (LetterName, error) {
	var n vogue.Notification
	v := raw
	if !(strings.IndexFunc(v, func(r rune) bool { return !unicode.IsLetter(r) }) < 0) {
		n.Add(vogue.FieldError{Field: "letterName", Rule: "alpha", Value: v, Message: "letterName must contain letters only"})
	}

	if err := n.ErrOrNil(); err != nil {
		return LetterName{}, err
	}
	return LetterName{v: v}, nil
}

// String returns the validated value.
func (l LetterName) String() string { return l.v }

// IsZero reports whether the receiver is the zero LetterName, which is the only
// LetterName that never passed validation.
func (l LetterName) IsZero() bool { return l.v == "" }

// Equal reports whether both value objects hold the same value.
func (l LetterName) Equal(other LetterName) bool { return l.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so LetterName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (l LetterName) MarshalText() ([]byte, error) { return []byte(l.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a LetterName the constructor would have rejected.
func (l *LetterName) UnmarshalText(data []byte) error {
	parsed, err := NewLetterName(string(data))
	if err != nil {
		return err
	}
	*l = parsed
	return nil
}

// Value implements driver.Valuer.
func (l LetterName) Value() (driver.Value, error) { return l.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (l *LetterName) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*l = LetterName{}
		return nil
	case string:
		return l.UnmarshalText([]byte(value))
	case []byte:
		return l.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into LetterName", src)
	}
}

// Handle is a short code of letters and digits.
type Handle struct{ v string }

// NewHandle validates raw and returns the Handle it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewHandle(raw string) (Handle, error) {
	var n vogue.Notification
	v := raw
	if !(strings.IndexFunc(v, func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) }) < 0) {
		n.Add(vogue.FieldError{Field: "handle", Rule: "alphanum", Value: v, Message: "handle must contain letters and digits only"})
	}

	if err := n.ErrOrNil(); err != nil {
		return Handle{}, err
	}
	return Handle{v: v}, nil
}

// String returns the validated value.
func (h Handle) String() string { return h.v }

// IsZero reports whether the receiver is the zero Handle, which is the only
// Handle that never passed validation.
func (h Handle) IsZero() bool { return h.v == "" }

// Equal reports whether both value objects hold the same value.
func (h Handle) Equal(other Handle) bool { return h.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so Handle marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (h Handle) MarshalText() ([]byte, error) { return []byte(h.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a Handle the constructor would have rejected.
func (h *Handle) UnmarshalText(data []byte) error {
	parsed, err := NewHandle(string(data))
	if err != nil {
		return err
	}
	*h = parsed
	return nil
}

// Value implements driver.Valuer.
func (h Handle) Value() (driver.Value, error) { return h.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (h *Handle) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*h = Handle{}
		return nil
	case string:
		return h.UnmarshalText([]byte(value))
	case []byte:
		return h.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into Handle", src)
	}
}

// PhoneDigits is a phone number written as digits only.
type PhoneDigits struct{ v string }

// NewPhoneDigits validates raw and returns the PhoneDigits it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewPhoneDigits(raw string) (PhoneDigits, error) {
	var n vogue.Notification
	v := raw
	if !(strings.IndexFunc(v, func(r rune) bool { return r < '0' || r > '9' }) < 0) {
		n.Add(vogue.FieldError{Field: "phoneDigits", Rule: "numeric", Value: v, Message: "phoneDigits must contain digits only"})
	}

	if err := n.ErrOrNil(); err != nil {
		return PhoneDigits{}, err
	}
	return PhoneDigits{v: v}, nil
}

// String returns the validated value.
func (p PhoneDigits) String() string { return p.v }

// IsZero reports whether the receiver is the zero PhoneDigits, which is the only
// PhoneDigits that never passed validation.
func (p PhoneDigits) IsZero() bool { return p.v == "" }

// Equal reports whether both value objects hold the same value.
func (p PhoneDigits) Equal(other PhoneDigits) bool { return p.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so PhoneDigits marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (p PhoneDigits) MarshalText() ([]byte, error) { return []byte(p.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a PhoneDigits the constructor would have rejected.
func (p *PhoneDigits) UnmarshalText(data []byte) error {
	parsed, err := NewPhoneDigits(string(data))
	if err != nil {
		return err
	}
	*p = parsed
	return nil
}

// Value implements driver.Valuer.
func (p PhoneDigits) Value() (driver.Value, error) { return p.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (p *PhoneDigits) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*p = PhoneDigits{}
		return nil
	case string:
		return p.UnmarshalText([]byte(value))
	case []byte:
		return p.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into PhoneDigits", src)
	}
}

// LegacyCode is a code an ASCII-only system has to read.
type LegacyCode struct{ v string }

// NewLegacyCode validates raw and returns the LegacyCode it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewLegacyCode(raw string) (LegacyCode, error) {
	var n vogue.Notification
	v := raw
	if !(strings.IndexFunc(v, func(r rune) bool { return r >= utf8.RuneSelf }) < 0) {
		n.Add(vogue.FieldError{Field: "legacyCode", Rule: "ascii", Value: v, Message: "legacyCode must contain ASCII characters only"})
	}

	if err := n.ErrOrNil(); err != nil {
		return LegacyCode{}, err
	}
	return LegacyCode{v: v}, nil
}

// String returns the validated value.
func (l LegacyCode) String() string { return l.v }

// IsZero reports whether the receiver is the zero LegacyCode, which is the only
// LegacyCode that never passed validation.
func (l LegacyCode) IsZero() bool { return l.v == "" }

// Equal reports whether both value objects hold the same value.
func (l LegacyCode) Equal(other LegacyCode) bool { return l.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so LegacyCode marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (l LegacyCode) MarshalText() ([]byte, error) { return []byte(l.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a LegacyCode the constructor would have rejected.
func (l *LegacyCode) UnmarshalText(data []byte) error {
	parsed, err := NewLegacyCode(string(data))
	if err != nil {
		return err
	}
	*l = parsed
	return nil
}

// Value implements driver.Valuer.
func (l LegacyCode) Value() (driver.Value, error) { return l.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (l *LegacyCode) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*l = LegacyCode{}
		return nil
	case string:
		return l.UnmarshalText([]byte(value))
	case []byte:
		return l.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into LegacyCode", src)
	}
}

// SingleLine is a line of text carrying no control characters.
type SingleLine struct{ v string }

// NewSingleLine validates raw and returns the SingleLine it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewSingleLine(raw string) (SingleLine, error) {
	var n vogue.Notification
	v := raw
	if !(strings.IndexFunc(v, func(r rune) bool { return !unicode.IsPrint(r) }) < 0) {
		n.Add(vogue.FieldError{Field: "singleLine", Rule: "printable", Value: v, Message: "singleLine must not contain control characters"})
	}

	if err := n.ErrOrNil(); err != nil {
		return SingleLine{}, err
	}
	return SingleLine{v: v}, nil
}

// String returns the validated value.
func (s SingleLine) String() string { return s.v }

// IsZero reports whether the receiver is the zero SingleLine, which is the only
// SingleLine that never passed validation.
func (s SingleLine) IsZero() bool { return s.v == "" }

// Equal reports whether both value objects hold the same value.
func (s SingleLine) Equal(other SingleLine) bool { return s.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so SingleLine marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (s SingleLine) MarshalText() ([]byte, error) { return []byte(s.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a SingleLine the constructor would have rejected.
func (s *SingleLine) UnmarshalText(data []byte) error {
	parsed, err := NewSingleLine(string(data))
	if err != nil {
		return err
	}
	*s = parsed
	return nil
}

// Value implements driver.Valuer.
func (s SingleLine) Value() (driver.Value, error) { return s.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (s *SingleLine) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*s = SingleLine{}
		return nil
	case string:
		return s.UnmarshalText([]byte(value))
	case []byte:
		return s.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into SingleLine", src)
	}
}

// Slug is a URL-safe token carrying no whitespace.
type Slug struct{ v string }

// NewSlug validates raw and returns the Slug it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewSlug(raw string) (Slug, error) {
	var n vogue.Notification
	v := raw
	if !(strings.IndexFunc(v, unicode.IsSpace) < 0) {
		n.Add(vogue.FieldError{Field: "slug", Rule: "nospace", Value: v, Message: "slug must not contain spaces"})
	}

	if err := n.ErrOrNil(); err != nil {
		return Slug{}, err
	}
	return Slug{v: v}, nil
}

// String returns the validated value.
func (s Slug) String() string { return s.v }

// IsZero reports whether the receiver is the zero Slug, which is the only
// Slug that never passed validation.
func (s Slug) IsZero() bool { return s.v == "" }

// Equal reports whether both value objects hold the same value.
func (s Slug) Equal(other Slug) bool { return s.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so Slug marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (s Slug) MarshalText() ([]byte, error) { return []byte(s.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a Slug the constructor would have rejected.
func (s *Slug) UnmarshalText(data []byte) error {
	parsed, err := NewSlug(string(data))
	if err != nil {
		return err
	}
	*s = parsed
	return nil
}

// Value implements driver.Valuer.
func (s Slug) Value() (driver.Value, error) { return s.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (s *Slug) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*s = Slug{}
		return nil
	case string:
		return s.UnmarshalText([]byte(value))
	case []byte:
		return s.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into Slug", src)
	}
}

// ProductCode is a code inside the SKU namespace.
type ProductCode struct{ v string }

// NewProductCode validates raw and returns the ProductCode it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewProductCode(raw string) (ProductCode, error) {
	var n vogue.Notification
	v := raw
	if !(strings.HasPrefix(v, "SKU-")) {
		n.Add(vogue.FieldError{Field: "productCode", Rule: "prefix", Param: "SKU-", Value: v, Message: "productCode must start with \"SKU-\""})
	}

	if err := n.ErrOrNil(); err != nil {
		return ProductCode{}, err
	}
	return ProductCode{v: v}, nil
}

// String returns the validated value.
func (p ProductCode) String() string { return p.v }

// IsZero reports whether the receiver is the zero ProductCode, which is the only
// ProductCode that never passed validation.
func (p ProductCode) IsZero() bool { return p.v == "" }

// Equal reports whether both value objects hold the same value.
func (p ProductCode) Equal(other ProductCode) bool { return p.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so ProductCode marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (p ProductCode) MarshalText() ([]byte, error) { return []byte(p.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a ProductCode the constructor would have rejected.
func (p *ProductCode) UnmarshalText(data []byte) error {
	parsed, err := NewProductCode(string(data))
	if err != nil {
		return err
	}
	*p = parsed
	return nil
}

// Value implements driver.Valuer.
func (p ProductCode) Value() (driver.Value, error) { return p.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (p *ProductCode) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*p = ProductCode{}
		return nil
	case string:
		return p.UnmarshalText([]byte(value))
	case []byte:
		return p.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into ProductCode", src)
	}
}

// DocumentFile is the name of a PDF document.
type DocumentFile struct{ v string }

// NewDocumentFile validates raw and returns the DocumentFile it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewDocumentFile(raw string) (DocumentFile, error) {
	var n vogue.Notification
	v := raw
	if !(strings.HasSuffix(v, ".pdf")) {
		n.Add(vogue.FieldError{Field: "documentFile", Rule: "suffix", Param: ".pdf", Value: v, Message: "documentFile must end with \".pdf\""})
	}

	if err := n.ErrOrNil(); err != nil {
		return DocumentFile{}, err
	}
	return DocumentFile{v: v}, nil
}

// String returns the validated value.
func (d DocumentFile) String() string { return d.v }

// IsZero reports whether the receiver is the zero DocumentFile, which is the only
// DocumentFile that never passed validation.
func (d DocumentFile) IsZero() bool { return d.v == "" }

// Equal reports whether both value objects hold the same value.
func (d DocumentFile) Equal(other DocumentFile) bool { return d.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so DocumentFile marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (d DocumentFile) MarshalText() ([]byte, error) { return []byte(d.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a DocumentFile the constructor would have rejected.
func (d *DocumentFile) UnmarshalText(data []byte) error {
	parsed, err := NewDocumentFile(string(data))
	if err != nil {
		return err
	}
	*d = parsed
	return nil
}

// Value implements driver.Valuer.
func (d DocumentFile) Value() (driver.Value, error) { return d.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (d *DocumentFile) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*d = DocumentFile{}
		return nil
	case string:
		return d.UnmarshalText([]byte(value))
	case []byte:
		return d.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into DocumentFile", src)
	}
}

// ResourcePath is a path carrying a separator.
type ResourcePath struct{ v string }

// NewResourcePath validates raw and returns the ResourcePath it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewResourcePath(raw string) (ResourcePath, error) {
	var n vogue.Notification
	v := raw
	if !(strings.Contains(v, "/")) {
		n.Add(vogue.FieldError{Field: "resourcePath", Rule: "contains", Param: "/", Value: v, Message: "resourcePath must contain \"/\""})
	}

	if err := n.ErrOrNil(); err != nil {
		return ResourcePath{}, err
	}
	return ResourcePath{v: v}, nil
}

// String returns the validated value.
func (r ResourcePath) String() string { return r.v }

// IsZero reports whether the receiver is the zero ResourcePath, which is the only
// ResourcePath that never passed validation.
func (r ResourcePath) IsZero() bool { return r.v == "" }

// Equal reports whether both value objects hold the same value.
func (r ResourcePath) Equal(other ResourcePath) bool { return r.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so ResourcePath marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (r ResourcePath) MarshalText() ([]byte, error) { return []byte(r.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a ResourcePath the constructor would have rejected.
func (r *ResourcePath) UnmarshalText(data []byte) error {
	parsed, err := NewResourcePath(string(data))
	if err != nil {
		return err
	}
	*r = parsed
	return nil
}

// Value implements driver.Valuer.
func (r ResourcePath) Value() (driver.Value, error) { return r.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (r *ResourcePath) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*r = ResourcePath{}
		return nil
	case string:
		return r.UnmarshalText([]byte(value))
	case []byte:
		return r.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into ResourcePath", src)
	}
}

// FlatName is a name carrying no separator.
type FlatName struct{ v string }

// NewFlatName validates raw and returns the FlatName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [vogue.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewFlatName(raw string) (FlatName, error) {
	var n vogue.Notification
	v := raw
	if !(!strings.Contains(v, "/")) {
		n.Add(vogue.FieldError{Field: "flatName", Rule: "excludes", Param: "/", Value: v, Message: "flatName must not contain \"/\""})
	}

	if err := n.ErrOrNil(); err != nil {
		return FlatName{}, err
	}
	return FlatName{v: v}, nil
}

// String returns the validated value.
func (f FlatName) String() string { return f.v }

// IsZero reports whether the receiver is the zero FlatName, which is the only
// FlatName that never passed validation.
func (f FlatName) IsZero() bool { return f.v == "" }

// Equal reports whether both value objects hold the same value.
func (f FlatName) Equal(other FlatName) bool { return f.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so FlatName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (f FlatName) MarshalText() ([]byte, error) { return []byte(f.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a FlatName the constructor would have rejected.
func (f *FlatName) UnmarshalText(data []byte) error {
	parsed, err := NewFlatName(string(data))
	if err != nil {
		return err
	}
	*f = parsed
	return nil
}

// Value implements driver.Valuer.
func (f FlatName) Value() (driver.Value, error) { return f.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (f *FlatName) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*f = FlatName{}
		return nil
	case string:
		return f.UnmarshalText([]byte(value))
	case []byte:
		return f.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into FlatName", src)
	}
}

// Covers is the number of guests seated at a tab, at least one.
//
// The value is held as an int64 so it survives every database driver and JSON
// number without a widening conversion at the boundary.
type Covers struct{ v int64 }

// NewCovers validates raw and returns the Covers it describes.
//
// Rules are applied in the order they were declared, and every failure is
// collected into one error rather than the first one aborting the rest.
func NewCovers(raw int64) (Covers, error) {
	var n vogue.Notification
	v := raw
	if !(v >= 1) {
		n.Add(vogue.FieldError{Field: "covers", Rule: "min", Param: "1", Value: strconv.FormatInt(v, 10), Message: "covers must be at least 1"})
	}

	if err := n.ErrOrNil(); err != nil {
		return Covers{}, err
	}
	return Covers{v: v}, nil
}

// ParseCovers reads a base-10 representation and validates it.
func ParseCovers(raw string) (Covers, error) {
	v, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var n vogue.Notification
		n.Add(vogue.FieldError{Field: "covers", Rule: "int", Value: raw, Message: "covers must be a whole number"})
		return Covers{}, n.ErrOrNil()
	}
	return NewCovers(v)
}

// Int64 returns the validated value.
func (c Covers) Int64() int64 { return c.v }

// String returns the base-10 representation of the value.
func (c Covers) String() string { return strconv.FormatInt(c.v, 10) }

// IsZero reports whether the receiver is the zero Covers, which is the only
// Covers that never passed validation.
func (c Covers) IsZero() bool { return c.v == 0 }

// Equal reports whether both value objects hold the same value.
func (c Covers) Equal(other Covers) bool { return c.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json uses the text
// codec when a type implements it, so Covers round-trips through JSON without
// a MarshalJSON of its own.
func (c Covers) MarshalText() ([]byte, error) {
	return strconv.AppendInt(nil, c.v, 10), nil
}

// UnmarshalText implements encoding.TextUnmarshaler, re-running validation so
// no payload can produce a Covers the constructor would have rejected.
func (c *Covers) UnmarshalText(data []byte) error {
	parsed, err := ParseCovers(string(data))
	if err != nil {
		return err
	}
	*c = parsed
	return nil
}

// Value implements driver.Valuer.
func (c Covers) Value() (driver.Value, error) { return c.v, nil }

// Scan implements sql.Scanner for integer and text columns, re-running
// validation so a row that no longer satisfies the rules surfaces as a vogue
// error.
func (c *Covers) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*c = Covers{}
		return nil
	case int64:
		parsed, err := NewCovers(value)
		if err != nil {
			return err
		}
		*c = parsed
		return nil
	case string:
		return c.UnmarshalText([]byte(value))
	case []byte:
		return c.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into Covers", src)
	}
}

// Seats is the number of seats in the room, at most two hundred.
//
// The value is held as an int64 so it survives every database driver and JSON
// number without a widening conversion at the boundary.
type Seats struct{ v int64 }

// NewSeats validates raw and returns the Seats it describes.
//
// Rules are applied in the order they were declared, and every failure is
// collected into one error rather than the first one aborting the rest.
func NewSeats(raw int64) (Seats, error) {
	var n vogue.Notification
	v := raw
	if !(v <= 200) {
		n.Add(vogue.FieldError{Field: "seats", Rule: "max", Param: "200", Value: strconv.FormatInt(v, 10), Message: "seats must be at most 200"})
	}

	if err := n.ErrOrNil(); err != nil {
		return Seats{}, err
	}
	return Seats{v: v}, nil
}

// ParseSeats reads a base-10 representation and validates it.
func ParseSeats(raw string) (Seats, error) {
	v, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var n vogue.Notification
		n.Add(vogue.FieldError{Field: "seats", Rule: "int", Value: raw, Message: "seats must be a whole number"})
		return Seats{}, n.ErrOrNil()
	}
	return NewSeats(v)
}

// Int64 returns the validated value.
func (s Seats) Int64() int64 { return s.v }

// String returns the base-10 representation of the value.
func (s Seats) String() string { return strconv.FormatInt(s.v, 10) }

// IsZero reports whether the receiver is the zero Seats, which is the only
// Seats that never passed validation.
func (s Seats) IsZero() bool { return s.v == 0 }

// Equal reports whether both value objects hold the same value.
func (s Seats) Equal(other Seats) bool { return s.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json uses the text
// codec when a type implements it, so Seats round-trips through JSON without
// a MarshalJSON of its own.
func (s Seats) MarshalText() ([]byte, error) {
	return strconv.AppendInt(nil, s.v, 10), nil
}

// UnmarshalText implements encoding.TextUnmarshaler, re-running validation so
// no payload can produce a Seats the constructor would have rejected.
func (s *Seats) UnmarshalText(data []byte) error {
	parsed, err := ParseSeats(string(data))
	if err != nil {
		return err
	}
	*s = parsed
	return nil
}

// Value implements driver.Valuer.
func (s Seats) Value() (driver.Value, error) { return s.v, nil }

// Scan implements sql.Scanner for integer and text columns, re-running
// validation so a row that no longer satisfies the rules surfaces as a vogue
// error.
func (s *Seats) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*s = Seats{}
		return nil
	case int64:
		parsed, err := NewSeats(value)
		if err != nil {
			return err
		}
		*s = parsed
		return nil
	case string:
		return s.UnmarshalText([]byte(value))
	case []byte:
		return s.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into Seats", src)
	}
}

// CourseCount is one of the menu sizes the kitchen serves.
//
// The value is held as an int64 so it survives every database driver and JSON
// number without a widening conversion at the boundary.
type CourseCount struct{ v int64 }

// NewCourseCount validates raw and returns the CourseCount it describes.
//
// Rules are applied in the order they were declared, and every failure is
// collected into one error rather than the first one aborting the rest.
func NewCourseCount(raw int64) (CourseCount, error) {
	var n vogue.Notification
	v := raw
	if !(v == 1 || v == 2 || v == 4) {
		n.Add(vogue.FieldError{Field: "courseCount", Rule: "oneof", Param: "1,2,4", Value: strconv.FormatInt(v, 10), Message: "courseCount must be one of: 1,2,4"})
	}

	if err := n.ErrOrNil(); err != nil {
		return CourseCount{}, err
	}
	return CourseCount{v: v}, nil
}

// ParseCourseCount reads a base-10 representation and validates it.
func ParseCourseCount(raw string) (CourseCount, error) {
	v, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var n vogue.Notification
		n.Add(vogue.FieldError{Field: "courseCount", Rule: "int", Value: raw, Message: "courseCount must be a whole number"})
		return CourseCount{}, n.ErrOrNil()
	}
	return NewCourseCount(v)
}

// Int64 returns the validated value.
func (c CourseCount) Int64() int64 { return c.v }

// String returns the base-10 representation of the value.
func (c CourseCount) String() string { return strconv.FormatInt(c.v, 10) }

// IsZero reports whether the receiver is the zero CourseCount, which is the only
// CourseCount that never passed validation.
func (c CourseCount) IsZero() bool { return c.v == 0 }

// Equal reports whether both value objects hold the same value.
func (c CourseCount) Equal(other CourseCount) bool { return c.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json uses the text
// codec when a type implements it, so CourseCount round-trips through JSON without
// a MarshalJSON of its own.
func (c CourseCount) MarshalText() ([]byte, error) {
	return strconv.AppendInt(nil, c.v, 10), nil
}

// UnmarshalText implements encoding.TextUnmarshaler, re-running validation so
// no payload can produce a CourseCount the constructor would have rejected.
func (c *CourseCount) UnmarshalText(data []byte) error {
	parsed, err := ParseCourseCount(string(data))
	if err != nil {
		return err
	}
	*c = parsed
	return nil
}

// Value implements driver.Valuer.
func (c CourseCount) Value() (driver.Value, error) { return c.v, nil }

// Scan implements sql.Scanner for integer and text columns, re-running
// validation so a row that no longer satisfies the rules surfaces as a vogue
// error.
func (c *CourseCount) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*c = CourseCount{}
		return nil
	case int64:
		parsed, err := NewCourseCount(value)
		if err != nil {
			return err
		}
		*c = parsed
		return nil
	case string:
		return c.UnmarshalText([]byte(value))
	case []byte:
		return c.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into CourseCount", src)
	}
}

// Portions is a count of portions, which is always at least one.
//
// The value is held as an int64 so it survives every database driver and JSON
// number without a widening conversion at the boundary.
type Portions struct{ v int64 }

// NewPortions validates raw and returns the Portions it describes.
//
// Rules are applied in the order they were declared, and every failure is
// collected into one error rather than the first one aborting the rest.
func NewPortions(raw int64) (Portions, error) {
	var n vogue.Notification
	v := raw
	if !(v > 0) {
		n.Add(vogue.FieldError{Field: "portions", Rule: "positive", Value: strconv.FormatInt(v, 10), Message: "portions must be greater than zero"})
	}

	if err := n.ErrOrNil(); err != nil {
		return Portions{}, err
	}
	return Portions{v: v}, nil
}

// ParsePortions reads a base-10 representation and validates it.
func ParsePortions(raw string) (Portions, error) {
	v, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var n vogue.Notification
		n.Add(vogue.FieldError{Field: "portions", Rule: "int", Value: raw, Message: "portions must be a whole number"})
		return Portions{}, n.ErrOrNil()
	}
	return NewPortions(v)
}

// Int64 returns the validated value.
func (p Portions) Int64() int64 { return p.v }

// String returns the base-10 representation of the value.
func (p Portions) String() string { return strconv.FormatInt(p.v, 10) }

// IsZero reports whether the receiver is the zero Portions, which is the only
// Portions that never passed validation.
func (p Portions) IsZero() bool { return p.v == 0 }

// Equal reports whether both value objects hold the same value.
func (p Portions) Equal(other Portions) bool { return p.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json uses the text
// codec when a type implements it, so Portions round-trips through JSON without
// a MarshalJSON of its own.
func (p Portions) MarshalText() ([]byte, error) {
	return strconv.AppendInt(nil, p.v, 10), nil
}

// UnmarshalText implements encoding.TextUnmarshaler, re-running validation so
// no payload can produce a Portions the constructor would have rejected.
func (p *Portions) UnmarshalText(data []byte) error {
	parsed, err := ParsePortions(string(data))
	if err != nil {
		return err
	}
	*p = parsed
	return nil
}

// Value implements driver.Valuer.
func (p Portions) Value() (driver.Value, error) { return p.v, nil }

// Scan implements sql.Scanner for integer and text columns, re-running
// validation so a row that no longer satisfies the rules surfaces as a vogue
// error.
func (p *Portions) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*p = Portions{}
		return nil
	case int64:
		parsed, err := NewPortions(value)
		if err != nil {
			return err
		}
		*p = parsed
		return nil
	case string:
		return p.UnmarshalText([]byte(value))
	case []byte:
		return p.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into Portions", src)
	}
}

// StockLevel is a stock level, which may be nothing but never less.
//
// The value is held as an int64 so it survives every database driver and JSON
// number without a widening conversion at the boundary.
type StockLevel struct{ v int64 }

// NewStockLevel validates raw and returns the StockLevel it describes.
//
// Rules are applied in the order they were declared, and every failure is
// collected into one error rather than the first one aborting the rest.
func NewStockLevel(raw int64) (StockLevel, error) {
	var n vogue.Notification
	v := raw
	if !(v >= 0) {
		n.Add(vogue.FieldError{Field: "stockLevel", Rule: "nonneg", Value: strconv.FormatInt(v, 10), Message: "stockLevel must not be negative"})
	}

	if err := n.ErrOrNil(); err != nil {
		return StockLevel{}, err
	}
	return StockLevel{v: v}, nil
}

// ParseStockLevel reads a base-10 representation and validates it.
func ParseStockLevel(raw string) (StockLevel, error) {
	v, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var n vogue.Notification
		n.Add(vogue.FieldError{Field: "stockLevel", Rule: "int", Value: raw, Message: "stockLevel must be a whole number"})
		return StockLevel{}, n.ErrOrNil()
	}
	return NewStockLevel(v)
}

// Int64 returns the validated value.
func (s StockLevel) Int64() int64 { return s.v }

// String returns the base-10 representation of the value.
func (s StockLevel) String() string { return strconv.FormatInt(s.v, 10) }

// IsZero reports whether the receiver is the zero StockLevel, which is the only
// StockLevel that never passed validation.
func (s StockLevel) IsZero() bool { return s.v == 0 }

// Equal reports whether both value objects hold the same value.
func (s StockLevel) Equal(other StockLevel) bool { return s.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json uses the text
// codec when a type implements it, so StockLevel round-trips through JSON without
// a MarshalJSON of its own.
func (s StockLevel) MarshalText() ([]byte, error) {
	return strconv.AppendInt(nil, s.v, 10), nil
}

// UnmarshalText implements encoding.TextUnmarshaler, re-running validation so
// no payload can produce a StockLevel the constructor would have rejected.
func (s *StockLevel) UnmarshalText(data []byte) error {
	parsed, err := ParseStockLevel(string(data))
	if err != nil {
		return err
	}
	*s = parsed
	return nil
}

// Value implements driver.Valuer.
func (s StockLevel) Value() (driver.Value, error) { return s.v, nil }

// Scan implements sql.Scanner for integer and text columns, re-running
// validation so a row that no longer satisfies the rules surfaces as a vogue
// error.
func (s *StockLevel) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*s = StockLevel{}
		return nil
	case int64:
		parsed, err := NewStockLevel(value)
		if err != nil {
			return err
		}
		*s = parsed
		return nil
	case string:
		return s.UnmarshalText([]byte(value))
	case []byte:
		return s.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into StockLevel", src)
	}
}

// SlotMinutes is a booking length measured in whole quarter hours.
//
// The value is held as an int64 so it survives every database driver and JSON
// number without a widening conversion at the boundary.
type SlotMinutes struct{ v int64 }

// NewSlotMinutes validates raw and returns the SlotMinutes it describes.
//
// Rules are applied in the order they were declared, and every failure is
// collected into one error rather than the first one aborting the rest.
func NewSlotMinutes(raw int64) (SlotMinutes, error) {
	var n vogue.Notification
	v := raw
	if !(v%15 == 0) {
		n.Add(vogue.FieldError{Field: "slotMinutes", Rule: "multipleof", Param: "15", Value: strconv.FormatInt(v, 10), Message: "slotMinutes must be a multiple of 15"})
	}

	if err := n.ErrOrNil(); err != nil {
		return SlotMinutes{}, err
	}
	return SlotMinutes{v: v}, nil
}

// ParseSlotMinutes reads a base-10 representation and validates it.
func ParseSlotMinutes(raw string) (SlotMinutes, error) {
	v, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var n vogue.Notification
		n.Add(vogue.FieldError{Field: "slotMinutes", Rule: "int", Value: raw, Message: "slotMinutes must be a whole number"})
		return SlotMinutes{}, n.ErrOrNil()
	}
	return NewSlotMinutes(v)
}

// Int64 returns the validated value.
func (s SlotMinutes) Int64() int64 { return s.v }

// String returns the base-10 representation of the value.
func (s SlotMinutes) String() string { return strconv.FormatInt(s.v, 10) }

// IsZero reports whether the receiver is the zero SlotMinutes, which is the only
// SlotMinutes that never passed validation.
func (s SlotMinutes) IsZero() bool { return s.v == 0 }

// Equal reports whether both value objects hold the same value.
func (s SlotMinutes) Equal(other SlotMinutes) bool { return s.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json uses the text
// codec when a type implements it, so SlotMinutes round-trips through JSON without
// a MarshalJSON of its own.
func (s SlotMinutes) MarshalText() ([]byte, error) {
	return strconv.AppendInt(nil, s.v, 10), nil
}

// UnmarshalText implements encoding.TextUnmarshaler, re-running validation so
// no payload can produce a SlotMinutes the constructor would have rejected.
func (s *SlotMinutes) UnmarshalText(data []byte) error {
	parsed, err := ParseSlotMinutes(string(data))
	if err != nil {
		return err
	}
	*s = parsed
	return nil
}

// Value implements driver.Valuer.
func (s SlotMinutes) Value() (driver.Value, error) { return s.v, nil }

// Scan implements sql.Scanner for integer and text columns, re-running
// validation so a row that no longer satisfies the rules surfaces as a vogue
// error.
func (s *SlotMinutes) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*s = SlotMinutes{}
		return nil
	case int64:
		parsed, err := NewSlotMinutes(value)
		if err != nil {
			return err
		}
		*s = parsed
		return nil
	case string:
		return s.UnmarshalText([]byte(value))
	case []byte:
		return s.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into SlotMinutes", src)
	}
}
