// Code generated by vogue. DO NOT EDIT.

package catalogue

import (
	"testing"

	"github.com/MathiasHilgert/vogue/voguetest"
)

// TestTrimmedName runs the value-object suite against the examples the directive
// and its rules declare.
func TestTrimmedName(t *testing.T) {
	const (
		exampleTortilla                              = "Tortilla"
		exampleTheBlanksAroundAPastedValueAreDropped = "the blanks around a pasted value are dropped"
		exampleTortilla2                             = "  Tortilla  "
		exampleTabsAndNewlinesCountAsWhitespaceToo   = "tabs and newlines count as whitespace too"
		exampleTortilla3                             = "\tTortilla\n"
		exampleAnAlreadyCleanValueIsLeftAlone        = "an already clean value is left alone"
	)

	t.Parallel()

	voguetest.Scalar[TrimmedName, *TrimmedName, string]{
		Field:      "trimmedName",
		New:        NewTrimmedName,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, " "},
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleTheBlanksAroundAPastedValueAreDropped,
				Input: exampleTortilla2,
				Out:   exampleTortilla,
			},
			{
				Name:  exampleTabsAndNewlinesCountAsWhitespaceToo,
				Input: exampleTortilla3,
				Out:   exampleTortilla,
			},
			{
				Name:  exampleAnAlreadyCleanValueIsLeftAlone,
				Input: exampleTortilla,
				Out:   exampleTortilla,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestSquishedName runs the value-object suite against the examples the directive
// and its rules declare.
func TestSquishedName(t *testing.T) {
	const (
		exampleTortilla                         = "Tortilla"
		exampleARunOfSpacesBecomesOne           = "a run of spaces becomes one"
		exampleTortillaDePatatas                = "Tortilla   de  patatas"
		exampleTortillaDePatatas2               = "Tortilla de patatas"
		exampleTheEndsAreTrimmedAsWell          = "the ends are trimmed as well"
		exampleTortillaDePatatas3               = "  Tortilla de patatas  "
		exampleATabAndANewlineBecomePlainSpaces = "a tab and a newline become plain spaces"
		exampleTortillaDePatatas4               = "Tortilla\tde\npatatas"
	)

	t.Parallel()

	voguetest.Scalar[SquishedName, *SquishedName, string]{
		Field:      "squishedName",
		New:        NewSquishedName,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, " "},
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleARunOfSpacesBecomesOne,
				Input: exampleTortillaDePatatas,
				Out:   exampleTortillaDePatatas2,
			},
			{
				Name:  exampleTheEndsAreTrimmedAsWell,
				Input: exampleTortillaDePatatas3,
				Out:   exampleTortillaDePatatas2,
			},
			{
				Name:  exampleATabAndANewlineBecomePlainSpaces,
				Input: exampleTortillaDePatatas4,
				Out:   exampleTortillaDePatatas2,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestLoweredName runs the value-object suite against the examples the directive
// and its rules declare.
func TestLoweredName(t *testing.T) {
	const (
		exampleTortilla                                 = "Tortilla"
		exampleAnAddressIsFoldedToOneCanonicalSpelling  = "an address is folded to one canonical spelling"
		exampleWaiterExampleCom                         = "Waiter@Example.Com"
		exampleWaiterExampleCom2                        = "waiter@example.com"
		exampleAnAccentedCapitalFoldsLikeAnyOtherLetter = "an accented capital folds like any other letter"
		exampleRBOL                                     = "ÁRBOL"
		exampleRbol                                     = "árbol"
		exampleAValueAlreadyInLowerCaseIsLeftAlone      = "a value already in lower case is left alone"
		exampleAlready                                  = "already"
	)

	t.Parallel()

	voguetest.Scalar[LoweredName, *LoweredName, string]{
		Field:      "loweredName",
		New:        NewLoweredName,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, " "},
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleAnAddressIsFoldedToOneCanonicalSpelling,
				Input: exampleWaiterExampleCom,
				Out:   exampleWaiterExampleCom2,
			},
			{
				Name:  exampleAnAccentedCapitalFoldsLikeAnyOtherLetter,
				Input: exampleRBOL,
				Out:   exampleRbol,
			},
			{
				Name:  exampleAValueAlreadyInLowerCaseIsLeftAlone,
				Input: exampleAlready,
				Out:   exampleAlready,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestUpperedName runs the value-object suite against the examples the directive
// and its rules declare.
func TestUpperedName(t *testing.T) {
	const (
		exampleTortilla                                        = "Tortilla"
		exampleACurrencyCodeIsShoutedTheWayTheStandardWritesIt = "a currency code is shouted the way the standard writes it"
		exampleEur                                             = "eur"
		exampleEUR                                             = "EUR"
		exampleDigitsAndPunctuationAreLeftUntouched            = "digits and punctuation are left untouched"
		exampleSku12                                           = "sku-12"
		exampleSKU12                                           = "SKU-12"
		exampleAValueAlreadyInUpperCaseIsLeftAlone             = "a value already in upper case is left alone"
	)

	t.Parallel()

	voguetest.Scalar[UpperedName, *UpperedName, string]{
		Field:      "upperedName",
		New:        NewUpperedName,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, " "},
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleACurrencyCodeIsShoutedTheWayTheStandardWritesIt,
				Input: exampleEur,
				Out:   exampleEUR,
			},
			{
				Name:  exampleDigitsAndPunctuationAreLeftUntouched,
				Input: exampleSku12,
				Out:   exampleSKU12,
			},
			{
				Name:  exampleAValueAlreadyInUpperCaseIsLeftAlone,
				Input: exampleEUR,
				Out:   exampleEUR,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestTrimmedOnly runs the value-object suite against the examples the directive
// and its rules declare.
func TestTrimmedOnly(t *testing.T) {
	const (
		exampleTheBlanksAroundAPastedValueAreDropped = "the blanks around a pasted value are dropped"
		exampleTortilla2                             = "  Tortilla  "
		exampleTortilla                              = "Tortilla"
		exampleTabsAndNewlinesCountAsWhitespaceToo   = "tabs and newlines count as whitespace too"
		exampleTortilla3                             = "\tTortilla\n"
		exampleAnAlreadyCleanValueIsLeftAlone        = "an already clean value is left alone"
	)

	t.Parallel()

	voguetest.Scalar[TrimmedOnly, *TrimmedOnly, string]{
		Field:      "trimmedOnly",
		New:        NewTrimmedOnly,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: nil,
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleTheBlanksAroundAPastedValueAreDropped,
				Input: exampleTortilla2,
				Out:   exampleTortilla,
			},
			{
				Name:  exampleTabsAndNewlinesCountAsWhitespaceToo,
				Input: exampleTortilla3,
				Out:   exampleTortilla,
			},
			{
				Name:  exampleAnAlreadyCleanValueIsLeftAlone,
				Input: exampleTortilla,
				Out:   exampleTortilla,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestSquishedOnly runs the value-object suite against the examples the directive
// and its rules declare.
func TestSquishedOnly(t *testing.T) {
	const (
		exampleARunOfSpacesBecomesOne           = "a run of spaces becomes one"
		exampleTortillaDePatatas                = "Tortilla   de  patatas"
		exampleTortillaDePatatas2               = "Tortilla de patatas"
		exampleTheEndsAreTrimmedAsWell          = "the ends are trimmed as well"
		exampleTortillaDePatatas3               = "  Tortilla de patatas  "
		exampleATabAndANewlineBecomePlainSpaces = "a tab and a newline become plain spaces"
		exampleTortillaDePatatas4               = "Tortilla\tde\npatatas"
	)

	t.Parallel()

	voguetest.Scalar[SquishedOnly, *SquishedOnly, string]{
		Field:      "squishedOnly",
		New:        NewSquishedOnly,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: nil,
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleARunOfSpacesBecomesOne,
				Input: exampleTortillaDePatatas,
				Out:   exampleTortillaDePatatas2,
			},
			{
				Name:  exampleTheEndsAreTrimmedAsWell,
				Input: exampleTortillaDePatatas3,
				Out:   exampleTortillaDePatatas2,
			},
			{
				Name:  exampleATabAndANewlineBecomePlainSpaces,
				Input: exampleTortillaDePatatas4,
				Out:   exampleTortillaDePatatas2,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestLoweredOnly runs the value-object suite against the examples the directive
// and its rules declare.
func TestLoweredOnly(t *testing.T) {
	const (
		exampleAnAddressIsFoldedToOneCanonicalSpelling  = "an address is folded to one canonical spelling"
		exampleWaiterExampleCom                         = "Waiter@Example.Com"
		exampleWaiterExampleCom2                        = "waiter@example.com"
		exampleAnAccentedCapitalFoldsLikeAnyOtherLetter = "an accented capital folds like any other letter"
		exampleRBOL                                     = "ÁRBOL"
		exampleRbol                                     = "árbol"
		exampleAValueAlreadyInLowerCaseIsLeftAlone      = "a value already in lower case is left alone"
		exampleAlready                                  = "already"
	)

	t.Parallel()

	voguetest.Scalar[LoweredOnly, *LoweredOnly, string]{
		Field:      "loweredOnly",
		New:        NewLoweredOnly,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: nil,
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleAnAddressIsFoldedToOneCanonicalSpelling,
				Input: exampleWaiterExampleCom,
				Out:   exampleWaiterExampleCom2,
			},
			{
				Name:  exampleAnAccentedCapitalFoldsLikeAnyOtherLetter,
				Input: exampleRBOL,
				Out:   exampleRbol,
			},
			{
				Name:  exampleAValueAlreadyInLowerCaseIsLeftAlone,
				Input: exampleAlready,
				Out:   exampleAlready,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestUpperedOnly runs the value-object suite against the examples the directive
// and its rules declare.
func TestUpperedOnly(t *testing.T) {
	const (
		exampleACurrencyCodeIsShoutedTheWayTheStandardWritesIt = "a currency code is shouted the way the standard writes it"
		exampleEur                                             = "eur"
		exampleEUR                                             = "EUR"
		exampleDigitsAndPunctuationAreLeftUntouched            = "digits and punctuation are left untouched"
		exampleSku12                                           = "sku-12"
		exampleSKU12                                           = "SKU-12"
		exampleAValueAlreadyInUpperCaseIsLeftAlone             = "a value already in upper case is left alone"
	)

	t.Parallel()

	voguetest.Scalar[UpperedOnly, *UpperedOnly, string]{
		Field:      "upperedOnly",
		New:        NewUpperedOnly,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: nil,
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleACurrencyCodeIsShoutedTheWayTheStandardWritesIt,
				Input: exampleEur,
				Out:   exampleEUR,
			},
			{
				Name:  exampleDigitsAndPunctuationAreLeftUntouched,
				Input: exampleSku12,
				Out:   exampleSKU12,
			},
			{
				Name:  exampleAValueAlreadyInUpperCaseIsLeftAlone,
				Input: exampleEUR,
				Out:   exampleEUR,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestRequiredName runs the value-object suite against the examples the directive
// and its rules declare.
func TestRequiredName(t *testing.T) {
	const (
		exampleTortilla              = "Tortilla"
		exampleRejectsTheEmptyString = "rejects the empty string"
	)

	t.Parallel()

	voguetest.Scalar[RequiredName, *RequiredName, string]{
		Field:      "requiredName",
		New:        NewRequiredName,
		Get:        RequiredName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, " "},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  exampleRejectsTheEmptyString,
				Input: "",
				Rules: []string{"required"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestShortName runs the value-object suite against the examples the directive
// and its rules declare.
func TestShortName(t *testing.T) {
	const exampleMin = "min"

	t.Parallel()

	voguetest.Scalar[ShortName, *ShortName, string]{
		Field:      "shortName",
		New:        NewShortName,
		Get:        ShortName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"a"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the empty string is shorter than one rune",
				Input: "",
				Rules: []string{exampleMin},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestLongerName runs the value-object suite against the examples the directive
// and its rules declare.
func TestLongerName(t *testing.T) {
	const exampleMin = "min"

	t.Parallel()

	voguetest.Scalar[LongerName, *LongerName, string]{
		Field:      "longerName",
		New:        NewLongerName,
		Get:        LongerName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"añó"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects two runes fall short of three",
				Input: "ab",
				Rules: []string{exampleMin},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestBoundedName runs the value-object suite against the examples the directive
// and its rules declare.
func TestBoundedName(t *testing.T) {
	const exampleMax = "max"

	t.Parallel()

	voguetest.Scalar[BoundedName, *BoundedName, string]{
		Field:      "boundedName",
		New:        NewBoundedName,
		Get:        BoundedName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"abcd", ""},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects one rune more than the bound holds",
				Input: "abcde",
				Rules: []string{exampleMax},
			},
			{
				Name:  "rejects five accented runes are five, not ten",
				Input: "añóra",
				Rules: []string{exampleMax},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestCurrencyCode runs the value-object suite against the examples the directive
// and its rules declare.
func TestCurrencyCode(t *testing.T) {
	const (
		exampleEUR = "EUR"
		exampleLen = "len"
	)

	t.Parallel()

	voguetest.Scalar[CurrencyCode, *CurrencyCode, string]{
		Field:      "currencyCode",
		New:        NewCurrencyCode,
		Get:        CurrencyCode.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleEUR, "añó"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a code one character short",
				Input: "EU",
				Rules: []string{exampleLen},
			},
			{
				Name:  "rejects a code one character long",
				Input: "EURO",
				Rules: []string{exampleLen},
			},
			{
				Name:  "rejects the empty string, which has no characters at all",
				Input: "",
				Rules: []string{exampleLen},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestEmailAddress runs the value-object suite against the examples the directive
// and its rules declare.
func TestEmailAddress(t *testing.T) {
	const (
		exampleWaiterExampleCom2     = "waiter@example.com"
		exampleEmail                 = "email"
		exampleRejectsTheEmptyString = "rejects the empty string"
	)

	t.Parallel()

	voguetest.Scalar[EmailAddress, *EmailAddress, string]{
		Field:      "emailAddress",
		New:        NewEmailAddress,
		Get:        EmailAddress.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleWaiterExampleCom2, "orders+tab7@example.com"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a local part with no domain",
				Input: "waiter",
				Rules: []string{exampleEmail},
			},
			{
				Name:  "rejects a display name, which a stored address must not carry",
				Input: "Waiter <a@b.test>",
				Rules: []string{exampleEmail},
			},
			{
				Name:  exampleRejectsTheEmptyString,
				Input: "",
				Rules: []string{exampleEmail},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestMenuLink runs the value-object suite against the examples the directive
// and its rules declare.
func TestMenuLink(t *testing.T) {
	const (
		exampleUrl                   = "url"
		exampleRejectsTheEmptyString = "rejects the empty string"
	)

	t.Parallel()

	voguetest.Scalar[MenuLink, *MenuLink, string]{
		Field:      "menuLink",
		New:        NewMenuLink,
		Get:        MenuLink.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"https://example.com/menu", "http://example.com:8080/menu?tab=7"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a bare host with no scheme",
				Input: "example.com",
				Rules: []string{exampleUrl},
			},
			{
				Name:  "rejects a scheme that is not http or https",
				Input: "ftp://example.com",
				Rules: []string{exampleUrl},
			},
			{
				Name:  exampleRejectsTheEmptyString,
				Input: "",
				Rules: []string{exampleUrl},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestExternalRef runs the value-object suite against the examples the directive
// and its rules declare.
func TestExternalRef(t *testing.T) {
	const (
		exampleUuid                  = "uuid"
		exampleRejectsTheEmptyString = "rejects the empty string"
	)

	t.Parallel()

	voguetest.Scalar[ExternalRef, *ExternalRef, string]{
		Field:      "externalRef",
		New:        NewExternalRef,
		Get:        ExternalRef.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"9b2b4f52-1c2d-4e5a-9f3b-6d7c8e9f0a1b", "018f3a2b-7c4d-7e8f-9a0b-1c2d3e4f5a6b"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the undashed form, which stored ids never use",
				Input: "9b2b4f521c2d4e5a9f3b6d7c8e9f0a1b",
				Rules: []string{exampleUuid},
			},
			{
				Name:  "rejects a value that is not hexadecimal at all",
				Input: "not-a-uuid",
				Rules: []string{exampleUuid},
			},
			{
				Name:  exampleRejectsTheEmptyString,
				Input: "",
				Rules: []string{exampleUuid},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestZoneName runs the value-object suite against the examples the directive
// and its rules declare.
func TestZoneName(t *testing.T) {
	const (
		exampleTimezone              = "timezone"
		exampleRejectsTheEmptyString = "rejects the empty string"
	)

	t.Parallel()

	voguetest.Scalar[ZoneName, *ZoneName, string]{
		Field:      "zoneName",
		New:        NewZoneName,
		Get:        ZoneName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"America/Argentina/Buenos_Aires", "UTC"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a zone the database does not hold",
				Input: "Mars/Olympus_Mons",
				Rules: []string{exampleTimezone},
			},
			{
				Name:  "rejects the process-local zone, which names no place",
				Input: "Local",
				Rules: []string{exampleTimezone},
			},
			{
				Name:  exampleRejectsTheEmptyString,
				Input: "",
				Rules: []string{exampleTimezone},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestStockCode runs the value-object suite against the examples the directive
// and its rules declare.
func TestStockCode(t *testing.T) {
	const (
		exampleSKU0042 = "SKU-0042"
		exampleSku0042 = "sku-0042"
		exampleRegex   = "regex"
	)

	t.Parallel()

	voguetest.Scalar[StockCode, *StockCode, string]{
		Field:      "stockCode",
		New:        NewStockCode,
		Get:        StockCode.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleSKU0042, "EUR-1000"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the prefix is not upper case",
				Input: exampleSku0042,
				Rules: []string{exampleRegex},
			},
			{
				Name:  "rejects the number is too short",
				Input: "SKU-42",
				Rules: []string{exampleRegex},
			},
			{
				Name:  "rejects the empty string, which an anchored pattern rejects",
				Input: "",
				Rules: []string{exampleRegex},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestCurrency runs the value-object suite against the examples the directive
// and its rules declare.
func TestCurrency(t *testing.T) {
	const (
		exampleEur   = "eur"
		exampleOneof = "oneof"
		exampleEUR   = "EUR"
	)

	t.Parallel()

	voguetest.Scalar[Currency, *Currency, string]{
		Field:      "currency",
		New:        NewCurrency,
		Get:        Currency.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleEur, "gbp"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a currency nobody listed",
				Input: "chf",
				Rules: []string{exampleOneof},
			},
			{
				Name:  "rejects the right item in the wrong case",
				Input: exampleEUR,
				Rules: []string{exampleOneof},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestLetterName runs the value-object suite against the examples the directive
// and its rules declare.
func TestLetterName(t *testing.T) {
	const exampleTortilla = "Tortilla"

	t.Parallel()

	voguetest.Scalar[LetterName, *LetterName, string]{
		Field:      "letterName",
		New:        NewLetterName,
		Get:        LetterName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, "Muñoz"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a digit among the letters",
				Input: "Tab7",
				Rules: []string{"alpha"},
			},
			{
				Name:  "rejects a space, which is not a letter",
				Input: "de patatas",
				Rules: []string{"alpha"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestHandle runs the value-object suite against the examples the directive
// and its rules declare.
func TestHandle(t *testing.T) {
	const exampleSku0042 = "sku-0042"

	t.Parallel()

	voguetest.Scalar[Handle, *Handle, string]{
		Field:      "handle",
		New:        NewHandle,
		Get:        Handle.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"Tab7", "sku0042"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a hyphen, which is neither a letter nor a digit",
				Input: exampleSku0042,
				Rules: []string{"alphanum"},
			},
			{
				Name:  "rejects a space",
				Input: "tab 7",
				Rules: []string{"alphanum"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestPhoneDigits runs the value-object suite against the examples the directive
// and its rules declare.
func TestPhoneDigits(t *testing.T) {
	const exampleNumeric = "numeric"

	t.Parallel()

	voguetest.Scalar[PhoneDigits, *PhoneDigits, string]{
		Field:      "phoneDigits",
		New:        NewPhoneDigits,
		Get:        PhoneDigits.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"0042", "600123456"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a sign, which a digit string does not carry",
				Input: "-42",
				Rules: []string{exampleNumeric},
			},
			{
				Name:  "rejects a decimal point",
				Input: "4.2",
				Rules: []string{exampleNumeric},
			},
			{
				Name:  "rejects Arabic-Indic digits, which no parser here would read",
				Input: "٤٢",
				Rules: []string{exampleNumeric},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestLegacyCode runs the value-object suite against the examples the directive
// and its rules declare.
func TestLegacyCode(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[LegacyCode, *LegacyCode, string]{
		Field:      "legacyCode",
		New:        NewLegacyCode,
		Get:        LegacyCode.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"tortilla", "SKU-0042!"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects an accented letter above U+007F",
				Input: "Muñoz",
				Rules: []string{"ascii"},
			},
			{
				Name:  "rejects a combining accent, which is not ASCII either",
				Input: "café",
				Rules: []string{"ascii"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestSingleLine runs the value-object suite against the examples the directive
// and its rules declare.
func TestSingleLine(t *testing.T) {
	const exampleTortillaDePatatas2 = "Tortilla de patatas"

	t.Parallel()

	voguetest.Scalar[SingleLine, *SingleLine, string]{
		Field:      "singleLine",
		New:        NewSingleLine,
		Get:        SingleLine.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortillaDePatatas2, "Muñoz — 42 €"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a newline smuggled into a single-line value",
				Input: "Tortilla\nde patatas",
				Rules: []string{"printable"},
			},
			{
				Name:  "rejects a tab, which is a control character too",
				Input: "Tab\t7",
				Rules: []string{"printable"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestSlug runs the value-object suite against the examples the directive
// and its rules declare.
func TestSlug(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[Slug, *Slug, string]{
		Field:      "slug",
		New:        NewSlug,
		Get:        Slug.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"tortilla-de-patatas", "SKU0042"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a space in the middle",
				Input: "tortilla de patatas",
				Rules: []string{"nospace"},
			},
			{
				Name:  "rejects a trailing space a paste left behind",
				Input: "sku0042 ",
				Rules: []string{"nospace"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestProductCode runs the value-object suite against the examples the directive
// and its rules declare.
func TestProductCode(t *testing.T) {
	const (
		exampleSKU0042 = "SKU-0042"
		exampleSku0042 = "sku-0042"
		examplePrefix  = "prefix"
	)

	t.Parallel()

	voguetest.Scalar[ProductCode, *ProductCode, string]{
		Field:      "productCode",
		New:        NewProductCode,
		Get:        ProductCode.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleSKU0042, "SKU-"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the right prefix in the wrong case",
				Input: exampleSku0042,
				Rules: []string{examplePrefix},
			},
			{
				Name:  "rejects no namespace at all",
				Input: "0042",
				Rules: []string{examplePrefix},
			},
			{
				Name:  "rejects the empty string, which starts with nothing",
				Input: "",
				Rules: []string{examplePrefix},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestDocumentFile runs the value-object suite against the examples the directive
// and its rules declare.
func TestDocumentFile(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[DocumentFile, *DocumentFile, string]{
		Field:      "documentFile",
		New:        NewDocumentFile,
		Get:        DocumentFile.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"invoice.pdf", ".pdf"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the right extension in the wrong case",
				Input: "invoice.PDF",
				Rules: []string{"suffix"},
			},
			{
				Name:  "rejects a different extension",
				Input: "invoice.png",
				Rules: []string{"suffix"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestResourcePath runs the value-object suite against the examples the directive
// and its rules declare.
func TestResourcePath(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[ResourcePath, *ResourcePath, string]{
		Field:      "resourcePath",
		New:        NewResourcePath,
		Get:        ResourcePath.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"tabs/7", "/"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a different separator",
				Input: "tabs-7",
				Rules: []string{"contains"},
			},
			{
				Name:  "rejects the empty string, which contains nothing",
				Input: "",
				Rules: []string{"contains"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestFlatName runs the value-object suite against the examples the directive
// and its rules declare.
func TestFlatName(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[FlatName, *FlatName, string]{
		Field:      "flatName",
		New:        NewFlatName,
		Get:        FlatName.String,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"tabs-7", ""},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects the forbidden separator in the middle",
				Input: "tabs/7",
				Rules: []string{"excludes"},
			},
			{
				Name:  "rejects the forbidden separator at the front",
				Input: "/tabs",
				Rules: []string{"excludes"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestCovers runs the value-object suite against the examples the directive
// and its rules declare.
func TestCovers(t *testing.T) {
	const (
		exampleInt = "int"
		exampleMin = "min"
	)

	t.Parallel()

	voguetest.Scalar[Covers, *Covers, int64]{
		Field:      "covers",
		New:        NewCovers,
		Get:        Covers.Int64,
		FromString: NewCoversFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{1, 42},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects a table with nobody at it",
				Input: 0,
				Rules: []string{exampleMin},
			},
			{
				Name:  "rejects a negative count is below any positive bound",
				Input: -5,
				Rules: []string{exampleMin},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestSeats runs the value-object suite against the examples the directive
// and its rules declare.
func TestSeats(t *testing.T) {
	const (
		exampleInt = "int"
		exampleMax = "max"
	)

	t.Parallel()

	voguetest.Scalar[Seats, *Seats, int64]{
		Field:      "seats",
		New:        NewSeats,
		Get:        Seats.Int64,
		FromString: NewSeatsFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{200, -1},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects one guest more than the room holds",
				Input: 201,
				Rules: []string{exampleMax},
			},
			{
				Name:  "rejects a value far above the bound",
				Input: 1000,
				Rules: []string{exampleMax},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestCourseCount runs the value-object suite against the examples the directive
// and its rules declare.
func TestCourseCount(t *testing.T) {
	const (
		exampleInt   = "int"
		exampleOneof = "oneof"
	)

	t.Parallel()

	voguetest.Scalar[CourseCount, *CourseCount, int64]{
		Field:      "courseCount",
		New:        NewCourseCount,
		Get:        CourseCount.Int64,
		FromString: NewCourseCountFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{1, 4},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects a number between two allowed ones",
				Input: 3,
				Rules: []string{exampleOneof},
			},
			{
				Name:  "rejects a number below the whole list",
				Input: 0,
				Rules: []string{exampleOneof},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestPortions runs the value-object suite against the examples the directive
// and its rules declare.
func TestPortions(t *testing.T) {
	const (
		exampleInt      = "int"
		examplePositive = "positive"
	)

	t.Parallel()

	voguetest.Scalar[Portions, *Portions, int64]{
		Field:      "portions",
		New:        NewPortions,
		Get:        Portions.Int64,
		FromString: NewPortionsFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{1, 42},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects zero, which is not positive",
				Input: 0,
				Rules: []string{examplePositive},
			},
			{
				Name:  "rejects a negative count",
				Input: -1,
				Rules: []string{examplePositive},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestStockLevel runs the value-object suite against the examples the directive
// and its rules declare.
func TestStockLevel(t *testing.T) {
	const (
		exampleInt    = "int"
		exampleNonneg = "nonneg"
	)

	t.Parallel()

	voguetest.Scalar[StockLevel, *StockLevel, int64]{
		Field:      "stockLevel",
		New:        NewStockLevel,
		Get:        StockLevel.Int64,
		FromString: NewStockLevelFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{0, 7},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects one below the floor",
				Input: -1,
				Rules: []string{exampleNonneg},
			},
			{
				Name:  "rejects a quantity nobody can have",
				Input: -100,
				Rules: []string{exampleNonneg},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestSlotMinutes runs the value-object suite against the examples the directive
// and its rules declare.
func TestSlotMinutes(t *testing.T) {
	const exampleInt = "int"

	t.Parallel()

	voguetest.Scalar[SlotMinutes, *SlotMinutes, int64]{
		Field:      "slotMinutes",
		New:        NewSlotMinutes,
		Get:        SlotMinutes.Int64,
		FromString: NewSlotMinutesFromString,
		ParseRule:  exampleInt,
		Examples:   nil,
		Candidates: []int64{30, 0, -15},
		Rejected: []voguetest.Rejection[int64]{
			{
				Name:  "rejects a duration that does not fill whole slots",
				Input: 20,
				Rules: []string{"multipleof"},
			},
			{
				Name:  "rejects less than one slot",
				Input: 1,
				Rules: []string{"multipleof"},
			},
		},
		Normalized:   nil,
		RefusesFloat: false,
	}.Run(t)
}

// TestMinRate runs the value-object suite against the examples the directive
// and its rules declare.
func TestMinRate(t *testing.T) {
	const (
		exampleDecimal = "decimal"
		exampleMin     = "min"
	)

	t.Parallel()

	voguetest.Scalar[MinRate, *MinRate, string]{
		Field:      "minRate",
		New:        NewMinRateFromString,
		Get:        nil,
		FromString: NewMinRateFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{"0.5", "0"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a quarter below a floor of nothing",
				Input: "-0.25",
				Rules: []string{exampleMin},
			},
			{
				Name:  "rejects a whole unit below the floor",
				Input: "-1",
				Rules: []string{exampleMin},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestMaxRate runs the value-object suite against the examples the directive
// and its rules declare.
func TestMaxRate(t *testing.T) {
	const (
		exampleDecimal = "decimal"
		example15      = "1.5"
		exampleMax     = "max"
	)

	t.Parallel()

	voguetest.Scalar[MaxRate, *MaxRate, string]{
		Field:      "maxRate",
		New:        NewMaxRateFromString,
		Get:        nil,
		FromString: NewMaxRateFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{"1", "0.25"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects half again more than the whole",
				Input: example15,
				Rules: []string{exampleMax},
			},
			{
				Name:  "rejects twice the whole bill",
				Input: "2",
				Rules: []string{exampleMax},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestUnitWeight runs the value-object suite against the examples the directive
// and its rules declare.
func TestUnitWeight(t *testing.T) {
	const (
		exampleDecimal  = "decimal"
		example15       = "1.5"
		examplePositive = "positive"
	)

	t.Parallel()

	voguetest.Scalar[UnitWeight, *UnitWeight, string]{
		Field:      "unitWeight",
		New:        NewUnitWeightFromString,
		Get:        nil,
		FromString: NewUnitWeightFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{example15, "0.001"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects zero written at three decimal places is still zero",
				Input: "0.000",
				Rules: []string{examplePositive},
			},
			{
				Name:  "rejects half a unit less than nothing",
				Input: "-0.5",
				Rules: []string{examplePositive},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestShelfWeight runs the value-object suite against the examples the directive
// and its rules declare.
func TestShelfWeight(t *testing.T) {
	const (
		exampleDecimal = "decimal"
		exampleNonneg  = "nonneg"
	)

	t.Parallel()

	voguetest.Scalar[ShelfWeight, *ShelfWeight, string]{
		Field:      "shelfWeight",
		New:        NewShelfWeightFromString,
		Get:        nil,
		FromString: NewShelfWeightFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{"0", "12.750"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a hundredth below the floor",
				Input: "-0.01",
				Rules: []string{exampleNonneg},
			},
			{
				Name:  "rejects a quantity nobody can have",
				Input: "-100",
				Rules: []string{exampleNonneg},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestTaxRate runs the value-object suite against the examples the directive
// and its rules declare.
func TestTaxRate(t *testing.T) {
	const exampleDecimal = "decimal"

	t.Parallel()

	voguetest.Scalar[TaxRate, *TaxRate, string]{
		Field:      "taxRate",
		New:        NewTaxRateFromString,
		Get:        nil,
		FromString: NewTaxRateFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{"0.1234", "0.5"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects one decimal place more than the column holds",
				Input: "0.12345",
				Rules: []string{"scale"},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestPreciseWeight runs the value-object suite against the examples the directive
// and its rules declare.
func TestPreciseWeight(t *testing.T) {
	const (
		exampleDecimal = "decimal"
		example15      = "1.5"
	)

	t.Parallel()

	voguetest.Scalar[PreciseWeight, *PreciseWeight, string]{
		Field:      "preciseWeight",
		New:        NewPreciseWeightFromString,
		Get:        nil,
		FromString: NewPreciseWeightFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{example15, "12.750"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects a weight measured finer than the scale reads",
				Input: "0.1234",
				Rules: []string{"scale"},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestAdjustment runs the value-object suite against the examples the directive
// and its rules declare.
func TestAdjustment(t *testing.T) {
	const exampleDecimal = "decimal"

	t.Parallel()

	voguetest.Scalar[Adjustment, *Adjustment, string]{
		Field:      "adjustment",
		New:        NewAdjustmentFromString,
		Get:        nil,
		FromString: NewAdjustmentFromString,
		ParseRule:  exampleDecimal,
		Examples:   nil,
		Candidates: []string{"1", "-0.5"},
		Rejected: []voguetest.Rejection[string]{
			{
				Name:  "rejects nothing to adjust",
				Input: "0",
				Rules: []string{"nonzero"},
			},
			{
				Name:  "rejects nothing, written to the cent",
				Input: "0.00",
				Rules: []string{"nonzero"},
			},
		},
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestLoweredCurrency runs the value-object suite against the examples the directive
// and its rules declare.
func TestLoweredCurrency(t *testing.T) {
	const (
		exampleEur                                      = "eur"
		exampleAnAddressIsFoldedToOneCanonicalSpelling  = "an address is folded to one canonical spelling"
		exampleWaiterExampleCom                         = "Waiter@Example.Com"
		exampleWaiterExampleCom2                        = "waiter@example.com"
		exampleAnAccentedCapitalFoldsLikeAnyOtherLetter = "an accented capital folds like any other letter"
		exampleRBOL                                     = "ÁRBOL"
		exampleRbol                                     = "árbol"
		exampleAValueAlreadyInLowerCaseIsLeftAlone      = "a value already in lower case is left alone"
		exampleAlready                                  = "already"
	)

	t.Parallel()

	voguetest.Scalar[LoweredCurrency, *LoweredCurrency, string]{
		Field:      "loweredCurrency",
		New:        NewLoweredCurrency,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleEur, "gbp"},
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleAnAddressIsFoldedToOneCanonicalSpelling,
				Input: exampleWaiterExampleCom,
				Out:   exampleWaiterExampleCom2,
			},
			{
				Name:  exampleAnAccentedCapitalFoldsLikeAnyOtherLetter,
				Input: exampleRBOL,
				Out:   exampleRbol,
			},
			{
				Name:  exampleAValueAlreadyInLowerCaseIsLeftAlone,
				Input: exampleAlready,
				Out:   exampleAlready,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestShoutedSku runs the value-object suite against the examples the directive
// and its rules declare.
func TestShoutedSku(t *testing.T) {
	const (
		exampleSKU0042                                         = "SKU-0042"
		exampleACurrencyCodeIsShoutedTheWayTheStandardWritesIt = "a currency code is shouted the way the standard writes it"
		exampleEur                                             = "eur"
		exampleEUR                                             = "EUR"
		exampleDigitsAndPunctuationAreLeftUntouched            = "digits and punctuation are left untouched"
		exampleSku12                                           = "sku-12"
		exampleSKU12                                           = "SKU-12"
		exampleAValueAlreadyInUpperCaseIsLeftAlone             = "a value already in upper case is left alone"
	)

	t.Parallel()

	voguetest.Scalar[ShoutedSku, *ShoutedSku, string]{
		Field:      "shoutedSku",
		New:        NewShoutedSku,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleSKU0042, "SKU-"},
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleACurrencyCodeIsShoutedTheWayTheStandardWritesIt,
				Input: exampleEur,
				Out:   exampleEUR,
			},
			{
				Name:  exampleDigitsAndPunctuationAreLeftUntouched,
				Input: exampleSku12,
				Out:   exampleSKU12,
			},
			{
				Name:  exampleAValueAlreadyInUpperCaseIsLeftAlone,
				Input: exampleEUR,
				Out:   exampleEUR,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestTrimmedSlug runs the value-object suite against the examples the directive
// and its rules declare.
func TestTrimmedSlug(t *testing.T) {
	const (
		exampleTheBlanksAroundAPastedValueAreDropped = "the blanks around a pasted value are dropped"
		exampleTortilla2                             = "  Tortilla  "
		exampleTortilla                              = "Tortilla"
		exampleTabsAndNewlinesCountAsWhitespaceToo   = "tabs and newlines count as whitespace too"
		exampleTortilla3                             = "\tTortilla\n"
		exampleAnAlreadyCleanValueIsLeftAlone        = "an already clean value is left alone"
	)

	t.Parallel()

	voguetest.Scalar[TrimmedSlug, *TrimmedSlug, string]{
		Field:      "trimmedSlug",
		New:        NewTrimmedSlug,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"tortilla-de-patatas", "SKU0042"},
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleTheBlanksAroundAPastedValueAreDropped,
				Input: exampleTortilla2,
				Out:   exampleTortilla,
			},
			{
				Name:  exampleTabsAndNewlinesCountAsWhitespaceToo,
				Input: exampleTortilla3,
				Out:   exampleTortilla,
			},
			{
				Name:  exampleAnAlreadyCleanValueIsLeftAlone,
				Input: exampleTortilla,
				Out:   exampleTortilla,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestSquishedLine runs the value-object suite against the examples the directive
// and its rules declare.
func TestSquishedLine(t *testing.T) {
	const (
		exampleTortillaDePatatas2               = "Tortilla de patatas"
		exampleARunOfSpacesBecomesOne           = "a run of spaces becomes one"
		exampleTortillaDePatatas                = "Tortilla   de  patatas"
		exampleTheEndsAreTrimmedAsWell          = "the ends are trimmed as well"
		exampleTortillaDePatatas3               = "  Tortilla de patatas  "
		exampleATabAndANewlineBecomePlainSpaces = "a tab and a newline become plain spaces"
		exampleTortillaDePatatas4               = "Tortilla\tde\npatatas"
	)

	t.Parallel()

	voguetest.Scalar[SquishedLine, *SquishedLine, string]{
		Field:      "squishedLine",
		New:        NewSquishedLine,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortillaDePatatas2, "Muñoz — 42 €"},
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleARunOfSpacesBecomesOne,
				Input: exampleTortillaDePatatas,
				Out:   exampleTortillaDePatatas2,
			},
			{
				Name:  exampleTheEndsAreTrimmedAsWell,
				Input: exampleTortillaDePatatas3,
				Out:   exampleTortillaDePatatas2,
			},
			{
				Name:  exampleATabAndANewlineBecomePlainSpaces,
				Input: exampleTortillaDePatatas4,
				Out:   exampleTortillaDePatatas2,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestLoweredFile runs the value-object suite against the examples the directive
// and its rules declare.
func TestLoweredFile(t *testing.T) {
	const (
		exampleAnAddressIsFoldedToOneCanonicalSpelling  = "an address is folded to one canonical spelling"
		exampleWaiterExampleCom                         = "Waiter@Example.Com"
		exampleWaiterExampleCom2                        = "waiter@example.com"
		exampleAnAccentedCapitalFoldsLikeAnyOtherLetter = "an accented capital folds like any other letter"
		exampleRBOL                                     = "ÁRBOL"
		exampleRbol                                     = "árbol"
		exampleAValueAlreadyInLowerCaseIsLeftAlone      = "a value already in lower case is left alone"
		exampleAlready                                  = "already"
	)

	t.Parallel()

	voguetest.Scalar[LoweredFile, *LoweredFile, string]{
		Field:      "loweredFile",
		New:        NewLoweredFile,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"invoice.pdf", ".pdf"},
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  exampleAnAddressIsFoldedToOneCanonicalSpelling,
				Input: exampleWaiterExampleCom,
				Out:   exampleWaiterExampleCom2,
			},
			{
				Name:  exampleAnAccentedCapitalFoldsLikeAnyOtherLetter,
				Input: exampleRBOL,
				Out:   exampleRbol,
			},
			{
				Name:  exampleAValueAlreadyInLowerCaseIsLeftAlone,
				Input: exampleAlready,
				Out:   exampleAlready,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}
