// Code generated by vogue. DO NOT EDIT.

package geo

import (
	"testing"

	"github.com/MathiasHilgert/vogue/voguetest"
)

// TestLatitude runs the value-object suite against the examples the directive
// and its rules declare.
func TestLatitude(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[Latitude, *Latitude, string]{
		Field:        "latitude",
		New:          NewLatitudeFromString,
		Get:          nil,
		FromString:   NewLatitudeFromString,
		ParseRule:    "decimal",
		Examples:     []string{"-34.603722"},
		Candidates:   nil,
		Rejected:     nil,
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}

// TestLongitude runs the value-object suite against the examples the directive
// and its rules declare.
func TestLongitude(t *testing.T) {
	t.Parallel()

	voguetest.Scalar[Longitude, *Longitude, string]{
		Field:        "longitude",
		New:          NewLongitudeFromString,
		Get:          nil,
		FromString:   NewLongitudeFromString,
		ParseRule:    "decimal",
		Examples:     []string{"-58.381592"},
		Candidates:   nil,
		Rejected:     nil,
		Normalized:   nil,
		RefusesFloat: true,
	}.Run(t)
}
