// Code generated by vogue. DO NOT EDIT.

package geo

import (
	"errors"
	"fmt"

	"github.com/MathiasHilgert/vogue/examples/validation"
	"github.com/govalues/decimal"
)

// Latitude is a WGS 84 latitude in decimal degrees.
type Latitude struct {
	value decimal.Decimal
	set   bool
}

// NewLatitude validates raw and returns the Latitude it describes.
func NewLatitude(raw decimal.Decimal) (Latitude, error) {
	var latitude Latitude // stays zero unless every rule passes
	var failures validation.Validation

	const (
		minimumParameter = -90
		maximumParameter = 90
		scaleParameter   = 6
	)

	value := raw
	if value.Cmp(decimal.MustNew(minimumParameter, 0)) < 0 {
		failures.Add("latitude", "min", "must be at least -90")
	}
	if value.Cmp(decimal.MustNew(maximumParameter, 0)) > 0 {
		failures.Add("latitude", "max", "must be at most 90")
	}
	if value.Scale() > scaleParameter {
		failures.Add("latitude", "scale", "must have at most 6 decimal places")
	}

	err := failures.Err()
	if err != nil {
		return latitude, err
	}

	return Latitude{value: value, set: true}, nil
}

// NewLatitudeFromString reads an exact decimal number and validates it.
func NewLatitudeFromString(raw string) (Latitude, error) {
	value, err := decimal.Parse(raw)
	if err != nil {
		var failures validation.Validation
		failures.Add("latitude", "decimal", "must be an exact decimal number")

		return Latitude{}, failures.Err()
	}

	return NewLatitude(value)
}

// Decimal returns the validated value.
func (latitude Latitude) Decimal() decimal.Decimal { return latitude.value }

// String returns the canonical text, which keeps the scale: 1.50 stays "1.50".
func (latitude Latitude) String() string { return latitude.value.String() }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (latitude Latitude) IsZero() bool { return !latitude.set }

// Equal reports whether both hold the same number, so 1.5 equals 1.50.
func (latitude Latitude) Equal(other Latitude) bool {
	return latitude.set == other.set && latitude.value.Cmp(other.value) == 0
}

// MarshalText implements encoding.TextMarshaler; the zero Latitude has no text form.
func (latitude Latitude) MarshalText() ([]byte, error) {
	if latitude.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero Latitude: %w", errors.ErrUnsupported)
	}

	return []byte(latitude.value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (latitude *Latitude) UnmarshalText(data []byte) error {
	parsed, err := NewLatitudeFromString(string(data))
	if err != nil {
		return err
	}

	*latitude = parsed

	return nil
}

// Longitude is a WGS 84 longitude in decimal degrees.
type Longitude struct {
	value decimal.Decimal
	set   bool
}

// NewLongitude validates raw and returns the Longitude it describes.
func NewLongitude(raw decimal.Decimal) (Longitude, error) {
	var longitude Longitude // stays zero unless every rule passes
	var failures validation.Validation

	const (
		minimumParameter = -180
		maximumParameter = 180
		scaleParameter   = 6
	)

	value := raw
	if value.Cmp(decimal.MustNew(minimumParameter, 0)) < 0 {
		failures.Add("longitude", "min", "must be at least -180")
	}
	if value.Cmp(decimal.MustNew(maximumParameter, 0)) > 0 {
		failures.Add("longitude", "max", "must be at most 180")
	}
	if value.Scale() > scaleParameter {
		failures.Add("longitude", "scale", "must have at most 6 decimal places")
	}

	err := failures.Err()
	if err != nil {
		return longitude, err
	}

	return Longitude{value: value, set: true}, nil
}

// NewLongitudeFromString reads an exact decimal number and validates it.
func NewLongitudeFromString(raw string) (Longitude, error) {
	value, err := decimal.Parse(raw)
	if err != nil {
		var failures validation.Validation
		failures.Add("longitude", "decimal", "must be an exact decimal number")

		return Longitude{}, failures.Err()
	}

	return NewLongitude(value)
}

// Decimal returns the validated value.
func (longitude Longitude) Decimal() decimal.Decimal { return longitude.value }

// String returns the canonical text, which keeps the scale: 1.50 stays "1.50".
func (longitude Longitude) String() string { return longitude.value.String() }

// IsZero reports whether the receiver was never constructed; `json:",omitzero"` asks it.
func (longitude Longitude) IsZero() bool { return !longitude.set }

// Equal reports whether both hold the same number, so 1.5 equals 1.50.
func (longitude Longitude) Equal(other Longitude) bool {
	return longitude.set == other.set && longitude.value.Cmp(other.value) == 0
}

// MarshalText implements encoding.TextMarshaler; the zero Longitude has no text form.
func (longitude Longitude) MarshalText() ([]byte, error) {
	if longitude.IsZero() {
		return nil, fmt.Errorf("cannot marshal the zero Longitude: %w", errors.ErrUnsupported)
	}

	return []byte(longitude.value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler and validates like the constructor.
func (longitude *Longitude) UnmarshalText(data []byte) error {
	parsed, err := NewLongitudeFromString(string(data))
	if err != nil {
		return err
	}

	*longitude = parsed

	return nil
}
