// Code generated by vogue. DO NOT EDIT.

package geo

import (
	"github.com/MathiasHilgert/vogue/validation"
	"github.com/govalues/decimal"
)

// Latitude is a WGS 84 latitude in decimal degrees.
//
// The value is held as a decimal.Decimal: an exact base-10 number with no
// binary float underneath, so a rate, a percentage or a fractional quantity
// reads back as the value someone typed.
type Latitude struct {
	value decimal.Decimal
	set   bool
}

// NewLatitude validates raw and returns the Latitude it describes.
//
// Rules are applied in the order they were declared, and every failure is
// collected into one error rather than the first one aborting the rest.
func NewLatitude(raw decimal.Decimal) (Latitude, error) {
	const (
		minimumParameter = -90
		maximumParameter = 90
		scaleParameter   = 6
	)

	var notification validation.Notification

	value := raw
	if value.Cmp(decimal.MustNew(minimumParameter, 0)) < 0 {
		notification.Reject(
			"latitude",
			"min",
			"-90",
			value.String(),
			"latitude must be at least -90",
		)
	}
	if value.Cmp(decimal.MustNew(maximumParameter, 0)) > 0 {
		notification.Reject(
			"latitude",
			"max",
			"90",
			value.String(),
			"latitude must be at most 90",
		)
	}
	if value.Scale() > scaleParameter {
		notification.Reject(
			"latitude",
			"scale",
			"6",
			value.String(),
			"latitude must have at most 6 decimal places",
		)
	}

	if notification.HasErrors() {
		var zero Latitude

		// Only a rejected input escapes to the heap: the notification is
		// copied here, so the happy path above allocates nothing.
		failed := notification

		return zero, &failed
	}

	return Latitude{value: value, set: true}, nil
}

// NewLatitudeFromString reads a decimal representation and validates it. A
// representation decimal.Parse cannot read is reported as a failure of the
// "decimal" rule, so a caller handles it the same way as every other rule.
func NewLatitudeFromString(raw string) (Latitude, error) {
	value, err := decimal.Parse(raw)
	if err != nil {
		var (
			zero         Latitude
			notification validation.Notification
		)

		notification.Reject(
			"latitude",
			"decimal",
			"",
			raw,
			"latitude must be an exact decimal number",
		)

		return zero, &notification
	}

	return NewLatitude(value)
}

// Decimal returns the validated value.
func (latitude Latitude) Decimal() decimal.Decimal { return latitude.value }

// String returns the canonical representation of the value, which keeps the
// scale it was created with: 1.50 reads back as "1.50", not as "1.5".
func (latitude Latitude) String() string { return latitude.value.String() }

// IsZero reports whether the receiver is the zero Latitude: one that was never
// constructed, as opposed to one constructed from 0. It is what
// `json:",omitzero"` asks, and what Value stores as NULL.
func (latitude Latitude) IsZero() bool { return !latitude.set }

// Equal reports whether both value objects hold the same number.
//
// It compares with Cmp rather than with ==, because a decimal carries its
// scale: 1.5 and 1.50 are the same number written at two scales, and == would
// call them different. Two Latitude values that compare equal here may therefore
// still marshal to different text, which is what keeps a stored scale intact.
func (latitude Latitude) Equal(other Latitude) bool {
	return latitude.set == other.set && latitude.value.Cmp(other.value) == 0
}

// MarshalText implements encoding.TextMarshaler. encoding/json uses the text
// codec when a type implements it, so Latitude crosses a JSON boundary as a
// string and never as a float the receiver would have to round.
func (latitude Latitude) MarshalText() ([]byte, error) { return []byte(latitude.value.String()), nil }

// UnmarshalText implements encoding.TextUnmarshaler, re-running validation so
// no payload can produce a Latitude the constructor would have rejected.
func (latitude *Latitude) UnmarshalText(data []byte) error {
	parsed, err := NewLatitudeFromString(string(data))
	if err != nil {
		return err
	}

	*latitude = parsed

	return nil
}

// Longitude is a WGS 84 longitude in decimal degrees.
//
// The value is held as a decimal.Decimal: an exact base-10 number with no
// binary float underneath, so a rate, a percentage or a fractional quantity
// reads back as the value someone typed.
type Longitude struct {
	value decimal.Decimal
	set   bool
}

// NewLongitude validates raw and returns the Longitude it describes.
//
// Rules are applied in the order they were declared, and every failure is
// collected into one error rather than the first one aborting the rest.
func NewLongitude(raw decimal.Decimal) (Longitude, error) {
	const (
		minimumParameter = -180
		maximumParameter = 180
		scaleParameter   = 6
	)

	var notification validation.Notification

	value := raw
	if value.Cmp(decimal.MustNew(minimumParameter, 0)) < 0 {
		notification.Reject(
			"longitude",
			"min",
			"-180",
			value.String(),
			"longitude must be at least -180",
		)
	}
	if value.Cmp(decimal.MustNew(maximumParameter, 0)) > 0 {
		notification.Reject(
			"longitude",
			"max",
			"180",
			value.String(),
			"longitude must be at most 180",
		)
	}
	if value.Scale() > scaleParameter {
		notification.Reject(
			"longitude",
			"scale",
			"6",
			value.String(),
			"longitude must have at most 6 decimal places",
		)
	}

	if notification.HasErrors() {
		var zero Longitude

		// Only a rejected input escapes to the heap: the notification is
		// copied here, so the happy path above allocates nothing.
		failed := notification

		return zero, &failed
	}

	return Longitude{value: value, set: true}, nil
}

// NewLongitudeFromString reads a decimal representation and validates it. A
// representation decimal.Parse cannot read is reported as a failure of the
// "decimal" rule, so a caller handles it the same way as every other rule.
func NewLongitudeFromString(raw string) (Longitude, error) {
	value, err := decimal.Parse(raw)
	if err != nil {
		var (
			zero         Longitude
			notification validation.Notification
		)

		notification.Reject(
			"longitude",
			"decimal",
			"",
			raw,
			"longitude must be an exact decimal number",
		)

		return zero, &notification
	}

	return NewLongitude(value)
}

// Decimal returns the validated value.
func (longitude Longitude) Decimal() decimal.Decimal { return longitude.value }

// String returns the canonical representation of the value, which keeps the
// scale it was created with: 1.50 reads back as "1.50", not as "1.5".
func (longitude Longitude) String() string { return longitude.value.String() }

// IsZero reports whether the receiver is the zero Longitude: one that was never
// constructed, as opposed to one constructed from 0. It is what
// `json:",omitzero"` asks, and what Value stores as NULL.
func (longitude Longitude) IsZero() bool { return !longitude.set }

// Equal reports whether both value objects hold the same number.
//
// It compares with Cmp rather than with ==, because a decimal carries its
// scale: 1.5 and 1.50 are the same number written at two scales, and == would
// call them different. Two Longitude values that compare equal here may therefore
// still marshal to different text, which is what keeps a stored scale intact.
func (longitude Longitude) Equal(other Longitude) bool {
	return longitude.set == other.set && longitude.value.Cmp(other.value) == 0
}

// MarshalText implements encoding.TextMarshaler. encoding/json uses the text
// codec when a type implements it, so Longitude crosses a JSON boundary as a
// string and never as a float the receiver would have to round.
func (longitude Longitude) MarshalText() ([]byte, error) {
	return []byte(longitude.value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler, re-running validation so
// no payload can produce a Longitude the constructor would have rejected.
func (longitude *Longitude) UnmarshalText(data []byte) error {
	parsed, err := NewLongitudeFromString(string(data))
	if err != nil {
		return err
	}

	*longitude = parsed

	return nil
}
