// Package domain is the value-object package of the worked example: ordinary
// hand-written Go with nothing in it but directives, generated by the binary
// next door rather than by the shipped command, because one of its rules is
// the project's own.
//
//go:generate go run ../tools/vogue
package domain

// TaxID is the Argentine taxpayer identifier of a supplier. The `cuit` rule is
// this project's own; `trim` is a built-in, and writing it first is what makes
// the check run on the value that will actually be stored.
//vogue:string TaxID trim cuit

// LegalName is the name a supplier is registered under. It uses nothing but
// built-ins, which is what the same generator does for the rest of a project.
//vogue:string LegalName trim squish required min=2 max=200
