// Code generated by vogue. DO NOT EDIT.

package domain

import (
	"testing"

	"github.com/MathiasHilgert/vogue/voguetest"
)

// TestTaxID runs the value-object suite against the examples the directive
// and its rules declare.
func TestTaxID(t *testing.T) {
	const exampleTortilla = "Tortilla"

	t.Parallel()

	voguetest.Scalar[TaxID, *TaxID, string]{
		Field:      "taxID",
		New:        NewTaxID,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{"20123456786", "27123456780"},
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  "the blanks around a pasted value are dropped",
				Input: "  Tortilla  ",
				Out:   exampleTortilla,
			},
			{
				Name:  "tabs and newlines count as whitespace too",
				Input: "\tTortilla\n",
				Out:   exampleTortilla,
			},
			{
				Name:  "an already clean value is left alone",
				Input: exampleTortilla,
				Out:   exampleTortilla,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}

// TestLegalName runs the value-object suite against the examples the directive
// and its rules declare.
func TestLegalName(t *testing.T) {
	const (
		exampleTortilla          = "Tortilla"
		exampleTortillaDePatatas = "Tortilla de patatas"
	)

	t.Parallel()

	voguetest.Scalar[LegalName, *LegalName, string]{
		Field:      "legalName",
		New:        NewLegalName,
		Get:        nil,
		FromString: nil,
		ParseRule:  "",
		Examples:   nil,
		Candidates: []string{exampleTortilla, " "},
		Rejected:   nil,
		Normalized: []voguetest.Normalization[string]{
			{
				Name:  "the blanks around a pasted value are dropped",
				Input: "  Tortilla  ",
				Out:   exampleTortilla,
			},
			{
				Name:  "tabs and newlines count as whitespace too",
				Input: "\tTortilla\n",
				Out:   exampleTortilla,
			},
			{
				Name:  "an already clean value is left alone",
				Input: exampleTortilla,
				Out:   exampleTortilla,
			},
			{
				Name:  "a run of spaces becomes one",
				Input: "Tortilla   de  patatas",
				Out:   exampleTortillaDePatatas,
			},
			{
				Name:  "the ends are trimmed as well",
				Input: "  Tortilla de patatas  ",
				Out:   exampleTortillaDePatatas,
			},
			{
				Name:  "a tab and a newline become plain spaces",
				Input: "Tortilla\tde\npatatas",
				Out:   exampleTortillaDePatatas,
			},
		},
		RefusesFloat: false,
	}.Run(t)
}
