// Code generated by vogue. DO NOT EDIT.

package domain

import (
	"database/sql/driver"
	"fmt"
	"strings"
	"unicode/utf8"

	"github.com/MathiasHilgert/vogue/examples/customrule/cuit"
	"github.com/MathiasHilgert/vogue/validation"
)

// TaxID is the Argentine taxpayer identifier of a supplier. The `cuit` rule is
// this project's own; `trim` is a built-in, and writing it first is what makes
// the check run on the value that will actually be stored.
//
//nolint:recvcheck // Scan implements sql.Scanner and needs a pointer receiver.
type TaxID struct{ value string }

// NewTaxID validates raw and returns the TaxID it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [validation.FieldError] on a notification.
// Every failure is collected, so the returned error describes the whole input
// rather than the first thing that went wrong.
func NewTaxID(raw string) (TaxID, error) {
	var notification validation.Notification

	value := raw
	value = strings.TrimSpace(value)
	if !cuit.Valid(value) {
		notification.Reject(
			"taxId",
			"cuit",
			"",
			value,
			"taxId must be a valid CUIT",
		)
	}

	if notification.HasErrors() {
		var zero TaxID

		// Only a rejected input escapes to the heap: the notification is
		// copied here, so the happy path above allocates nothing.
		failed := notification

		return zero, &failed
	}

	return TaxID{value: value}, nil
}

// String returns the validated value.
func (taxId TaxID) String() string { return taxId.value }

// IsZero reports whether the receiver is the zero TaxID, which is the only
// TaxID that never passed validation.
func (taxId TaxID) IsZero() bool { return taxId.value == "" }

// Equal reports whether both value objects hold the same value.
func (taxId TaxID) Equal(other TaxID) bool { return taxId.value == other.value }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so TaxID marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (taxId TaxID) MarshalText() ([]byte, error) { return []byte(taxId.value), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a TaxID the constructor would have rejected.
func (taxId *TaxID) UnmarshalText(data []byte) error {
	parsed, err := NewTaxID(string(data))
	if err != nil {
		return err
	}

	*taxId = parsed

	return nil
}

// Value implements driver.Valuer.
func (taxId TaxID) Value() (driver.Value, error) { return taxId.value, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a validation error
// instead of an invalid value object.
func (taxId *TaxID) Scan(src any) error {
	switch source := src.(type) {
	case nil:
		var zero TaxID

		*taxId = zero

		return nil
	case string:
		return taxId.UnmarshalText([]byte(source))
	case []byte:
		return taxId.UnmarshalText(source)
	default:
		return fmt.Errorf("vogue: cannot scan %T into TaxID: %w", src, validation.ErrUnsupportedSource)
	}
}

// LegalName is the name a supplier is registered under. It uses nothing but
// built-ins, which is what the same generator does for the rest of a project.
//
//nolint:recvcheck // Scan implements sql.Scanner and needs a pointer receiver.
type LegalName struct{ value string }

// NewLegalName validates raw and returns the LegalName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [validation.FieldError] on a notification.
// Every failure is collected, so the returned error describes the whole input
// rather than the first thing that went wrong.
func NewLegalName(raw string) (LegalName, error) {
	const minimumParameter = 2

	const maximumParameter = 200

	var notification validation.Notification

	value := raw
	value = strings.TrimSpace(value)
	value = strings.Join(strings.Fields(value), " ")
	if value == "" {
		notification.Reject(
			"legalName",
			"required",
			"",
			value,
			"legalName is required",
		)
	}
	if utf8.RuneCountInString(value) < minimumParameter {
		notification.Reject(
			"legalName",
			"min",
			"2",
			value,
			"legalName must be at least 2",
		)
	}
	if utf8.RuneCountInString(value) > maximumParameter {
		notification.Reject(
			"legalName",
			"max",
			"200",
			value,
			"legalName must be at most 200",
		)
	}

	if notification.HasErrors() {
		var zero LegalName

		// Only a rejected input escapes to the heap: the notification is
		// copied here, so the happy path above allocates nothing.
		failed := notification

		return zero, &failed
	}

	return LegalName{value: value}, nil
}

// String returns the validated value.
func (legalName LegalName) String() string { return legalName.value }

// IsZero reports whether the receiver is the zero LegalName, which is the only
// LegalName that never passed validation.
func (legalName LegalName) IsZero() bool { return legalName.value == "" }

// Equal reports whether both value objects hold the same value.
func (legalName LegalName) Equal(other LegalName) bool { return legalName.value == other.value }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so LegalName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (legalName LegalName) MarshalText() ([]byte, error) { return []byte(legalName.value), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a LegalName the constructor would have rejected.
func (legalName *LegalName) UnmarshalText(data []byte) error {
	parsed, err := NewLegalName(string(data))
	if err != nil {
		return err
	}

	*legalName = parsed

	return nil
}

// Value implements driver.Valuer.
func (legalName LegalName) Value() (driver.Value, error) { return legalName.value, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a validation error
// instead of an invalid value object.
func (legalName *LegalName) Scan(src any) error {
	switch source := src.(type) {
	case nil:
		var zero LegalName

		*legalName = zero

		return nil
	case string:
		return legalName.UnmarshalText([]byte(source))
	case []byte:
		return legalName.UnmarshalText(source)
	default:
		return fmt.Errorf("vogue: cannot scan %T into LegalName: %w", src, validation.ErrUnsupportedSource)
	}
}
