// Code generated by vogue. DO NOT EDIT.

package domain

import (
	"testing"

	"github.com/MathiasHilgert/vogue/validation"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestNewTaxID exercises the constructor against the examples the rules of
// the directive declare: one accepted input, and one row per rejected input
// naming every rule that rejects it.
func TestNewTaxID(t *testing.T) {
	t.Parallel()

	// Arrange
	cases := []struct {
		name      string
		in        string
		wantRules []string
	}{
		{name: "accepts \"20123456786\"", in: "20123456786"},
		{name: "rejects the right shape with the wrong check digit", in: "20123456789", wantRules: []string{"cuit"}},
		{name: "rejects ten digits, one short", in: "2012345678", wantRules: []string{"cuit"}},
		{name: "rejects a punctuated CUIT, which is not what is stored", in: "20-12345678-6", wantRules: []string{"cuit"}},
		{name: "rejects a non-digit in the check position", in: "2012345678X", wantRules: []string{"cuit"}},
		{name: "rejects the empty string", in: "", wantRules: []string{"cuit"}},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			// Act
			got, err := NewTaxID(tc.in)

			// Assert
			if len(tc.wantRules) == 0 {
				require.NoError(t, err)
				assert.False(t, got.IsZero())
				return
			}
			require.Error(t, err)
			assert.True(t, got.IsZero(), "a rejected input must not produce a usable value object")
			for _, rule := range tc.wantRules {
				assert.ErrorIs(t, err, validation.FieldError{Field: "taxId", Rule: rule},
					"the %q rule was expected to reject the input", rule)
			}
		})
	}
}

// TestTaxID_TextRoundTrip proves a marshalled value object unmarshals back to
// an equal one, which is what a JSON boundary does to it.
func TestTaxID_TextRoundTrip(t *testing.T) {
	t.Parallel()

	// Arrange
	want, err := NewTaxID("20123456786")
	require.NoError(t, err)

	// Act
	text, err := want.MarshalText()
	require.NoError(t, err)

	var got TaxID
	err = got.UnmarshalText(text)

	// Assert
	require.NoError(t, err)
	assert.True(t, want.Equal(got), "%s did not survive the text round trip", want.String())
}

// TestTaxID_SQLRoundTrip proves a stored value object reads back equal.
func TestTaxID_SQLRoundTrip(t *testing.T) {
	t.Parallel()

	// Arrange
	want, err := NewTaxID("20123456786")
	require.NoError(t, err)

	// Act
	stored, err := want.Value()
	require.NoError(t, err)

	var got TaxID
	err = got.Scan(stored)

	// Assert
	require.NoError(t, err)
	assert.True(t, want.Equal(got), "%s did not survive the SQL round trip", want.String())
}

// TestTaxID_Scan covers the sources Scan accepts and the ones it refuses.
func TestTaxID_Scan(t *testing.T) {
	t.Parallel()

	t.Run("a NULL column produces the zero value", func(t *testing.T) {
		t.Parallel()

		// Arrange
		var got TaxID

		// Act
		err := got.Scan(nil)

		// Assert
		require.NoError(t, err)
		assert.True(t, got.IsZero())
	})

	t.Run("a stored value the rules reject is refused", func(t *testing.T) {
		t.Parallel()

		// Arrange
		var got TaxID

		// Act
		err := got.Scan("20123456789")

		// Assert
		require.Error(t, err)
		assert.True(t, got.IsZero())
	})

	t.Run("an unsupported source is refused", func(t *testing.T) {
		t.Parallel()

		// Arrange
		var got TaxID

		// Act
		err := got.Scan(struct{}{})

		// Assert
		require.Error(t, err)
		assert.Contains(t, err.Error(), "cannot scan")
	})
}

// TestTaxID_IsZero separates the zero value from a validated one.
func TestTaxID_IsZero(t *testing.T) {
	t.Parallel()

	// Arrange
	var zero TaxID
	built, err := NewTaxID("20123456786")
	require.NoError(t, err)

	// Act & Assert
	assert.True(t, zero.IsZero())
	assert.False(t, built.IsZero())
	assert.False(t, zero.Equal(built))
}

// TestNewLegalName exercises the constructor against the examples the rules of
// the directive declare: one accepted input, and one row per rejected input
// naming every rule that rejects it.
func TestNewLegalName(t *testing.T) {
	t.Parallel()

	// Arrange
	cases := []struct {
		name      string
		in        string
		wantRules []string
	}{
		{name: "accepts \"Tortilla\"", in: "Tortilla"},
		{name: "rejects the empty string", in: "", wantRules: []string{"required"}},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			// Act
			got, err := NewLegalName(tc.in)

			// Assert
			if len(tc.wantRules) == 0 {
				require.NoError(t, err)
				assert.False(t, got.IsZero())
				return
			}
			require.Error(t, err)
			assert.True(t, got.IsZero(), "a rejected input must not produce a usable value object")
			for _, rule := range tc.wantRules {
				assert.ErrorIs(t, err, validation.FieldError{Field: "legalName", Rule: rule},
					"the %q rule was expected to reject the input", rule)
			}
		})
	}
}

// TestNewLegalName_Normalizes proves the normalizers of the directive rewrite the
// value instead of only accepting it.
func TestNewLegalName_Normalizes(t *testing.T) {
	t.Parallel()

	// Arrange
	cases := []struct {
		name string
		in   string
		want string
	}{
		{name: "the blanks around a pasted value are dropped", in: "  Tortilla  ", want: "Tortilla"},
		{name: "tabs and newlines count as whitespace too", in: "\tTortilla\n", want: "Tortilla"},
		{name: "an already clean value is left alone", in: "Tortilla", want: "Tortilla"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			// Act
			got, err := NewLegalName(tc.in)

			// Assert
			require.NoError(t, err)
			assert.Equal(t, tc.want, got.String())
		})
	}
}

// TestLegalName_TextRoundTrip proves a marshalled value object unmarshals back to
// an equal one, which is what a JSON boundary does to it.
func TestLegalName_TextRoundTrip(t *testing.T) {
	t.Parallel()

	// Arrange
	want, err := NewLegalName("Tortilla")
	require.NoError(t, err)

	// Act
	text, err := want.MarshalText()
	require.NoError(t, err)

	var got LegalName
	err = got.UnmarshalText(text)

	// Assert
	require.NoError(t, err)
	assert.True(t, want.Equal(got), "%s did not survive the text round trip", want.String())
}

// TestLegalName_SQLRoundTrip proves a stored value object reads back equal.
func TestLegalName_SQLRoundTrip(t *testing.T) {
	t.Parallel()

	// Arrange
	want, err := NewLegalName("Tortilla")
	require.NoError(t, err)

	// Act
	stored, err := want.Value()
	require.NoError(t, err)

	var got LegalName
	err = got.Scan(stored)

	// Assert
	require.NoError(t, err)
	assert.True(t, want.Equal(got), "%s did not survive the SQL round trip", want.String())
}

// TestLegalName_Scan covers the sources Scan accepts and the ones it refuses.
func TestLegalName_Scan(t *testing.T) {
	t.Parallel()

	t.Run("a NULL column produces the zero value", func(t *testing.T) {
		t.Parallel()

		// Arrange
		var got LegalName

		// Act
		err := got.Scan(nil)

		// Assert
		require.NoError(t, err)
		assert.True(t, got.IsZero())
	})

	t.Run("an unsupported source is refused", func(t *testing.T) {
		t.Parallel()

		// Arrange
		var got LegalName

		// Act
		err := got.Scan(struct{}{})

		// Assert
		require.Error(t, err)
		assert.Contains(t, err.Error(), "cannot scan")
	})
}

// TestLegalName_IsZero separates the zero value from a validated one.
func TestLegalName_IsZero(t *testing.T) {
	t.Parallel()

	// Arrange
	var zero LegalName
	built, err := NewLegalName("Tortilla")
	require.NoError(t, err)

	// Act & Assert
	assert.True(t, zero.IsZero())
	assert.False(t, built.IsZero())
	assert.False(t, zero.Equal(built))
}
