// Code generated by vogue. DO NOT EDIT.

package domain

import (
	"database/sql/driver"
	"fmt"
	"strings"
	"unicode/utf8"

	"github.com/MathiasHilgert/vogue/examples/customrule/cuit"
	"github.com/MathiasHilgert/vogue/validation"
)

// TaxID is the Argentine taxpayer identifier of a supplier. The `cuit` rule is
// this project's own; `trim` is a built-in, and writing it first is what makes
// the check run on the value that will actually be stored.
type TaxID struct{ v string }

// NewTaxID validates raw and returns the TaxID it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [validation.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewTaxID(raw string) (TaxID, error) {
	var n validation.Notification
	v := raw
	v = strings.TrimSpace(v)
	if !(cuit.Valid(v)) {
		n.Add(validation.FieldError{Field: "taxId", Rule: "cuit", Value: v, Message: "taxId must be a valid CUIT"})
	}

	if err := n.ErrOrNil(); err != nil {
		return TaxID{}, err
	}
	return TaxID{v: v}, nil
}

// String returns the validated value.
func (t TaxID) String() string { return t.v }

// IsZero reports whether the receiver is the zero TaxID, which is the only
// TaxID that never passed validation.
func (t TaxID) IsZero() bool { return t.v == "" }

// Equal reports whether both value objects hold the same value.
func (t TaxID) Equal(other TaxID) bool { return t.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so TaxID marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (t TaxID) MarshalText() ([]byte, error) { return []byte(t.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a TaxID the constructor would have rejected.
func (t *TaxID) UnmarshalText(data []byte) error {
	parsed, err := NewTaxID(string(data))
	if err != nil {
		return err
	}
	*t = parsed
	return nil
}

// Value implements driver.Valuer.
func (t TaxID) Value() (driver.Value, error) { return t.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (t *TaxID) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*t = TaxID{}
		return nil
	case string:
		return t.UnmarshalText([]byte(value))
	case []byte:
		return t.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into TaxID: %w", src, validation.ErrUnsupportedSource)
	}
}

// LegalName is the name a supplier is registered under. It uses nothing but
// built-ins, which is what the same generator does for the rest of a project.
type LegalName struct{ v string }

// NewLegalName validates raw and returns the LegalName it describes.
//
// Rules are applied in the order they were declared: normalizers rewrite the
// working value, checks record a [validation.FieldError] on a notification. Every
// failure is collected, so the returned error describes the whole input rather
// than the first thing that went wrong.
func NewLegalName(raw string) (LegalName, error) {
	var n validation.Notification
	v := raw
	v = strings.TrimSpace(v)
	v = strings.Join(strings.Fields(v), " ")
	if !(v != "") {
		n.Add(validation.FieldError{Field: "legalName", Rule: "required", Value: v, Message: "legalName is required"})
	}
	if !(utf8.RuneCountInString(v) >= 2) {
		n.Add(validation.FieldError{Field: "legalName", Rule: "min", Param: "2", Value: v, Message: "legalName must be at least 2"})
	}
	if !(utf8.RuneCountInString(v) <= 200) {
		n.Add(validation.FieldError{Field: "legalName", Rule: "max", Param: "200", Value: v, Message: "legalName must be at most 200"})
	}

	if err := n.ErrOrNil(); err != nil {
		return LegalName{}, err
	}
	return LegalName{v: v}, nil
}

// String returns the validated value.
func (l LegalName) String() string { return l.v }

// IsZero reports whether the receiver is the zero LegalName, which is the only
// LegalName that never passed validation.
func (l LegalName) IsZero() bool { return l.v == "" }

// Equal reports whether both value objects hold the same value.
func (l LegalName) Equal(other LegalName) bool { return l.v == other.v }

// MarshalText implements encoding.TextMarshaler. encoding/json falls back to
// the text codec for types that implement it, so LegalName marshals and
// unmarshals as a JSON string without a MarshalJSON of its own, and works as a
// map key too.
func (l LegalName) MarshalText() ([]byte, error) { return []byte(l.v), nil }

// UnmarshalText implements encoding.TextUnmarshaler. It re-runs validation, so
// no payload can produce a LegalName the constructor would have rejected.
func (l *LegalName) UnmarshalText(data []byte) error {
	parsed, err := NewLegalName(string(data))
	if err != nil {
		return err
	}
	*l = parsed
	return nil
}

// Value implements driver.Valuer.
func (l LegalName) Value() (driver.Value, error) { return l.v, nil }

// Scan implements sql.Scanner for text columns. It re-runs validation, so a
// row that no longer satisfies the rules surfaces as a vogue error instead of
// an invalid value object.
func (l *LegalName) Scan(src any) error {
	switch value := src.(type) {
	case nil:
		*l = LegalName{}
		return nil
	case string:
		return l.UnmarshalText([]byte(value))
	case []byte:
		return l.UnmarshalText(value)
	default:
		return fmt.Errorf("vogue: cannot scan %T into LegalName: %w", src, validation.ErrUnsupportedSource)
	}
}
