// Package customrule is the worked example of extending vogue with a rule of
// your own.
//
// It is five files and no machinery:
//
//	cuit/cuit.go         the predicate: a pure function that imports nothing of vogue
//	cuitrule/cuitrule.go the rule: the vogue.Rule value pointing at the predicate
//	tools/vogue/main.go  the project's generator, built around generator.Run
//	domain/vo.go         the directives, with a //go:generate line
//	domain/vo_vogue*.go  the committed output, regenerated by `go generate`
//
// The generated files are committed and compared against a fresh run by the
// test in this package, so an example that stops matching what the generator
// produces fails the ordinary test run rather than quietly becoming wrong.
//
// A project follows the same shape: put the rule wherever it belongs, build
// one binary that hands it to [generator.Run], and point a //go:generate line
// at that binary. Nothing registers itself at run time, which is what lets the
// generator reject a directive naming a rule nobody passed.
package customrule
